// Copyright 2023 Redpanda Data, Inc.
//
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

// Code generated by cmd/enumgen. DO NOT EDIT.

package enums

import (
	"strings"

	controlplanev1 "buf.build/gen/go/redpandadata/cloud/protocolbuffers/go/redpanda/api/controlplane/v1"
	corev2 "buf.build/gen/go/redpandadata/core/protocolbuffers/go/redpanda/core/admin/v2"
	commonv1 "buf.build/gen/go/redpandadata/core/protocolbuffers/go/redpanda/core/common/v1"
	dataplanev1 "buf.build/gen/go/redpandadata/dataplane/protocolbuffers/go/redpanda/api/dataplane/v1"
)

// CommonACLOperationToString maps a proto enum value to its TF string form.
func CommonACLOperationToString(e commonv1.ACLOperation) string {
	return strings.TrimPrefix(e.String(), "ACL_OPERATION_")
}

// StringToCommonACLOperation maps a TF string back to the proto enum.
// Returns the UNSPECIFIED value for unknown inputs.
func StringToCommonACLOperation(s string) commonv1.ACLOperation {
	if v, ok := commonv1.ACLOperation_value["ACL_OPERATION_"+s]; ok {
		return commonv1.ACLOperation(v)
	}
	return commonv1.ACLOperation_ACL_OPERATION_UNSPECIFIED
}

// CommonACLPatternToString maps a proto enum value to its TF string form.
func CommonACLPatternToString(e commonv1.ACLPattern) string {
	return strings.TrimPrefix(e.String(), "ACL_PATTERN_")
}

// StringToCommonACLPattern maps a TF string back to the proto enum.
// Returns the UNSPECIFIED value for unknown inputs.
func StringToCommonACLPattern(s string) commonv1.ACLPattern {
	if v, ok := commonv1.ACLPattern_value["ACL_PATTERN_"+s]; ok {
		return commonv1.ACLPattern(v)
	}
	return commonv1.ACLPattern_ACL_PATTERN_UNSPECIFIED
}

// CommonACLPermissionTypeToString maps a proto enum value to its TF string form.
func CommonACLPermissionTypeToString(e commonv1.ACLPermissionType) string {
	return strings.TrimPrefix(e.String(), "ACL_PERMISSION_TYPE_")
}

// StringToCommonACLPermissionType maps a TF string back to the proto enum.
// Returns the UNSPECIFIED value for unknown inputs.
func StringToCommonACLPermissionType(s string) commonv1.ACLPermissionType {
	if v, ok := commonv1.ACLPermissionType_value["ACL_PERMISSION_TYPE_"+s]; ok {
		return commonv1.ACLPermissionType(v)
	}
	return commonv1.ACLPermissionType_ACL_PERMISSION_TYPE_UNSPECIFIED
}

// CommonACLResourceToString maps a proto enum value to its TF string form.
func CommonACLResourceToString(e commonv1.ACLResource) string {
	return strings.TrimPrefix(e.String(), "ACL_RESOURCE_")
}

// StringToCommonACLResource maps a TF string back to the proto enum.
// Returns the UNSPECIFIED value for unknown inputs.
func StringToCommonACLResource(s string) commonv1.ACLResource {
	if v, ok := commonv1.ACLResource_value["ACL_RESOURCE_"+s]; ok {
		return commonv1.ACLResource(v)
	}
	return commonv1.ACLResource_ACL_RESOURCE_UNSPECIFIED
}

// NetworkPeeringStateToString maps a proto enum value to its TF string form.
func NetworkPeeringStateToString(e controlplanev1.NetworkPeering_State) string {
	return strings.TrimPrefix(e.String(), "STATE_")
}

// StringToNetworkPeeringState maps a TF string back to the proto enum.
// Returns the UNSPECIFIED value for unknown inputs.
func StringToNetworkPeeringState(s string) controlplanev1.NetworkPeering_State {
	if v, ok := controlplanev1.NetworkPeering_State_value["STATE_"+s]; ok {
		return controlplanev1.NetworkPeering_State(v)
	}
	return controlplanev1.NetworkPeering_STATE_UNSPECIFIED
}

// OperationStateToString maps a proto enum value to its TF string form.
func OperationStateToString(e controlplanev1.Operation_State) string {
	return strings.TrimPrefix(e.String(), "STATE_")
}

// StringToOperationState maps a TF string back to the proto enum.
// Returns the UNSPECIFIED value for unknown inputs.
func StringToOperationState(s string) controlplanev1.Operation_State {
	if v, ok := controlplanev1.Operation_State_value["STATE_"+s]; ok {
		return controlplanev1.Operation_State(v)
	}
	return controlplanev1.Operation_STATE_UNSPECIFIED
}

// OperationTypeToString maps a proto enum value to its TF string form.
func OperationTypeToString(e controlplanev1.Operation_Type) string {
	return strings.TrimPrefix(e.String(), "TYPE_")
}

// StringToOperationType maps a TF string back to the proto enum.
// Returns the UNSPECIFIED value for unknown inputs.
func StringToOperationType(s string) controlplanev1.Operation_Type {
	if v, ok := controlplanev1.Operation_Type_value["TYPE_"+s]; ok {
		return controlplanev1.Operation_Type(v)
	}
	return controlplanev1.Operation_TYPE_UNSPECIFIED
}

// PrivateLinkAuthModeToString maps a proto enum value to its TF string form.
func PrivateLinkAuthModeToString(e controlplanev1.PrivateLinkAuthMode) string {
	return strings.TrimPrefix(e.String(), "PRIVATE_LINK_AUTH_MODE_")
}

// StringToPrivateLinkAuthMode maps a TF string back to the proto enum.
// Returns the UNSPECIFIED value for unknown inputs.
func StringToPrivateLinkAuthMode(s string) controlplanev1.PrivateLinkAuthMode {
	if v, ok := controlplanev1.PrivateLinkAuthMode_value["PRIVATE_LINK_AUTH_MODE_"+s]; ok {
		return controlplanev1.PrivateLinkAuthMode(v)
	}
	return controlplanev1.PrivateLinkAuthMode_PRIVATE_LINK_AUTH_MODE_UNSPECIFIED
}

// ShadowLink_StateToString maps a proto enum value to its TF string form.
func ShadowLink_StateToString(e controlplanev1.ShadowLink_State) string {
	return strings.TrimPrefix(e.String(), "STATE_")
}

// StringToShadowLink_State maps a TF string back to the proto enum.
// Returns the UNSPECIFIED value for unknown inputs.
func StringToShadowLink_State(s string) controlplanev1.ShadowLink_State {
	if v, ok := controlplanev1.ShadowLink_State_value["STATE_"+s]; ok {
		return controlplanev1.ShadowLink_State(v)
	}
	return controlplanev1.ShadowLink_STATE_UNSPECIFIED
}

// UpdateClusterMetadataUpdateClusterTypeToString maps a proto enum value to its TF string form.
func UpdateClusterMetadataUpdateClusterTypeToString(e controlplanev1.UpdateClusterMetadata_UpdateClusterType) string {
	return strings.TrimPrefix(e.String(), "UPDATE_CLUSTER_TYPE_")
}

// StringToUpdateClusterMetadataUpdateClusterType maps a TF string back to the proto enum.
// Returns the UNSPECIFIED value for unknown inputs.
func StringToUpdateClusterMetadataUpdateClusterType(s string) controlplanev1.UpdateClusterMetadata_UpdateClusterType {
	if v, ok := controlplanev1.UpdateClusterMetadata_UpdateClusterType_value["UPDATE_CLUSTER_TYPE_"+s]; ok {
		return controlplanev1.UpdateClusterMetadata_UpdateClusterType(v)
	}
	return controlplanev1.UpdateClusterMetadata_UPDATE_CLUSTER_TYPE_UNSPECIFIED
}

// FilterTypeToString maps a proto enum value to its TF string form.
func FilterTypeToString(e corev2.FilterType) string {
	return strings.TrimPrefix(e.String(), "FILTER_TYPE_")
}

// StringToFilterType maps a TF string back to the proto enum.
// Returns the UNSPECIFIED value for unknown inputs.
func StringToFilterType(s string) corev2.FilterType {
	if v, ok := corev2.FilterType_value["FILTER_TYPE_"+s]; ok {
		return corev2.FilterType(v)
	}
	return corev2.FilterType_FILTER_TYPE_UNSPECIFIED
}

// PatternTypeToString maps a proto enum value to its TF string form.
func PatternTypeToString(e corev2.PatternType) string {
	return strings.TrimPrefix(e.String(), "PATTERN_TYPE_")
}

// StringToPatternType maps a TF string back to the proto enum.
// Returns the UNSPECIFIED value for unknown inputs.
func StringToPatternType(s string) corev2.PatternType {
	if v, ok := corev2.PatternType_value["PATTERN_TYPE_"+s]; ok {
		return corev2.PatternType(v)
	}
	return corev2.PatternType_PATTERN_TYPE_UNSPECIFIED
}

// ScramMechanismToString maps a proto enum value to its TF string form.
func ScramMechanismToString(e corev2.ScramMechanism) string {
	return strings.TrimPrefix(e.String(), "SCRAM_MECHANISM_")
}

// StringToScramMechanism maps a TF string back to the proto enum.
// Returns the UNSPECIFIED value for unknown inputs.
func StringToScramMechanism(s string) corev2.ScramMechanism {
	if v, ok := corev2.ScramMechanism_value["SCRAM_MECHANISM_"+s]; ok {
		return corev2.ScramMechanism(v)
	}
	return corev2.ScramMechanism_SCRAM_MECHANISM_UNSPECIFIED
}

// ShadowLinkStateToString maps a proto enum value to its TF string form.
func ShadowLinkStateToString(e corev2.ShadowLinkState) string {
	return strings.TrimPrefix(e.String(), "SHADOW_LINK_STATE_")
}

// StringToShadowLinkState maps a TF string back to the proto enum.
// Returns the UNSPECIFIED value for unknown inputs.
func StringToShadowLinkState(s string) corev2.ShadowLinkState {
	if v, ok := corev2.ShadowLinkState_value["SHADOW_LINK_STATE_"+s]; ok {
		return corev2.ShadowLinkState(v)
	}
	return corev2.ShadowLinkState_SHADOW_LINK_STATE_UNSPECIFIED
}

// ShadowTopicStateToString maps a proto enum value to its TF string form.
func ShadowTopicStateToString(e corev2.ShadowTopicState) string {
	return strings.TrimPrefix(e.String(), "SHADOW_TOPIC_STATE_")
}

// StringToShadowTopicState maps a TF string back to the proto enum.
// Returns the UNSPECIFIED value for unknown inputs.
func StringToShadowTopicState(s string) corev2.ShadowTopicState {
	if v, ok := corev2.ShadowTopicState_value["SHADOW_TOPIC_STATE_"+s]; ok {
		return corev2.ShadowTopicState(v)
	}
	return corev2.ShadowTopicState_SHADOW_TOPIC_STATE_UNSPECIFIED
}

// TaskStateToString maps a proto enum value to its TF string form.
func TaskStateToString(e corev2.TaskState) string {
	return strings.TrimPrefix(e.String(), "TASK_STATE_")
}

// StringToTaskState maps a TF string back to the proto enum.
// Returns the UNSPECIFIED value for unknown inputs.
func StringToTaskState(s string) corev2.TaskState {
	if v, ok := corev2.TaskState_value["TASK_STATE_"+s]; ok {
		return corev2.TaskState(v)
	}
	return corev2.TaskState_TASK_STATE_UNSPECIFIED
}

// ACLOperationToString maps a proto enum value to its TF string form.
func ACLOperationToString(e dataplanev1.ACL_Operation) string {
	return strings.TrimPrefix(e.String(), "OPERATION_")
}

// StringToACLOperation maps a TF string back to the proto enum.
// Returns the UNSPECIFIED value for unknown inputs.
func StringToACLOperation(s string) dataplanev1.ACL_Operation {
	if v, ok := dataplanev1.ACL_Operation_value["OPERATION_"+s]; ok {
		return dataplanev1.ACL_Operation(v)
	}
	return dataplanev1.ACL_OPERATION_UNSPECIFIED
}

// ACLPermissionTypeToString maps a proto enum value to its TF string form.
func ACLPermissionTypeToString(e dataplanev1.ACL_PermissionType) string {
	return strings.TrimPrefix(e.String(), "PERMISSION_TYPE_")
}

// StringToACLPermissionType maps a TF string back to the proto enum.
// Returns the UNSPECIFIED value for unknown inputs.
func StringToACLPermissionType(s string) dataplanev1.ACL_PermissionType {
	if v, ok := dataplanev1.ACL_PermissionType_value["PERMISSION_TYPE_"+s]; ok {
		return dataplanev1.ACL_PermissionType(v)
	}
	return dataplanev1.ACL_PERMISSION_TYPE_UNSPECIFIED
}

// ACLResourcePatternTypeToString maps a proto enum value to its TF string form.
func ACLResourcePatternTypeToString(e dataplanev1.ACL_ResourcePatternType) string {
	return strings.TrimPrefix(e.String(), "RESOURCE_PATTERN_TYPE_")
}

// StringToACLResourcePatternType maps a TF string back to the proto enum.
// Returns the UNSPECIFIED value for unknown inputs.
func StringToACLResourcePatternType(s string) dataplanev1.ACL_ResourcePatternType {
	if v, ok := dataplanev1.ACL_ResourcePatternType_value["RESOURCE_PATTERN_TYPE_"+s]; ok {
		return dataplanev1.ACL_ResourcePatternType(v)
	}
	return dataplanev1.ACL_RESOURCE_PATTERN_TYPE_UNSPECIFIED
}

// ACLResourceTypeToString maps a proto enum value to its TF string form.
func ACLResourceTypeToString(e dataplanev1.ACL_ResourceType) string {
	return strings.TrimPrefix(e.String(), "RESOURCE_TYPE_")
}

// StringToACLResourceType maps a TF string back to the proto enum.
// Returns the UNSPECIFIED value for unknown inputs.
func StringToACLResourceType(s string) dataplanev1.ACL_ResourceType {
	if v, ok := dataplanev1.ACL_ResourceType_value["RESOURCE_TYPE_"+s]; ok {
		return dataplanev1.ACL_ResourceType(v)
	}
	return dataplanev1.ACL_RESOURCE_TYPE_UNSPECIFIED
}

// ComponentStatusToString maps a proto enum value to its TF string form.
func ComponentStatusToString(e dataplanev1.ComponentStatus) string {
	return strings.TrimPrefix(e.String(), "COMPONENT_STATUS_")
}

// StringToComponentStatus maps a TF string back to the proto enum.
// Returns the UNSPECIFIED value for unknown inputs.
func StringToComponentStatus(s string) dataplanev1.ComponentStatus {
	if v, ok := dataplanev1.ComponentStatus_value["COMPONENT_STATUS_"+s]; ok {
		return dataplanev1.ComponentStatus(v)
	}
	return dataplanev1.ComponentStatus_COMPONENT_STATUS_UNSPECIFIED
}

// ConfigAlterOperationToString maps a proto enum value to its TF string form.
func ConfigAlterOperationToString(e dataplanev1.ConfigAlterOperation) string {
	return strings.TrimPrefix(e.String(), "CONFIG_ALTER_OPERATION_")
}

// StringToConfigAlterOperation maps a TF string back to the proto enum.
// Returns the UNSPECIFIED value for unknown inputs.
func StringToConfigAlterOperation(s string) dataplanev1.ConfigAlterOperation {
	if v, ok := dataplanev1.ConfigAlterOperation_value["CONFIG_ALTER_OPERATION_"+s]; ok {
		return dataplanev1.ConfigAlterOperation(v)
	}
	return dataplanev1.ConfigAlterOperation_CONFIG_ALTER_OPERATION_UNSPECIFIED
}

// ConfigSourceToString maps a proto enum value to its TF string form.
func ConfigSourceToString(e dataplanev1.ConfigSource) string {
	return strings.TrimPrefix(e.String(), "CONFIG_SOURCE_")
}

// StringToConfigSource maps a TF string back to the proto enum.
// Returns the UNSPECIFIED value for unknown inputs.
func StringToConfigSource(s string) dataplanev1.ConfigSource {
	if v, ok := dataplanev1.ConfigSource_value["CONFIG_SOURCE_"+s]; ok {
		return dataplanev1.ConfigSource(v)
	}
	return dataplanev1.ConfigSource_CONFIG_SOURCE_UNSPECIFIED
}

// ConfigTypeToString maps a proto enum value to its TF string form.
func ConfigTypeToString(e dataplanev1.ConfigType) string {
	return strings.TrimPrefix(e.String(), "CONFIG_TYPE_")
}

// StringToConfigType maps a TF string back to the proto enum.
// Returns the UNSPECIFIED value for unknown inputs.
func StringToConfigType(s string) dataplanev1.ConfigType {
	if v, ok := dataplanev1.ConfigType_value["CONFIG_TYPE_"+s]; ok {
		return dataplanev1.ConfigType(v)
	}
	return dataplanev1.ConfigType_CONFIG_TYPE_UNSPECIFIED
}

// ConnectorErrorTypeToString maps a proto enum value to its TF string form.
func ConnectorErrorTypeToString(e dataplanev1.ConnectorError_Type) string {
	return strings.TrimPrefix(e.String(), "TYPE_")
}

// StringToConnectorErrorType maps a TF string back to the proto enum.
// Returns the UNSPECIFIED value for unknown inputs.
func StringToConnectorErrorType(s string) dataplanev1.ConnectorError_Type {
	if v, ok := dataplanev1.ConnectorError_Type_value["TYPE_"+s]; ok {
		return dataplanev1.ConnectorError_Type(v)
	}
	return dataplanev1.ConnectorError_TYPE_UNSPECIFIED
}

// ConnectorHolisticStateToString maps a proto enum value to its TF string form.
func ConnectorHolisticStateToString(e dataplanev1.ConnectorHolisticState) string {
	return strings.TrimPrefix(e.String(), "CONNECTOR_HOLISTIC_STATE_")
}

// StringToConnectorHolisticState maps a TF string back to the proto enum.
// Returns the UNSPECIFIED value for unknown inputs.
func StringToConnectorHolisticState(s string) dataplanev1.ConnectorHolisticState {
	if v, ok := dataplanev1.ConnectorHolisticState_value["CONNECTOR_HOLISTIC_STATE_"+s]; ok {
		return dataplanev1.ConnectorHolisticState(v)
	}
	return dataplanev1.ConnectorHolisticState_CONNECTOR_HOLISTIC_STATE_UNSPECIFIED
}

// ListResourcesResponseTypeToString maps a proto enum value to its TF string form.
func ListResourcesResponseTypeToString(e dataplanev1.ListResourcesResponse_Type) string {
	return strings.TrimPrefix(e.String(), "TYPE_")
}

// StringToListResourcesResponseType maps a TF string back to the proto enum.
// Returns the UNSPECIFIED value for unknown inputs.
func StringToListResourcesResponseType(s string) dataplanev1.ListResourcesResponse_Type {
	if v, ok := dataplanev1.ListResourcesResponse_Type_value["TYPE_"+s]; ok {
		return dataplanev1.ListResourcesResponse_Type(v)
	}
	return dataplanev1.ListResourcesResponse_TYPE_UNSPECIFIED
}

// MCPServerStateToString maps a proto enum value to its TF string form.
func MCPServerStateToString(e dataplanev1.MCPServer_State) string {
	return strings.TrimPrefix(e.String(), "STATE_")
}

// StringToMCPServerState maps a TF string back to the proto enum.
// Returns the UNSPECIFIED value for unknown inputs.
func StringToMCPServerState(s string) dataplanev1.MCPServer_State {
	if v, ok := dataplanev1.MCPServer_State_value["STATE_"+s]; ok {
		return dataplanev1.MCPServer_State(v)
	}
	return dataplanev1.MCPServer_STATE_UNSPECIFIED
}

// MCPServerToolComponentTypeToString maps a proto enum value to its TF string form.
func MCPServerToolComponentTypeToString(e dataplanev1.MCPServer_Tool_ComponentType) string {
	return strings.TrimPrefix(e.String(), "COMPONENT_TYPE_")
}

// StringToMCPServerToolComponentType maps a TF string back to the proto enum.
// Returns the UNSPECIFIED value for unknown inputs.
func StringToMCPServerToolComponentType(s string) dataplanev1.MCPServer_Tool_ComponentType {
	if v, ok := dataplanev1.MCPServer_Tool_ComponentType_value["COMPONENT_TYPE_"+s]; ok {
		return dataplanev1.MCPServer_Tool_ComponentType(v)
	}
	return dataplanev1.MCPServer_Tool_COMPONENT_TYPE_UNSPECIFIED
}

// MountTaskStateToString maps a proto enum value to its TF string form.
func MountTaskStateToString(e dataplanev1.MountTask_State) string {
	return strings.TrimPrefix(e.String(), "STATE_")
}

// StringToMountTaskState maps a TF string back to the proto enum.
// Returns the UNSPECIFIED value for unknown inputs.
func StringToMountTaskState(s string) dataplanev1.MountTask_State {
	if v, ok := dataplanev1.MountTask_State_value["STATE_"+s]; ok {
		return dataplanev1.MountTask_State(v)
	}
	return dataplanev1.MountTask_STATE_UNSPECIFIED
}

// MountTaskTypeToString maps a proto enum value to its TF string form.
func MountTaskTypeToString(e dataplanev1.MountTask_Type) string {
	return strings.TrimPrefix(e.String(), "TYPE_")
}

// StringToMountTaskType maps a TF string back to the proto enum.
// Returns the UNSPECIFIED value for unknown inputs.
func StringToMountTaskType(s string) dataplanev1.MountTask_Type {
	if v, ok := dataplanev1.MountTask_Type_value["TYPE_"+s]; ok {
		return dataplanev1.MountTask_Type(v)
	}
	return dataplanev1.MountTask_TYPE_UNSPECIFIED
}

// PartitionTransformStatusPartitionStatusToString maps a proto enum value to its TF string form.
func PartitionTransformStatusPartitionStatusToString(e dataplanev1.PartitionTransformStatus_PartitionStatus) string {
	return strings.TrimPrefix(e.String(), "PARTITION_STATUS_")
}

// StringToPartitionTransformStatusPartitionStatus maps a TF string back to the proto enum.
// Returns the UNSPECIFIED value for unknown inputs.
func StringToPartitionTransformStatusPartitionStatus(s string) dataplanev1.PartitionTransformStatus_PartitionStatus {
	if v, ok := dataplanev1.PartitionTransformStatus_PartitionStatus_value["PARTITION_STATUS_"+s]; ok {
		return dataplanev1.PartitionTransformStatus_PartitionStatus(v)
	}
	return dataplanev1.PartitionTransformStatus_PARTITION_STATUS_UNSPECIFIED
}

// PipelineStateToString maps a proto enum value to its TF string form.
func PipelineStateToString(e dataplanev1.Pipeline_State) string {
	return strings.TrimPrefix(e.String(), "STATE_")
}

// StringToPipelineState maps a TF string back to the proto enum.
// Returns the UNSPECIFIED value for unknown inputs.
func StringToPipelineState(s string) dataplanev1.Pipeline_State {
	if v, ok := dataplanev1.Pipeline_State_value["STATE_"+s]; ok {
		return dataplanev1.Pipeline_State(v)
	}
	return dataplanev1.Pipeline_STATE_UNSPECIFIED
}

// QuotaEntityTypeToString maps a proto enum value to its TF string form.
func QuotaEntityTypeToString(e dataplanev1.Quota_EntityType) string {
	return strings.TrimPrefix(e.String(), "ENTITY_TYPE_")
}

// StringToQuotaEntityType maps a TF string back to the proto enum.
// Returns the UNSPECIFIED value for unknown inputs.
func StringToQuotaEntityType(s string) dataplanev1.Quota_EntityType {
	if v, ok := dataplanev1.Quota_EntityType_value["ENTITY_TYPE_"+s]; ok {
		return dataplanev1.Quota_EntityType(v)
	}
	return dataplanev1.Quota_ENTITY_TYPE_UNSPECIFIED
}

// QuotaValueTypeToString maps a proto enum value to its TF string form.
func QuotaValueTypeToString(e dataplanev1.Quota_ValueType) string {
	return strings.TrimPrefix(e.String(), "VALUE_TYPE_")
}

// StringToQuotaValueType maps a TF string back to the proto enum.
// Returns the UNSPECIFIED value for unknown inputs.
func StringToQuotaValueType(s string) dataplanev1.Quota_ValueType {
	if v, ok := dataplanev1.Quota_ValueType_value["VALUE_TYPE_"+s]; ok {
		return dataplanev1.Quota_ValueType(v)
	}
	return dataplanev1.Quota_VALUE_TYPE_UNSPECIFIED
}

// ReasonToString maps a proto enum value to its TF string form.
func ReasonToString(e dataplanev1.Reason) string {
	return strings.TrimPrefix(e.String(), "REASON_")
}

// StringToReason maps a TF string back to the proto enum.
// Returns the UNSPECIFIED value for unknown inputs.
func StringToReason(s string) dataplanev1.Reason {
	if v, ok := dataplanev1.Reason_value["REASON_"+s]; ok {
		return dataplanev1.Reason(v)
	}
	return dataplanev1.Reason_REASON_UNSPECIFIED
}

// ScopeToString maps a proto enum value to its TF string form.
func ScopeToString(e dataplanev1.Scope) string {
	return strings.TrimPrefix(e.String(), "SCOPE_")
}

// StringToScope maps a TF string back to the proto enum.
// Returns the UNSPECIFIED value for unknown inputs.
func StringToScope(s string) dataplanev1.Scope {
	if v, ok := dataplanev1.Scope_value["SCOPE_"+s]; ok {
		return dataplanev1.Scope(v)
	}
	return dataplanev1.Scope_SCOPE_UNSPECIFIED
}

// UpdateMountTaskRequestActionToString maps a proto enum value to its TF string form.
func UpdateMountTaskRequestActionToString(e dataplanev1.UpdateMountTaskRequest_Action) string {
	return strings.TrimPrefix(e.String(), "ACTION_")
}

// StringToUpdateMountTaskRequestAction maps a TF string back to the proto enum.
// Returns the UNSPECIFIED value for unknown inputs.
func StringToUpdateMountTaskRequestAction(s string) dataplanev1.UpdateMountTaskRequest_Action {
	if v, ok := dataplanev1.UpdateMountTaskRequest_Action_value["ACTION_"+s]; ok {
		return dataplanev1.UpdateMountTaskRequest_Action(v)
	}
	return dataplanev1.UpdateMountTaskRequest_ACTION_UNSPECIFIED
}
