// Code generated by schemagen. DO NOT EDIT.

// Copyright 2023 Redpanda Data, Inc.
//
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

// Package serviceaccount contains the model for the serviceaccount resource.
package serviceaccount

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

// ResourceModel represents the Terraform schema for the serviceaccount resource.
type ResourceModel struct {
	Auth0ClientCredentials types.Object   `tfsdk:"auth0_client_credentials"`
	Description            types.String   `tfsdk:"description"`
	ID                     types.String   `tfsdk:"id"`
	Name                   types.String   `tfsdk:"name"`
	Timeouts               timeouts.Value `tfsdk:"timeouts"`
}

// --- Nested typed structs (one per nested message in the proto tree) ---

// Auth0ClientCredentialsModel mirrors the nested "auth0_client_credentials" attribute. Use the As/To
// converters on the parent struct to move between types.Object and this
// typed form.
type Auth0ClientCredentialsModel struct {
	ClientID     types.String `tfsdk:"client_id"`
	ClientSecret types.String `tfsdk:"client_secret"`
}

// --- AttrType tables for nested types (consumed by types.ObjectValueFrom / ObjectNull) ---

// Auth0ClientCredentialsAttrTypes returns the attr.Type map for the "auth0_client_credentials" nested
// attribute.
func Auth0ClientCredentialsAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"client_id":     types.StringType,
		"client_secret": types.StringType,
	}
}

// --- Root-level converters (types.Object ⇄ typed struct ergonomics) ---

// AsAuth0ClientCredentials converts the root auth0_client_credentials attribute from
// types.Object into its typed form. Returns (nil, nil) when the object is
// null or unknown. Use this when you want typed field access without
// manually unpacking .Attributes().
func (m *ResourceModel) AsAuth0ClientCredentials(ctx context.Context) (*Auth0ClientCredentialsModel, diag.Diagnostics) {
	if m == nil || m.Auth0ClientCredentials.IsNull() || m.Auth0ClientCredentials.IsUnknown() {
		return nil, nil
	}
	var out Auth0ClientCredentialsModel
	d := m.Auth0ClientCredentials.As(ctx, &out, basetypes.ObjectAsOptions{})
	return &out, d
}

// Auth0ClientCredentialsToObject encodes a typed struct back into the
// types.Object shape expected by the framework. A nil receiver returns
// types.ObjectNull with the correct attribute types.
func Auth0ClientCredentialsToObject(ctx context.Context, v *Auth0ClientCredentialsModel) (types.Object, diag.Diagnostics) {
	if v == nil {
		return types.ObjectNull(Auth0ClientCredentialsAttrTypes()), nil
	}
	return types.ObjectValueFrom(ctx, Auth0ClientCredentialsAttrTypes(), v)
}

// GenerateMinimalResourceModel returns a *ResourceModel populated only with
// the supplied id + timeouts; every other field is at its typed null (or its
// declared minimal_default). Used by resources that need to persist a
// partial state when Create / Read returns mid-flight.
func GenerateMinimalResourceModel(id types.String, timeout timeouts.Value) *ResourceModel {
	return &ResourceModel{
		Auth0ClientCredentials: types.ObjectNull(Auth0ClientCredentialsAttrTypes()),
		Description:            types.StringNull(),
		ID:                     id,
		Name:                   types.StringNull(),
		Timeouts:               timeout,
	}
}
