// Code generated by schemagen. DO NOT EDIT.

// Copyright 2023 Redpanda Data, Inc.
//
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

// Package serverlesscluster contains the model for the serverlesscluster datasource.
package serverlesscluster

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

// DataModel represents the Terraform schema for the serverlesscluster datasource.
type DataModel struct {
	ClusterAPIURL     types.String `tfsdk:"cluster_api_url"`
	ConsolePrivateURL types.String `tfsdk:"console_private_url"`
	ConsoleURL        types.String `tfsdk:"console_url"`
	DataplaneAPI      types.Object `tfsdk:"dataplane_api"`
	ID                types.String `tfsdk:"id"`
	KafkaAPI          types.Object `tfsdk:"kafka_api"`
	Name              types.String `tfsdk:"name"`
	NetworkingConfig  types.Object `tfsdk:"networking_config"`
	PlannedDeletion   types.Object `tfsdk:"planned_deletion"`
	PrivateLinkID     types.String `tfsdk:"private_link_id"`
	Prometheus        types.Object `tfsdk:"prometheus"`
	ResourceGroupID   types.String `tfsdk:"resource_group_id"`
	SchemaRegistry    types.Object `tfsdk:"schema_registry"`
	ServerlessRegion  types.String `tfsdk:"serverless_region"`
	State             types.String `tfsdk:"state"`
	Tags              types.Map    `tfsdk:"tags"`
}

// --- Nested typed structs (one per nested message in the proto tree) ---

// DataDataplaneAPIModel mirrors the nested "dataplane_api" attribute. Use the As/To
// converters on the parent struct to move between types.Object and this
// typed form.
type DataDataplaneAPIModel struct {
	PrivateURL types.String `tfsdk:"private_url"`
	URL        types.String `tfsdk:"url"`
}

// DataKafkaAPIModel mirrors the nested "kafka_api" attribute. Use the As/To
// converters on the parent struct to move between types.Object and this
// typed form.
type DataKafkaAPIModel struct {
	PrivateSeedBrokers types.List `tfsdk:"private_seed_brokers"`
	SeedBrokers        types.List `tfsdk:"seed_brokers"`
}

// DataNetworkingConfigModel mirrors the nested "networking_config" attribute. Use the As/To
// converters on the parent struct to move between types.Object and this
// typed form.
type DataNetworkingConfigModel struct {
	Private types.String `tfsdk:"private"`
	Public  types.String `tfsdk:"public"`
}

// DataPlannedDeletionModel mirrors the nested "planned_deletion" attribute. Use the As/To
// converters on the parent struct to move between types.Object and this
// typed form.
type DataPlannedDeletionModel struct {
	DeleteAfter types.String `tfsdk:"delete_after"`
	Reason      types.String `tfsdk:"reason"`
}

// DataPrometheusModel mirrors the nested "prometheus" attribute. Use the As/To
// converters on the parent struct to move between types.Object and this
// typed form.
type DataPrometheusModel struct {
	PrivateURL types.String `tfsdk:"private_url"`
	URL        types.String `tfsdk:"url"`
}

// DataSchemaRegistryModel mirrors the nested "schema_registry" attribute. Use the As/To
// converters on the parent struct to move between types.Object and this
// typed form.
type DataSchemaRegistryModel struct {
	PrivateURL types.String `tfsdk:"private_url"`
	URL        types.String `tfsdk:"url"`
}

// --- AttrType tables for nested types (consumed by types.ObjectValueFrom / ObjectNull) ---

// DataDataplaneAPIAttrTypes returns the attr.Type map for the "dataplane_api" nested
// attribute.
func DataDataplaneAPIAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"private_url": types.StringType,
		"url":         types.StringType,
	}
}

// DataKafkaAPIAttrTypes returns the attr.Type map for the "kafka_api" nested
// attribute.
func DataKafkaAPIAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"private_seed_brokers": types.ListType{ElemType: types.StringType},
		"seed_brokers":         types.ListType{ElemType: types.StringType},
	}
}

// DataNetworkingConfigAttrTypes returns the attr.Type map for the "networking_config" nested
// attribute.
func DataNetworkingConfigAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"private": types.StringType,
		"public":  types.StringType,
	}
}

// DataPlannedDeletionAttrTypes returns the attr.Type map for the "planned_deletion" nested
// attribute.
func DataPlannedDeletionAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"delete_after": types.StringType,
		"reason":       types.StringType,
	}
}

// DataPrometheusAttrTypes returns the attr.Type map for the "prometheus" nested
// attribute.
func DataPrometheusAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"private_url": types.StringType,
		"url":         types.StringType,
	}
}

// DataSchemaRegistryAttrTypes returns the attr.Type map for the "schema_registry" nested
// attribute.
func DataSchemaRegistryAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"private_url": types.StringType,
		"url":         types.StringType,
	}
}

// --- Root-level converters (types.Object ⇄ typed struct ergonomics) ---

// AsDataplaneAPI converts the root dataplane_api attribute from
// types.Object into its typed form. Returns (nil, nil) when the object is
// null or unknown. Use this when you want typed field access without
// manually unpacking .Attributes().
func (m *DataModel) AsDataplaneAPI(ctx context.Context) (*DataDataplaneAPIModel, diag.Diagnostics) {
	if m == nil || m.DataplaneAPI.IsNull() || m.DataplaneAPI.IsUnknown() {
		return nil, nil
	}
	var out DataDataplaneAPIModel
	d := m.DataplaneAPI.As(ctx, &out, basetypes.ObjectAsOptions{})
	return &out, d
}

// DataDataplaneAPIToObject encodes a typed struct back into the
// types.Object shape expected by the framework. A nil receiver returns
// types.ObjectNull with the correct attribute types.
func DataDataplaneAPIToObject(ctx context.Context, v *DataDataplaneAPIModel) (types.Object, diag.Diagnostics) {
	if v == nil {
		return types.ObjectNull(DataDataplaneAPIAttrTypes()), nil
	}
	return types.ObjectValueFrom(ctx, DataDataplaneAPIAttrTypes(), v)
}

// AsKafkaAPI converts the root kafka_api attribute from
// types.Object into its typed form. Returns (nil, nil) when the object is
// null or unknown. Use this when you want typed field access without
// manually unpacking .Attributes().
func (m *DataModel) AsKafkaAPI(ctx context.Context) (*DataKafkaAPIModel, diag.Diagnostics) {
	if m == nil || m.KafkaAPI.IsNull() || m.KafkaAPI.IsUnknown() {
		return nil, nil
	}
	var out DataKafkaAPIModel
	d := m.KafkaAPI.As(ctx, &out, basetypes.ObjectAsOptions{})
	return &out, d
}

// DataKafkaAPIToObject encodes a typed struct back into the
// types.Object shape expected by the framework. A nil receiver returns
// types.ObjectNull with the correct attribute types.
func DataKafkaAPIToObject(ctx context.Context, v *DataKafkaAPIModel) (types.Object, diag.Diagnostics) {
	if v == nil {
		return types.ObjectNull(DataKafkaAPIAttrTypes()), nil
	}
	return types.ObjectValueFrom(ctx, DataKafkaAPIAttrTypes(), v)
}

// AsNetworkingConfig converts the root networking_config attribute from
// types.Object into its typed form. Returns (nil, nil) when the object is
// null or unknown. Use this when you want typed field access without
// manually unpacking .Attributes().
func (m *DataModel) AsNetworkingConfig(ctx context.Context) (*DataNetworkingConfigModel, diag.Diagnostics) {
	if m == nil || m.NetworkingConfig.IsNull() || m.NetworkingConfig.IsUnknown() {
		return nil, nil
	}
	var out DataNetworkingConfigModel
	d := m.NetworkingConfig.As(ctx, &out, basetypes.ObjectAsOptions{})
	return &out, d
}

// DataNetworkingConfigToObject encodes a typed struct back into the
// types.Object shape expected by the framework. A nil receiver returns
// types.ObjectNull with the correct attribute types.
func DataNetworkingConfigToObject(ctx context.Context, v *DataNetworkingConfigModel) (types.Object, diag.Diagnostics) {
	if v == nil {
		return types.ObjectNull(DataNetworkingConfigAttrTypes()), nil
	}
	return types.ObjectValueFrom(ctx, DataNetworkingConfigAttrTypes(), v)
}

// AsPlannedDeletion converts the root planned_deletion attribute from
// types.Object into its typed form. Returns (nil, nil) when the object is
// null or unknown. Use this when you want typed field access without
// manually unpacking .Attributes().
func (m *DataModel) AsPlannedDeletion(ctx context.Context) (*DataPlannedDeletionModel, diag.Diagnostics) {
	if m == nil || m.PlannedDeletion.IsNull() || m.PlannedDeletion.IsUnknown() {
		return nil, nil
	}
	var out DataPlannedDeletionModel
	d := m.PlannedDeletion.As(ctx, &out, basetypes.ObjectAsOptions{})
	return &out, d
}

// DataPlannedDeletionToObject encodes a typed struct back into the
// types.Object shape expected by the framework. A nil receiver returns
// types.ObjectNull with the correct attribute types.
func DataPlannedDeletionToObject(ctx context.Context, v *DataPlannedDeletionModel) (types.Object, diag.Diagnostics) {
	if v == nil {
		return types.ObjectNull(DataPlannedDeletionAttrTypes()), nil
	}
	return types.ObjectValueFrom(ctx, DataPlannedDeletionAttrTypes(), v)
}

// AsPrometheus converts the root prometheus attribute from
// types.Object into its typed form. Returns (nil, nil) when the object is
// null or unknown. Use this when you want typed field access without
// manually unpacking .Attributes().
func (m *DataModel) AsPrometheus(ctx context.Context) (*DataPrometheusModel, diag.Diagnostics) {
	if m == nil || m.Prometheus.IsNull() || m.Prometheus.IsUnknown() {
		return nil, nil
	}
	var out DataPrometheusModel
	d := m.Prometheus.As(ctx, &out, basetypes.ObjectAsOptions{})
	return &out, d
}

// DataPrometheusToObject encodes a typed struct back into the
// types.Object shape expected by the framework. A nil receiver returns
// types.ObjectNull with the correct attribute types.
func DataPrometheusToObject(ctx context.Context, v *DataPrometheusModel) (types.Object, diag.Diagnostics) {
	if v == nil {
		return types.ObjectNull(DataPrometheusAttrTypes()), nil
	}
	return types.ObjectValueFrom(ctx, DataPrometheusAttrTypes(), v)
}

// AsSchemaRegistry converts the root schema_registry attribute from
// types.Object into its typed form. Returns (nil, nil) when the object is
// null or unknown. Use this when you want typed field access without
// manually unpacking .Attributes().
func (m *DataModel) AsSchemaRegistry(ctx context.Context) (*DataSchemaRegistryModel, diag.Diagnostics) {
	if m == nil || m.SchemaRegistry.IsNull() || m.SchemaRegistry.IsUnknown() {
		return nil, nil
	}
	var out DataSchemaRegistryModel
	d := m.SchemaRegistry.As(ctx, &out, basetypes.ObjectAsOptions{})
	return &out, d
}

// DataSchemaRegistryToObject encodes a typed struct back into the
// types.Object shape expected by the framework. A nil receiver returns
// types.ObjectNull with the correct attribute types.
func DataSchemaRegistryToObject(ctx context.Context, v *DataSchemaRegistryModel) (types.Object, diag.Diagnostics) {
	if v == nil {
		return types.ObjectNull(DataSchemaRegistryAttrTypes()), nil
	}
	return types.ObjectValueFrom(ctx, DataSchemaRegistryAttrTypes(), v)
}
