// Code generated by schemagen. DO NOT EDIT.

// Copyright 2023 Redpanda Data, Inc.
//
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

// Package network contains the model for the network datasource.
package network

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

// DataModel represents the Terraform schema for the network datasource.
type DataModel struct {
	CidrBlock                types.String `tfsdk:"cidr_block"`
	CloudProvider            types.String `tfsdk:"cloud_provider"`
	ClusterType              types.String `tfsdk:"cluster_type"`
	CustomerManagedResources types.Object `tfsdk:"customer_managed_resources"`
	ID                       types.String `tfsdk:"id"`
	Name                     types.String `tfsdk:"name"`
	Region                   types.String `tfsdk:"region"`
	ResourceGroupID          types.String `tfsdk:"resource_group_id"`
	State                    types.String `tfsdk:"state"`
	Zones                    types.List   `tfsdk:"zones"`
}

// --- Nested typed structs (one per nested message in the proto tree) ---

// DataCustomerManagedResourcesModel mirrors the nested "customer_managed_resources" attribute. Use the As/To
// converters on the parent struct to move between types.Object and this
// typed form.
type DataCustomerManagedResourcesModel struct {
	AWS types.Object `tfsdk:"aws"`
	GCP types.Object `tfsdk:"gcp"`
}

// DataCustomerManagedResourcesAWSModel mirrors the nested "customer_managed_resources.aws" attribute. Use the As/To
// converters on the parent struct to move between types.Object and this
// typed form.
type DataCustomerManagedResourcesAWSModel struct {
	DynamodbTable    types.Object `tfsdk:"dynamodb_table"`
	ManagementBucket types.Object `tfsdk:"management_bucket"`
	PrivateSubnets   types.Object `tfsdk:"private_subnets"`
	VPC              types.Object `tfsdk:"vpc"`
}

// DataCustomerManagedResourcesAWSDynamodbTableModel mirrors the nested "customer_managed_resources.aws.dynamodb_table" attribute. Use the As/To
// converters on the parent struct to move between types.Object and this
// typed form.
type DataCustomerManagedResourcesAWSDynamodbTableModel struct {
	ARN types.String `tfsdk:"arn"`
}

// DataCustomerManagedResourcesAWSManagementBucketModel mirrors the nested "customer_managed_resources.aws.management_bucket" attribute. Use the As/To
// converters on the parent struct to move between types.Object and this
// typed form.
type DataCustomerManagedResourcesAWSManagementBucketModel struct {
	ARN types.String `tfsdk:"arn"`
}

// DataCustomerManagedResourcesAWSPrivateSubnetsModel mirrors the nested "customer_managed_resources.aws.private_subnets" attribute. Use the As/To
// converters on the parent struct to move between types.Object and this
// typed form.
type DataCustomerManagedResourcesAWSPrivateSubnetsModel struct {
	Arns types.List `tfsdk:"arns"`
}

// DataCustomerManagedResourcesAWSVPCModel mirrors the nested "customer_managed_resources.aws.vpc" attribute. Use the As/To
// converters on the parent struct to move between types.Object and this
// typed form.
type DataCustomerManagedResourcesAWSVPCModel struct {
	ARN types.String `tfsdk:"arn"`
}

// DataCustomerManagedResourcesGCPModel mirrors the nested "customer_managed_resources.gcp" attribute. Use the As/To
// converters on the parent struct to move between types.Object and this
// typed form.
type DataCustomerManagedResourcesGCPModel struct {
	ManagementBucket types.Object `tfsdk:"management_bucket"`
	NetworkName      types.String `tfsdk:"network_name"`
	NetworkProjectID types.String `tfsdk:"network_project_id"`
}

// DataCustomerManagedResourcesGCPManagementBucketModel mirrors the nested "customer_managed_resources.gcp.management_bucket" attribute. Use the As/To
// converters on the parent struct to move between types.Object and this
// typed form.
type DataCustomerManagedResourcesGCPManagementBucketModel struct {
	Name types.String `tfsdk:"name"`
}

// --- AttrType tables for nested types (consumed by types.ObjectValueFrom / ObjectNull) ---

// DataCustomerManagedResourcesAttrTypes returns the attr.Type map for the "customer_managed_resources" nested
// attribute.
func DataCustomerManagedResourcesAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"aws": types.ObjectType{AttrTypes: DataCustomerManagedResourcesAWSAttrTypes()},
		"gcp": types.ObjectType{AttrTypes: DataCustomerManagedResourcesGCPAttrTypes()},
	}
}

// DataCustomerManagedResourcesAWSAttrTypes returns the attr.Type map for the "customer_managed_resources.aws" nested
// attribute.
func DataCustomerManagedResourcesAWSAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"dynamodb_table":    types.ObjectType{AttrTypes: DataCustomerManagedResourcesAWSDynamodbTableAttrTypes()},
		"management_bucket": types.ObjectType{AttrTypes: DataCustomerManagedResourcesAWSManagementBucketAttrTypes()},
		"private_subnets":   types.ObjectType{AttrTypes: DataCustomerManagedResourcesAWSPrivateSubnetsAttrTypes()},
		"vpc":               types.ObjectType{AttrTypes: DataCustomerManagedResourcesAWSVPCAttrTypes()},
	}
}

// DataCustomerManagedResourcesAWSDynamodbTableAttrTypes returns the attr.Type map for the "customer_managed_resources.aws.dynamodb_table" nested
// attribute.
func DataCustomerManagedResourcesAWSDynamodbTableAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"arn": types.StringType,
	}
}

// DataCustomerManagedResourcesAWSManagementBucketAttrTypes returns the attr.Type map for the "customer_managed_resources.aws.management_bucket" nested
// attribute.
func DataCustomerManagedResourcesAWSManagementBucketAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"arn": types.StringType,
	}
}

// DataCustomerManagedResourcesAWSPrivateSubnetsAttrTypes returns the attr.Type map for the "customer_managed_resources.aws.private_subnets" nested
// attribute.
func DataCustomerManagedResourcesAWSPrivateSubnetsAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"arns": types.ListType{ElemType: types.StringType},
	}
}

// DataCustomerManagedResourcesAWSVPCAttrTypes returns the attr.Type map for the "customer_managed_resources.aws.vpc" nested
// attribute.
func DataCustomerManagedResourcesAWSVPCAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"arn": types.StringType,
	}
}

// DataCustomerManagedResourcesGCPAttrTypes returns the attr.Type map for the "customer_managed_resources.gcp" nested
// attribute.
func DataCustomerManagedResourcesGCPAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"management_bucket":  types.ObjectType{AttrTypes: DataCustomerManagedResourcesGCPManagementBucketAttrTypes()},
		"network_name":       types.StringType,
		"network_project_id": types.StringType,
	}
}

// DataCustomerManagedResourcesGCPManagementBucketAttrTypes returns the attr.Type map for the "customer_managed_resources.gcp.management_bucket" nested
// attribute.
func DataCustomerManagedResourcesGCPManagementBucketAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"name": types.StringType,
	}
}

// --- Root-level converters (types.Object ⇄ typed struct ergonomics) ---

// AsCustomerManagedResources converts the root customer_managed_resources attribute from
// types.Object into its typed form. Returns (nil, nil) when the object is
// null or unknown. Use this when you want typed field access without
// manually unpacking .Attributes().
func (m *DataModel) AsCustomerManagedResources(ctx context.Context) (*DataCustomerManagedResourcesModel, diag.Diagnostics) {
	if m == nil || m.CustomerManagedResources.IsNull() || m.CustomerManagedResources.IsUnknown() {
		return nil, nil
	}
	var out DataCustomerManagedResourcesModel
	d := m.CustomerManagedResources.As(ctx, &out, basetypes.ObjectAsOptions{})
	return &out, d
}

// DataCustomerManagedResourcesToObject encodes a typed struct back into the
// types.Object shape expected by the framework. A nil receiver returns
// types.ObjectNull with the correct attribute types.
func DataCustomerManagedResourcesToObject(ctx context.Context, v *DataCustomerManagedResourcesModel) (types.Object, diag.Diagnostics) {
	if v == nil {
		return types.ObjectNull(DataCustomerManagedResourcesAttrTypes()), nil
	}
	return types.ObjectValueFrom(ctx, DataCustomerManagedResourcesAttrTypes(), v)
}

// --- Sub-level converters (free-standing Decode*/ToObject for types nested beyond root level) ---

// DecodeDataCustomerManagedResourcesAWS decodes the sub-field from its parent typed struct.
// Returns (nil, nil) when the field is null or unknown.
func DecodeDataCustomerManagedResourcesAWS(ctx context.Context, v *DataCustomerManagedResourcesModel) (*DataCustomerManagedResourcesAWSModel, diag.Diagnostics) {
	if v == nil || v.AWS.IsNull() || v.AWS.IsUnknown() {
		return nil, nil
	}
	var out DataCustomerManagedResourcesAWSModel
	d := v.AWS.As(ctx, &out, basetypes.ObjectAsOptions{})
	return &out, d
}

// DataCustomerManagedResourcesAWSToObject encodes a typed struct back into types.Object.
// A nil receiver returns types.ObjectNull with the correct attribute types.
func DataCustomerManagedResourcesAWSToObject(ctx context.Context, v *DataCustomerManagedResourcesAWSModel) (types.Object, diag.Diagnostics) {
	if v == nil {
		return types.ObjectNull(DataCustomerManagedResourcesAWSAttrTypes()), nil
	}
	return types.ObjectValueFrom(ctx, DataCustomerManagedResourcesAWSAttrTypes(), v)
}

// DecodeDataCustomerManagedResourcesAWSDynamodbTable decodes the sub-field from its parent typed struct.
// Returns (nil, nil) when the field is null or unknown.
func DecodeDataCustomerManagedResourcesAWSDynamodbTable(ctx context.Context, v *DataCustomerManagedResourcesAWSModel) (*DataCustomerManagedResourcesAWSDynamodbTableModel, diag.Diagnostics) {
	if v == nil || v.DynamodbTable.IsNull() || v.DynamodbTable.IsUnknown() {
		return nil, nil
	}
	var out DataCustomerManagedResourcesAWSDynamodbTableModel
	d := v.DynamodbTable.As(ctx, &out, basetypes.ObjectAsOptions{})
	return &out, d
}

// DataCustomerManagedResourcesAWSDynamodbTableToObject encodes a typed struct back into types.Object.
// A nil receiver returns types.ObjectNull with the correct attribute types.
func DataCustomerManagedResourcesAWSDynamodbTableToObject(ctx context.Context, v *DataCustomerManagedResourcesAWSDynamodbTableModel) (types.Object, diag.Diagnostics) {
	if v == nil {
		return types.ObjectNull(DataCustomerManagedResourcesAWSDynamodbTableAttrTypes()), nil
	}
	return types.ObjectValueFrom(ctx, DataCustomerManagedResourcesAWSDynamodbTableAttrTypes(), v)
}

// DecodeDataCustomerManagedResourcesAWSManagementBucket decodes the sub-field from its parent typed struct.
// Returns (nil, nil) when the field is null or unknown.
func DecodeDataCustomerManagedResourcesAWSManagementBucket(ctx context.Context, v *DataCustomerManagedResourcesAWSModel) (*DataCustomerManagedResourcesAWSManagementBucketModel, diag.Diagnostics) {
	if v == nil || v.ManagementBucket.IsNull() || v.ManagementBucket.IsUnknown() {
		return nil, nil
	}
	var out DataCustomerManagedResourcesAWSManagementBucketModel
	d := v.ManagementBucket.As(ctx, &out, basetypes.ObjectAsOptions{})
	return &out, d
}

// DataCustomerManagedResourcesAWSManagementBucketToObject encodes a typed struct back into types.Object.
// A nil receiver returns types.ObjectNull with the correct attribute types.
func DataCustomerManagedResourcesAWSManagementBucketToObject(ctx context.Context, v *DataCustomerManagedResourcesAWSManagementBucketModel) (types.Object, diag.Diagnostics) {
	if v == nil {
		return types.ObjectNull(DataCustomerManagedResourcesAWSManagementBucketAttrTypes()), nil
	}
	return types.ObjectValueFrom(ctx, DataCustomerManagedResourcesAWSManagementBucketAttrTypes(), v)
}

// DecodeDataCustomerManagedResourcesAWSPrivateSubnets decodes the sub-field from its parent typed struct.
// Returns (nil, nil) when the field is null or unknown.
func DecodeDataCustomerManagedResourcesAWSPrivateSubnets(ctx context.Context, v *DataCustomerManagedResourcesAWSModel) (*DataCustomerManagedResourcesAWSPrivateSubnetsModel, diag.Diagnostics) {
	if v == nil || v.PrivateSubnets.IsNull() || v.PrivateSubnets.IsUnknown() {
		return nil, nil
	}
	var out DataCustomerManagedResourcesAWSPrivateSubnetsModel
	d := v.PrivateSubnets.As(ctx, &out, basetypes.ObjectAsOptions{})
	return &out, d
}

// DataCustomerManagedResourcesAWSPrivateSubnetsToObject encodes a typed struct back into types.Object.
// A nil receiver returns types.ObjectNull with the correct attribute types.
func DataCustomerManagedResourcesAWSPrivateSubnetsToObject(ctx context.Context, v *DataCustomerManagedResourcesAWSPrivateSubnetsModel) (types.Object, diag.Diagnostics) {
	if v == nil {
		return types.ObjectNull(DataCustomerManagedResourcesAWSPrivateSubnetsAttrTypes()), nil
	}
	return types.ObjectValueFrom(ctx, DataCustomerManagedResourcesAWSPrivateSubnetsAttrTypes(), v)
}

// DecodeDataCustomerManagedResourcesAWSVPC decodes the sub-field from its parent typed struct.
// Returns (nil, nil) when the field is null or unknown.
func DecodeDataCustomerManagedResourcesAWSVPC(ctx context.Context, v *DataCustomerManagedResourcesAWSModel) (*DataCustomerManagedResourcesAWSVPCModel, diag.Diagnostics) {
	if v == nil || v.VPC.IsNull() || v.VPC.IsUnknown() {
		return nil, nil
	}
	var out DataCustomerManagedResourcesAWSVPCModel
	d := v.VPC.As(ctx, &out, basetypes.ObjectAsOptions{})
	return &out, d
}

// DataCustomerManagedResourcesAWSVPCToObject encodes a typed struct back into types.Object.
// A nil receiver returns types.ObjectNull with the correct attribute types.
func DataCustomerManagedResourcesAWSVPCToObject(ctx context.Context, v *DataCustomerManagedResourcesAWSVPCModel) (types.Object, diag.Diagnostics) {
	if v == nil {
		return types.ObjectNull(DataCustomerManagedResourcesAWSVPCAttrTypes()), nil
	}
	return types.ObjectValueFrom(ctx, DataCustomerManagedResourcesAWSVPCAttrTypes(), v)
}

// DecodeDataCustomerManagedResourcesGCP decodes the sub-field from its parent typed struct.
// Returns (nil, nil) when the field is null or unknown.
func DecodeDataCustomerManagedResourcesGCP(ctx context.Context, v *DataCustomerManagedResourcesModel) (*DataCustomerManagedResourcesGCPModel, diag.Diagnostics) {
	if v == nil || v.GCP.IsNull() || v.GCP.IsUnknown() {
		return nil, nil
	}
	var out DataCustomerManagedResourcesGCPModel
	d := v.GCP.As(ctx, &out, basetypes.ObjectAsOptions{})
	return &out, d
}

// DataCustomerManagedResourcesGCPToObject encodes a typed struct back into types.Object.
// A nil receiver returns types.ObjectNull with the correct attribute types.
func DataCustomerManagedResourcesGCPToObject(ctx context.Context, v *DataCustomerManagedResourcesGCPModel) (types.Object, diag.Diagnostics) {
	if v == nil {
		return types.ObjectNull(DataCustomerManagedResourcesGCPAttrTypes()), nil
	}
	return types.ObjectValueFrom(ctx, DataCustomerManagedResourcesGCPAttrTypes(), v)
}

// DecodeDataCustomerManagedResourcesGCPManagementBucket decodes the sub-field from its parent typed struct.
// Returns (nil, nil) when the field is null or unknown.
func DecodeDataCustomerManagedResourcesGCPManagementBucket(ctx context.Context, v *DataCustomerManagedResourcesGCPModel) (*DataCustomerManagedResourcesGCPManagementBucketModel, diag.Diagnostics) {
	if v == nil || v.ManagementBucket.IsNull() || v.ManagementBucket.IsUnknown() {
		return nil, nil
	}
	var out DataCustomerManagedResourcesGCPManagementBucketModel
	d := v.ManagementBucket.As(ctx, &out, basetypes.ObjectAsOptions{})
	return &out, d
}

// DataCustomerManagedResourcesGCPManagementBucketToObject encodes a typed struct back into types.Object.
// A nil receiver returns types.ObjectNull with the correct attribute types.
func DataCustomerManagedResourcesGCPManagementBucketToObject(ctx context.Context, v *DataCustomerManagedResourcesGCPManagementBucketModel) (types.Object, diag.Diagnostics) {
	if v == nil {
		return types.ObjectNull(DataCustomerManagedResourcesGCPManagementBucketAttrTypes()), nil
	}
	return types.ObjectValueFrom(ctx, DataCustomerManagedResourcesGCPManagementBucketAttrTypes(), v)
}
