// Code generated by modelgen. DO NOT EDIT.

// Copyright 2023 Redpanda Data, Inc.
//
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

// Package network contains the model for the network datasource.
package network

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// DataModel represents the Terraform schema for the network datasource.
type DataModel struct {
	CidrBlock                types.String `tfsdk:"cidr_block"`
	CloudProvider            types.String `tfsdk:"cloud_provider"`
	ClusterType              types.String `tfsdk:"cluster_type"`
	CustomerManagedResources types.Object `tfsdk:"customer_managed_resources"`
	ID                       types.String `tfsdk:"id"`
	Name                     types.String `tfsdk:"name"`
	Region                   types.String `tfsdk:"region"`
	ResourceGroupID          types.String `tfsdk:"resource_group_id"`
}
