// Code generated by schemagen. DO NOT EDIT.

// Copyright 2023 Redpanda Data, Inc.
//
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

package network

import (
	controlplanev1 "buf.build/gen/go/redpandadata/cloud/protocolbuffers/go/redpanda/api/controlplane/v1"
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/redpanda-data/terraform-provider-redpanda/internal/modelconv"
	"github.com/redpanda-data/terraform-provider-redpanda/redpanda/utils/enums"
)

type DataNetworkResponse interface {
	GetCidrBlock() string
	GetCloudProvider() controlplanev1.CloudProvider
	GetClusterType() controlplanev1.Cluster_Type
	GetCustomerManagedResources() *controlplanev1.Network_CustomerManagedResources
	GetEgressSpec() *controlplanev1.Network_EgressSpec
	GetId() string
	GetName() string
	GetRegion() string
	GetResourceGroupId() string
	GetState() controlplanev1.Network_State
	GetZones() []string
}

// FlattenData populates a *DataModel from the API response payload.
// The prev *DataModel arg carries forward TF-only / sensitive / write-only
// fields that the response cannot supply; pass nil when no prior state exists
// (e.g., during ImportState).
func FlattenData(ctx context.Context, proto DataNetworkResponse, prev *DataModel) (*DataModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	m := &DataModel{}
	m.ID = types.StringValue(proto.GetId())
	m.CidrBlock = cidrBlockFromProto(proto)
	m.CloudProvider = types.StringValue(enums.CloudProviderToString(proto.GetCloudProvider()))
	m.ClusterType = types.StringValue(enums.ClusterTypeToString(proto.GetClusterType()))
	m.CustomerManagedResources = modelconv.ObjectFromMessageWithDiagsAndPrev(ctx, proto.GetCustomerManagedResources(), func() *DataCustomerManagedResourcesModel { v, _ := prev.AsCustomerManagedResources(ctx); return v }(), DataCustomerManagedResourcesAttrTypes(), FlattenDataCustomerManagedResources, &diags)
	m.EgressSpec = modelconv.ObjectFromMessageWithDiagsAndPrev(ctx, proto.GetEgressSpec(), func() *DataEgressSpecModel { v, _ := prev.AsEgressSpec(ctx); return v }(), DataEgressSpecAttrTypes(), FlattenDataEgressSpec, &diags)
	m.Name = types.StringValue(proto.GetName())
	m.Region = types.StringValue(proto.GetRegion())
	m.ResourceGroupID = types.StringValue(proto.GetResourceGroupId())
	m.State = types.StringValue(enums.NetworkStateToString(proto.GetState()))
	m.Zones = modelconv.ListFromSliceWithDiags(ctx, proto.GetZones(), types.StringType, &diags)
	return m, diags
}

// FlattenDataCustomerManagedResources converts a single proto controlplanev1.Network_CustomerManagedResources into the
// corresponding nested model. The prev *DataCustomerManagedResourcesModel arg carries forward
// TF-only / sensitive / write-only fields and resolves the proto3
// null-vs-empty ambiguity for Optional-only scalar leaves (Required leaves
// flatten directly); pass nil when no prior nested state is available.
func FlattenDataCustomerManagedResources(ctx context.Context, proto *controlplanev1.Network_CustomerManagedResources, prev *DataCustomerManagedResourcesModel) (DataCustomerManagedResourcesModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	_ = prev
	m := DataCustomerManagedResourcesModel{}
	m.AWS = modelconv.ObjectFromMessageWithDiagsAndPrev(ctx, proto.GetAws(), func() *DataCustomerManagedResourcesAWSModel {
		v, _ := DecodeDataCustomerManagedResourcesAWS(ctx, prev)
		return v
	}(), DataCustomerManagedResourcesAWSAttrTypes(), FlattenDataCustomerManagedResourcesAWS, &diags)
	m.GCP = modelconv.ObjectFromMessageWithDiagsAndPrev(ctx, proto.GetGcp(), func() *DataCustomerManagedResourcesGCPModel {
		v, _ := DecodeDataCustomerManagedResourcesGCP(ctx, prev)
		return v
	}(), DataCustomerManagedResourcesGCPAttrTypes(), FlattenDataCustomerManagedResourcesGCP, &diags)
	return m, diags
}

// ExpandDataCustomerManagedResources renders a nested model back into the proto type.
func ExpandDataCustomerManagedResources(ctx context.Context, m *DataCustomerManagedResourcesModel) (*controlplanev1.Network_CustomerManagedResources, diag.Diagnostics) {
	var diags diag.Diagnostics
	if m == nil {
		return nil, diags
	}
	out := &controlplanev1.Network_CustomerManagedResources{}
	if v := modelconv.ObjectToMessageWithDiags(ctx, m.AWS, ExpandDataCustomerManagedResourcesAWS, &diags); v != nil {
		out.SetAws(v)
	}
	if v := modelconv.ObjectToMessageWithDiags(ctx, m.GCP, ExpandDataCustomerManagedResourcesGCP, &diags); v != nil {
		out.SetGcp(v)
	}
	return out, diags
}

// FlattenDataCustomerManagedResourcesAWS converts a single proto controlplanev1.Network_CustomerManagedResources_AWS into the
// corresponding nested model. The prev *DataCustomerManagedResourcesAWSModel arg carries forward
// TF-only / sensitive / write-only fields and resolves the proto3
// null-vs-empty ambiguity for Optional-only scalar leaves (Required leaves
// flatten directly); pass nil when no prior nested state is available.
func FlattenDataCustomerManagedResourcesAWS(ctx context.Context, proto *controlplanev1.Network_CustomerManagedResources_AWS, prev *DataCustomerManagedResourcesAWSModel) (DataCustomerManagedResourcesAWSModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	_ = prev
	m := DataCustomerManagedResourcesAWSModel{}
	m.DynamodbTable = modelconv.ObjectFromMessageWithDiagsAndPrev(ctx, proto.GetDynamodbTable(), func() *DataCustomerManagedResourcesAWSDynamodbTableModel {
		v, _ := DecodeDataCustomerManagedResourcesAWSDynamodbTable(ctx, prev)
		return v
	}(), DataCustomerManagedResourcesAWSDynamodbTableAttrTypes(), FlattenDataCustomerManagedResourcesAWSDynamodbTable, &diags)
	m.ManagementBucket = modelconv.ObjectFromMessageWithDiagsAndPrev(ctx, proto.GetManagementBucket(), func() *DataCustomerManagedResourcesAWSManagementBucketModel {
		v, _ := DecodeDataCustomerManagedResourcesAWSManagementBucket(ctx, prev)
		return v
	}(), DataCustomerManagedResourcesAWSManagementBucketAttrTypes(), FlattenDataCustomerManagedResourcesAWSManagementBucket, &diags)
	m.PrivateSubnets = modelconv.ObjectFromMessageWithDiagsAndPrev(ctx, proto.GetPrivateSubnets(), func() *DataCustomerManagedResourcesAWSPrivateSubnetsModel {
		v, _ := DecodeDataCustomerManagedResourcesAWSPrivateSubnets(ctx, prev)
		return v
	}(), DataCustomerManagedResourcesAWSPrivateSubnetsAttrTypes(), FlattenDataCustomerManagedResourcesAWSPrivateSubnets, &diags)
	m.VPC = modelconv.ObjectFromMessageWithDiagsAndPrev(ctx, proto.GetVpc(), func() *DataCustomerManagedResourcesAWSVPCModel {
		v, _ := DecodeDataCustomerManagedResourcesAWSVPC(ctx, prev)
		return v
	}(), DataCustomerManagedResourcesAWSVPCAttrTypes(), FlattenDataCustomerManagedResourcesAWSVPC, &diags)
	return m, diags
}

// ExpandDataCustomerManagedResourcesAWS renders a nested model back into the proto type.
func ExpandDataCustomerManagedResourcesAWS(ctx context.Context, m *DataCustomerManagedResourcesAWSModel) (*controlplanev1.Network_CustomerManagedResources_AWS, diag.Diagnostics) {
	var diags diag.Diagnostics
	if m == nil {
		return nil, diags
	}
	out := &controlplanev1.Network_CustomerManagedResources_AWS{
		DynamodbTable:    modelconv.ObjectToMessageWithDiags(ctx, m.DynamodbTable, ExpandDataCustomerManagedResourcesAWSDynamodbTable, &diags),
		ManagementBucket: modelconv.ObjectToMessageWithDiags(ctx, m.ManagementBucket, ExpandDataCustomerManagedResourcesAWSManagementBucket, &diags),
		PrivateSubnets:   modelconv.ObjectToMessageWithDiags(ctx, m.PrivateSubnets, ExpandDataCustomerManagedResourcesAWSPrivateSubnets, &diags),
		Vpc:              modelconv.ObjectToMessageWithDiags(ctx, m.VPC, ExpandDataCustomerManagedResourcesAWSVPC, &diags),
	}
	return out, diags
}

// FlattenDataCustomerManagedResourcesAWSDynamodbTable converts a single proto controlplanev1.CustomerManagedDynamoDBTable into the
// corresponding nested model. The prev *DataCustomerManagedResourcesAWSDynamodbTableModel arg carries forward
// TF-only / sensitive / write-only fields and resolves the proto3
// null-vs-empty ambiguity for Optional-only scalar leaves (Required leaves
// flatten directly); pass nil when no prior nested state is available.
func FlattenDataCustomerManagedResourcesAWSDynamodbTable(_ context.Context, proto *controlplanev1.CustomerManagedDynamoDBTable, prev *DataCustomerManagedResourcesAWSDynamodbTableModel) (DataCustomerManagedResourcesAWSDynamodbTableModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	_ = prev
	m := DataCustomerManagedResourcesAWSDynamodbTableModel{}
	m.ARN = types.StringValue(proto.GetArn())
	return m, diags
}

// ExpandDataCustomerManagedResourcesAWSDynamodbTable renders a nested model back into the proto type.
func ExpandDataCustomerManagedResourcesAWSDynamodbTable(_ context.Context, m *DataCustomerManagedResourcesAWSDynamodbTableModel) (*controlplanev1.CustomerManagedDynamoDBTable, diag.Diagnostics) {
	var diags diag.Diagnostics
	if m == nil {
		return nil, diags
	}
	out := &controlplanev1.CustomerManagedDynamoDBTable{
		Arn: m.ARN.ValueString(),
	}
	return out, diags
}

// FlattenDataCustomerManagedResourcesAWSManagementBucket converts a single proto controlplanev1.CustomerManagedAWSCloudStorageBucket into the
// corresponding nested model. The prev *DataCustomerManagedResourcesAWSManagementBucketModel arg carries forward
// TF-only / sensitive / write-only fields and resolves the proto3
// null-vs-empty ambiguity for Optional-only scalar leaves (Required leaves
// flatten directly); pass nil when no prior nested state is available.
func FlattenDataCustomerManagedResourcesAWSManagementBucket(_ context.Context, proto *controlplanev1.CustomerManagedAWSCloudStorageBucket, prev *DataCustomerManagedResourcesAWSManagementBucketModel) (DataCustomerManagedResourcesAWSManagementBucketModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	_ = prev
	m := DataCustomerManagedResourcesAWSManagementBucketModel{}
	m.ARN = types.StringValue(proto.GetArn())
	return m, diags
}

// ExpandDataCustomerManagedResourcesAWSManagementBucket renders a nested model back into the proto type.
func ExpandDataCustomerManagedResourcesAWSManagementBucket(_ context.Context, m *DataCustomerManagedResourcesAWSManagementBucketModel) (*controlplanev1.CustomerManagedAWSCloudStorageBucket, diag.Diagnostics) {
	var diags diag.Diagnostics
	if m == nil {
		return nil, diags
	}
	out := &controlplanev1.CustomerManagedAWSCloudStorageBucket{
		Arn: m.ARN.ValueString(),
	}
	return out, diags
}

// FlattenDataCustomerManagedResourcesAWSPrivateSubnets converts a single proto controlplanev1.CustomerManagedAWSSubnets into the
// corresponding nested model. The prev *DataCustomerManagedResourcesAWSPrivateSubnetsModel arg carries forward
// TF-only / sensitive / write-only fields and resolves the proto3
// null-vs-empty ambiguity for Optional-only scalar leaves (Required leaves
// flatten directly); pass nil when no prior nested state is available.
func FlattenDataCustomerManagedResourcesAWSPrivateSubnets(ctx context.Context, proto *controlplanev1.CustomerManagedAWSSubnets, prev *DataCustomerManagedResourcesAWSPrivateSubnetsModel) (DataCustomerManagedResourcesAWSPrivateSubnetsModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	_ = prev
	m := DataCustomerManagedResourcesAWSPrivateSubnetsModel{}
	m.Arns = modelconv.ListFromSliceWithDiags(ctx, proto.GetArns(), types.StringType, &diags)
	return m, diags
}

// ExpandDataCustomerManagedResourcesAWSPrivateSubnets renders a nested model back into the proto type.
func ExpandDataCustomerManagedResourcesAWSPrivateSubnets(ctx context.Context, m *DataCustomerManagedResourcesAWSPrivateSubnetsModel) (*controlplanev1.CustomerManagedAWSSubnets, diag.Diagnostics) {
	var diags diag.Diagnostics
	if m == nil {
		return nil, diags
	}
	out := &controlplanev1.CustomerManagedAWSSubnets{
		Arns: modelconv.ListToSliceWithDiags[string](ctx, m.Arns, &diags),
	}
	return out, diags
}

// FlattenDataCustomerManagedResourcesAWSVPC converts a single proto controlplanev1.CustomerManagedAWSVPC into the
// corresponding nested model. The prev *DataCustomerManagedResourcesAWSVPCModel arg carries forward
// TF-only / sensitive / write-only fields and resolves the proto3
// null-vs-empty ambiguity for Optional-only scalar leaves (Required leaves
// flatten directly); pass nil when no prior nested state is available.
func FlattenDataCustomerManagedResourcesAWSVPC(_ context.Context, proto *controlplanev1.CustomerManagedAWSVPC, prev *DataCustomerManagedResourcesAWSVPCModel) (DataCustomerManagedResourcesAWSVPCModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	_ = prev
	m := DataCustomerManagedResourcesAWSVPCModel{}
	m.ARN = types.StringValue(proto.GetArn())
	return m, diags
}

// ExpandDataCustomerManagedResourcesAWSVPC renders a nested model back into the proto type.
func ExpandDataCustomerManagedResourcesAWSVPC(_ context.Context, m *DataCustomerManagedResourcesAWSVPCModel) (*controlplanev1.CustomerManagedAWSVPC, diag.Diagnostics) {
	var diags diag.Diagnostics
	if m == nil {
		return nil, diags
	}
	out := &controlplanev1.CustomerManagedAWSVPC{
		Arn: m.ARN.ValueString(),
	}
	return out, diags
}

// FlattenDataCustomerManagedResourcesGCP converts a single proto controlplanev1.Network_CustomerManagedResources_GCP into the
// corresponding nested model. The prev *DataCustomerManagedResourcesGCPModel arg carries forward
// TF-only / sensitive / write-only fields and resolves the proto3
// null-vs-empty ambiguity for Optional-only scalar leaves (Required leaves
// flatten directly); pass nil when no prior nested state is available.
func FlattenDataCustomerManagedResourcesGCP(ctx context.Context, proto *controlplanev1.Network_CustomerManagedResources_GCP, prev *DataCustomerManagedResourcesGCPModel) (DataCustomerManagedResourcesGCPModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	_ = prev
	m := DataCustomerManagedResourcesGCPModel{}
	m.ManagementBucket = modelconv.ObjectFromMessageWithDiagsAndPrev(ctx, proto.GetManagementBucket(), func() *DataCustomerManagedResourcesGCPManagementBucketModel {
		v, _ := DecodeDataCustomerManagedResourcesGCPManagementBucket(ctx, prev)
		return v
	}(), DataCustomerManagedResourcesGCPManagementBucketAttrTypes(), FlattenDataCustomerManagedResourcesGCPManagementBucket, &diags)
	m.NetworkName = types.StringValue(proto.GetNetworkName())
	m.NetworkProjectID = types.StringValue(proto.GetNetworkProjectId())
	return m, diags
}

// ExpandDataCustomerManagedResourcesGCP renders a nested model back into the proto type.
func ExpandDataCustomerManagedResourcesGCP(ctx context.Context, m *DataCustomerManagedResourcesGCPModel) (*controlplanev1.Network_CustomerManagedResources_GCP, diag.Diagnostics) {
	var diags diag.Diagnostics
	if m == nil {
		return nil, diags
	}
	out := &controlplanev1.Network_CustomerManagedResources_GCP{
		ManagementBucket: modelconv.ObjectToMessageWithDiags(ctx, m.ManagementBucket, ExpandDataCustomerManagedResourcesGCPManagementBucket, &diags),
		NetworkName:      m.NetworkName.ValueString(),
		NetworkProjectId: m.NetworkProjectID.ValueString(),
	}
	return out, diags
}

// FlattenDataCustomerManagedResourcesGCPManagementBucket converts a single proto controlplanev1.CustomerManagedGoogleCloudStorageBucket into the
// corresponding nested model. The prev *DataCustomerManagedResourcesGCPManagementBucketModel arg carries forward
// TF-only / sensitive / write-only fields and resolves the proto3
// null-vs-empty ambiguity for Optional-only scalar leaves (Required leaves
// flatten directly); pass nil when no prior nested state is available.
func FlattenDataCustomerManagedResourcesGCPManagementBucket(_ context.Context, proto *controlplanev1.CustomerManagedGoogleCloudStorageBucket, prev *DataCustomerManagedResourcesGCPManagementBucketModel) (DataCustomerManagedResourcesGCPManagementBucketModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	_ = prev
	m := DataCustomerManagedResourcesGCPManagementBucketModel{}
	m.Name = types.StringValue(proto.GetName())
	return m, diags
}

// ExpandDataCustomerManagedResourcesGCPManagementBucket renders a nested model back into the proto type.
func ExpandDataCustomerManagedResourcesGCPManagementBucket(_ context.Context, m *DataCustomerManagedResourcesGCPManagementBucketModel) (*controlplanev1.CustomerManagedGoogleCloudStorageBucket, diag.Diagnostics) {
	var diags diag.Diagnostics
	if m == nil {
		return nil, diags
	}
	out := &controlplanev1.CustomerManagedGoogleCloudStorageBucket{
		Name: m.Name.ValueString(),
	}
	return out, diags
}

// FlattenDataEgressSpec converts a single proto controlplanev1.Network_EgressSpec into the
// corresponding nested model. The prev *DataEgressSpecModel arg carries forward
// TF-only / sensitive / write-only fields and resolves the proto3
// null-vs-empty ambiguity for Optional-only scalar leaves (Required leaves
// flatten directly); pass nil when no prior nested state is available.
func FlattenDataEgressSpec(ctx context.Context, proto *controlplanev1.Network_EgressSpec, prev *DataEgressSpecModel) (DataEgressSpecModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	_ = prev
	m := DataEgressSpecModel{}
	m.AWS = modelconv.ObjectFromMessageWithDiagsAndPrev(ctx, proto.GetAws(), func() *DataEgressSpecAWSModel { v, _ := DecodeDataEgressSpecAWS(ctx, prev); return v }(), DataEgressSpecAWSAttrTypes(), FlattenDataEgressSpecAWS, &diags)
	m.Azure = modelconv.ObjectFromMessageWithDiagsAndPrev(ctx, proto.GetAzure(), func() *DataEgressSpecAzureModel { v, _ := DecodeDataEgressSpecAzure(ctx, prev); return v }(), DataEgressSpecAzureAttrTypes(), FlattenDataEgressSpecAzure, &diags)
	m.GCP = modelconv.ObjectFromMessageWithDiagsAndPrev(ctx, proto.GetGcp(), func() *DataEgressSpecGCPModel { v, _ := DecodeDataEgressSpecGCP(ctx, prev); return v }(), DataEgressSpecGCPAttrTypes(), FlattenDataEgressSpecGCP, &diags)
	return m, diags
}

// ExpandDataEgressSpec renders a nested model back into the proto type.
func ExpandDataEgressSpec(ctx context.Context, m *DataEgressSpecModel) (*controlplanev1.Network_EgressSpec, diag.Diagnostics) {
	var diags diag.Diagnostics
	if m == nil {
		return nil, diags
	}
	out := &controlplanev1.Network_EgressSpec{}
	if v := modelconv.ObjectToMessageWithDiags(ctx, m.AWS, ExpandDataEgressSpecAWS, &diags); v != nil {
		out.SetAws(v)
	}
	if v := modelconv.ObjectToMessageWithDiags(ctx, m.Azure, ExpandDataEgressSpecAzure, &diags); v != nil {
		out.SetAzure(v)
	}
	if v := modelconv.ObjectToMessageWithDiags(ctx, m.GCP, ExpandDataEgressSpecGCP, &diags); v != nil {
		out.SetGcp(v)
	}
	return out, diags
}

// FlattenDataEgressSpecAWS converts a single proto controlplanev1.Network_EgressSpec_AWS into the
// corresponding nested model. The prev *DataEgressSpecAWSModel arg carries forward
// TF-only / sensitive / write-only fields and resolves the proto3
// null-vs-empty ambiguity for Optional-only scalar leaves (Required leaves
// flatten directly); pass nil when no prior nested state is available.
func FlattenDataEgressSpecAWS(_ context.Context, proto *controlplanev1.Network_EgressSpec_AWS, prev *DataEgressSpecAWSModel) (DataEgressSpecAWSModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	_ = prev
	m := DataEgressSpecAWSModel{}
	m.TransitGatewayID = types.StringValue(proto.GetTransitGatewayId())
	return m, diags
}

// ExpandDataEgressSpecAWS renders a nested model back into the proto type.
func ExpandDataEgressSpecAWS(_ context.Context, m *DataEgressSpecAWSModel) (*controlplanev1.Network_EgressSpec_AWS, diag.Diagnostics) {
	var diags diag.Diagnostics
	if m == nil {
		return nil, diags
	}
	out := &controlplanev1.Network_EgressSpec_AWS{
		TransitGatewayId: m.TransitGatewayID.ValueString(),
	}
	return out, diags
}

// FlattenDataEgressSpecAzure converts a single proto controlplanev1.Network_EgressSpec_Azure into the
// corresponding nested model. The prev *DataEgressSpecAzureModel arg carries forward
// TF-only / sensitive / write-only fields and resolves the proto3
// null-vs-empty ambiguity for Optional-only scalar leaves (Required leaves
// flatten directly); pass nil when no prior nested state is available.
func FlattenDataEgressSpecAzure(_ context.Context, proto *controlplanev1.Network_EgressSpec_Azure, prev *DataEgressSpecAzureModel) (DataEgressSpecAzureModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	_ = prev
	m := DataEgressSpecAzureModel{}
	m.FirewallPrivateIp = types.StringValue(proto.GetFirewallPrivateIp())
	m.HubVnetID = types.StringValue(proto.GetHubVnetId())
	return m, diags
}

// ExpandDataEgressSpecAzure renders a nested model back into the proto type.
func ExpandDataEgressSpecAzure(_ context.Context, m *DataEgressSpecAzureModel) (*controlplanev1.Network_EgressSpec_Azure, diag.Diagnostics) {
	var diags diag.Diagnostics
	if m == nil {
		return nil, diags
	}
	out := &controlplanev1.Network_EgressSpec_Azure{
		FirewallPrivateIp: m.FirewallPrivateIp.ValueString(),
		HubVnetId:         m.HubVnetID.ValueString(),
	}
	return out, diags
}

// FlattenDataEgressSpecGCP converts a single proto controlplanev1.Network_EgressSpec_GCP into the
// corresponding nested model. The prev *DataEgressSpecGCPModel arg carries forward
// TF-only / sensitive / write-only fields and resolves the proto3
// null-vs-empty ambiguity for Optional-only scalar leaves (Required leaves
// flatten directly); pass nil when no prior nested state is available.
func FlattenDataEgressSpecGCP(_ context.Context, proto *controlplanev1.Network_EgressSpec_GCP, prev *DataEgressSpecGCPModel) (DataEgressSpecGCPModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	_ = prev
	m := DataEgressSpecGCPModel{}
	m.HubVPCName = types.StringValue(proto.GetHubVpcName())
	m.HubVPCProject = types.StringValue(proto.GetHubVpcProject())
	return m, diags
}

// ExpandDataEgressSpecGCP renders a nested model back into the proto type.
func ExpandDataEgressSpecGCP(_ context.Context, m *DataEgressSpecGCPModel) (*controlplanev1.Network_EgressSpec_GCP, diag.Diagnostics) {
	var diags diag.Diagnostics
	if m == nil {
		return nil, diags
	}
	out := &controlplanev1.Network_EgressSpec_GCP{
		HubVpcName:    m.HubVPCName.ValueString(),
		HubVpcProject: m.HubVPCProject.ValueString(),
	}
	return out, diags
}
