// Code generated by go generate; DO NOT EDIT.
// Generated by: redpanda/utils/testutil/generator

package network

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/redpanda-data/terraform-provider-redpanda/redpanda/utils/compare"
)

// Compare performs comprehensive field-by-field comparison between two ResourceModel instances
func (m *ResourceModel) Compare(other *ResourceModel) []compare.FieldDiff {
	var diffs []compare.FieldDiff

	// String fields
	compare.Collect(&diffs, compare.String("name", m.Name, other.Name))
	compare.Collect(&diffs, compare.String("resource_group_id", m.ResourceGroupID, other.ResourceGroupID))
	compare.Collect(&diffs, compare.String("cloud_provider", m.CloudProvider, other.CloudProvider))
	compare.Collect(&diffs, compare.String("region", m.Region, other.Region))
	compare.Collect(&diffs, compare.String("cidr_block", m.CidrBlock, other.CidrBlock))
	compare.Collect(&diffs, compare.String("id", m.ID, other.ID))
	compare.Collect(&diffs, compare.String("cluster_type", m.ClusterType, other.ClusterType))

	// Object fields (deep comparison)
	compare.CollectAll(&diffs, compareCustomerManagedResources("customer_managed_resources", m.CustomerManagedResources, other.CustomerManagedResources))

	return diffs
}

// Compare performs comprehensive field-by-field comparison between two DataModel instances
func (m *DataModel) Compare(other *DataModel) []compare.FieldDiff {
	var diffs []compare.FieldDiff

	// String fields
	compare.Collect(&diffs, compare.String("name", m.Name, other.Name))
	compare.Collect(&diffs, compare.String("resource_group_id", m.ResourceGroupID, other.ResourceGroupID))
	compare.Collect(&diffs, compare.String("cloud_provider", m.CloudProvider, other.CloudProvider))
	compare.Collect(&diffs, compare.String("region", m.Region, other.Region))
	compare.Collect(&diffs, compare.String("cidr_block", m.CidrBlock, other.CidrBlock))
	compare.Collect(&diffs, compare.String("id", m.ID, other.ID))
	compare.Collect(&diffs, compare.String("cluster_type", m.ClusterType, other.ClusterType))

	// Object fields (deep comparison)
	compare.CollectAll(&diffs, compareCustomerManagedResources("customer_managed_resources", m.CustomerManagedResources, other.CustomerManagedResources))

	return diffs
}

// compareCustomerManagedResources compares customer_managed_resources objects
func compareCustomerManagedResources(field string, a, b types.Object) []compare.FieldDiff {
	if d := compare.ObjectNullCheck(field, a, b); d != nil {
		return []compare.FieldDiff{*d}
	}
	if a.IsNull() {
		return nil
	}
	// No deep comparison available for customer_managed_resources
	return nil
}
