// Code generated by schemagen. DO NOT EDIT.

// Copyright 2023 Redpanda Data, Inc.
//
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

// Package network contains the model for the network resource.
package network

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

// ResourceModel represents the Terraform schema for the network resource.
type ResourceModel struct {
	CidrBlock                types.String   `tfsdk:"cidr_block"`
	CloudProvider            types.String   `tfsdk:"cloud_provider"`
	ClusterType              types.String   `tfsdk:"cluster_type"`
	CustomerManagedResources types.Object   `tfsdk:"customer_managed_resources"`
	ID                       types.String   `tfsdk:"id"`
	Name                     types.String   `tfsdk:"name"`
	Region                   types.String   `tfsdk:"region"`
	ResourceGroupID          types.String   `tfsdk:"resource_group_id"`
	State                    types.String   `tfsdk:"state"`
	Timeouts                 timeouts.Value `tfsdk:"timeouts"`
	Zones                    types.List     `tfsdk:"zones"`
}

// --- Nested typed structs (one per nested message in the proto tree) ---

// CustomerManagedResourcesModel mirrors the nested "customer_managed_resources" attribute. Use the As/To
// converters on the parent struct to move between types.Object and this
// typed form.
type CustomerManagedResourcesModel struct {
	AWS types.Object `tfsdk:"aws"`
	GCP types.Object `tfsdk:"gcp"`
}

// CustomerManagedResourcesAWSModel mirrors the nested "customer_managed_resources.aws" attribute. Use the As/To
// converters on the parent struct to move between types.Object and this
// typed form.
type CustomerManagedResourcesAWSModel struct {
	DynamodbTable    types.Object `tfsdk:"dynamodb_table"`
	ManagementBucket types.Object `tfsdk:"management_bucket"`
	PrivateSubnets   types.Object `tfsdk:"private_subnets"`
	VPC              types.Object `tfsdk:"vpc"`
}

// CustomerManagedResourcesAWSDynamodbTableModel mirrors the nested "customer_managed_resources.aws.dynamodb_table" attribute. Use the As/To
// converters on the parent struct to move between types.Object and this
// typed form.
type CustomerManagedResourcesAWSDynamodbTableModel struct {
	ARN types.String `tfsdk:"arn"`
}

// CustomerManagedResourcesAWSManagementBucketModel mirrors the nested "customer_managed_resources.aws.management_bucket" attribute. Use the As/To
// converters on the parent struct to move between types.Object and this
// typed form.
type CustomerManagedResourcesAWSManagementBucketModel struct {
	ARN types.String `tfsdk:"arn"`
}

// CustomerManagedResourcesAWSPrivateSubnetsModel mirrors the nested "customer_managed_resources.aws.private_subnets" attribute. Use the As/To
// converters on the parent struct to move between types.Object and this
// typed form.
type CustomerManagedResourcesAWSPrivateSubnetsModel struct {
	Arns types.List `tfsdk:"arns"`
}

// CustomerManagedResourcesAWSVPCModel mirrors the nested "customer_managed_resources.aws.vpc" attribute. Use the As/To
// converters on the parent struct to move between types.Object and this
// typed form.
type CustomerManagedResourcesAWSVPCModel struct {
	ARN types.String `tfsdk:"arn"`
}

// CustomerManagedResourcesGCPModel mirrors the nested "customer_managed_resources.gcp" attribute. Use the As/To
// converters on the parent struct to move between types.Object and this
// typed form.
type CustomerManagedResourcesGCPModel struct {
	ManagementBucket types.Object `tfsdk:"management_bucket"`
	NetworkName      types.String `tfsdk:"network_name"`
	NetworkProjectID types.String `tfsdk:"network_project_id"`
}

// CustomerManagedResourcesGCPManagementBucketModel mirrors the nested "customer_managed_resources.gcp.management_bucket" attribute. Use the As/To
// converters on the parent struct to move between types.Object and this
// typed form.
type CustomerManagedResourcesGCPManagementBucketModel struct {
	Name types.String `tfsdk:"name"`
}

// --- AttrType tables for nested types (consumed by types.ObjectValueFrom / ObjectNull) ---

// CustomerManagedResourcesAttrTypes returns the attr.Type map for the "customer_managed_resources" nested
// attribute.
func CustomerManagedResourcesAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"aws": types.ObjectType{AttrTypes: CustomerManagedResourcesAWSAttrTypes()},
		"gcp": types.ObjectType{AttrTypes: CustomerManagedResourcesGCPAttrTypes()},
	}
}

// CustomerManagedResourcesAWSAttrTypes returns the attr.Type map for the "customer_managed_resources.aws" nested
// attribute.
func CustomerManagedResourcesAWSAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"dynamodb_table":    types.ObjectType{AttrTypes: CustomerManagedResourcesAWSDynamodbTableAttrTypes()},
		"management_bucket": types.ObjectType{AttrTypes: CustomerManagedResourcesAWSManagementBucketAttrTypes()},
		"private_subnets":   types.ObjectType{AttrTypes: CustomerManagedResourcesAWSPrivateSubnetsAttrTypes()},
		"vpc":               types.ObjectType{AttrTypes: CustomerManagedResourcesAWSVPCAttrTypes()},
	}
}

// CustomerManagedResourcesAWSDynamodbTableAttrTypes returns the attr.Type map for the "customer_managed_resources.aws.dynamodb_table" nested
// attribute.
func CustomerManagedResourcesAWSDynamodbTableAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"arn": types.StringType,
	}
}

// CustomerManagedResourcesAWSManagementBucketAttrTypes returns the attr.Type map for the "customer_managed_resources.aws.management_bucket" nested
// attribute.
func CustomerManagedResourcesAWSManagementBucketAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"arn": types.StringType,
	}
}

// CustomerManagedResourcesAWSPrivateSubnetsAttrTypes returns the attr.Type map for the "customer_managed_resources.aws.private_subnets" nested
// attribute.
func CustomerManagedResourcesAWSPrivateSubnetsAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"arns": types.ListType{ElemType: types.StringType},
	}
}

// CustomerManagedResourcesAWSVPCAttrTypes returns the attr.Type map for the "customer_managed_resources.aws.vpc" nested
// attribute.
func CustomerManagedResourcesAWSVPCAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"arn": types.StringType,
	}
}

// CustomerManagedResourcesGCPAttrTypes returns the attr.Type map for the "customer_managed_resources.gcp" nested
// attribute.
func CustomerManagedResourcesGCPAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"management_bucket":  types.ObjectType{AttrTypes: CustomerManagedResourcesGCPManagementBucketAttrTypes()},
		"network_name":       types.StringType,
		"network_project_id": types.StringType,
	}
}

// CustomerManagedResourcesGCPManagementBucketAttrTypes returns the attr.Type map for the "customer_managed_resources.gcp.management_bucket" nested
// attribute.
func CustomerManagedResourcesGCPManagementBucketAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"name": types.StringType,
	}
}

// --- Root-level converters (types.Object ⇄ typed struct ergonomics) ---

// AsCustomerManagedResources converts the root customer_managed_resources attribute from
// types.Object into its typed form. Returns (nil, nil) when the object is
// null or unknown. Use this when you want typed field access without
// manually unpacking .Attributes().
func (m *ResourceModel) AsCustomerManagedResources(ctx context.Context) (*CustomerManagedResourcesModel, diag.Diagnostics) {
	if m == nil || m.CustomerManagedResources.IsNull() || m.CustomerManagedResources.IsUnknown() {
		return nil, nil
	}
	var out CustomerManagedResourcesModel
	d := m.CustomerManagedResources.As(ctx, &out, basetypes.ObjectAsOptions{})
	return &out, d
}

// CustomerManagedResourcesToObject encodes a typed struct back into the
// types.Object shape expected by the framework. A nil receiver returns
// types.ObjectNull with the correct attribute types.
func CustomerManagedResourcesToObject(ctx context.Context, v *CustomerManagedResourcesModel) (types.Object, diag.Diagnostics) {
	if v == nil {
		return types.ObjectNull(CustomerManagedResourcesAttrTypes()), nil
	}
	return types.ObjectValueFrom(ctx, CustomerManagedResourcesAttrTypes(), v)
}

// --- Sub-level converters (free-standing Decode*/ToObject for types nested beyond root level) ---

// DecodeCustomerManagedResourcesAWS decodes the sub-field from its parent typed struct.
// Returns (nil, nil) when the field is null or unknown.
func DecodeCustomerManagedResourcesAWS(ctx context.Context, v *CustomerManagedResourcesModel) (*CustomerManagedResourcesAWSModel, diag.Diagnostics) {
	if v == nil || v.AWS.IsNull() || v.AWS.IsUnknown() {
		return nil, nil
	}
	var out CustomerManagedResourcesAWSModel
	d := v.AWS.As(ctx, &out, basetypes.ObjectAsOptions{})
	return &out, d
}

// CustomerManagedResourcesAWSToObject encodes a typed struct back into types.Object.
// A nil receiver returns types.ObjectNull with the correct attribute types.
func CustomerManagedResourcesAWSToObject(ctx context.Context, v *CustomerManagedResourcesAWSModel) (types.Object, diag.Diagnostics) {
	if v == nil {
		return types.ObjectNull(CustomerManagedResourcesAWSAttrTypes()), nil
	}
	return types.ObjectValueFrom(ctx, CustomerManagedResourcesAWSAttrTypes(), v)
}

// DecodeCustomerManagedResourcesAWSDynamodbTable decodes the sub-field from its parent typed struct.
// Returns (nil, nil) when the field is null or unknown.
func DecodeCustomerManagedResourcesAWSDynamodbTable(ctx context.Context, v *CustomerManagedResourcesAWSModel) (*CustomerManagedResourcesAWSDynamodbTableModel, diag.Diagnostics) {
	if v == nil || v.DynamodbTable.IsNull() || v.DynamodbTable.IsUnknown() {
		return nil, nil
	}
	var out CustomerManagedResourcesAWSDynamodbTableModel
	d := v.DynamodbTable.As(ctx, &out, basetypes.ObjectAsOptions{})
	return &out, d
}

// CustomerManagedResourcesAWSDynamodbTableToObject encodes a typed struct back into types.Object.
// A nil receiver returns types.ObjectNull with the correct attribute types.
func CustomerManagedResourcesAWSDynamodbTableToObject(ctx context.Context, v *CustomerManagedResourcesAWSDynamodbTableModel) (types.Object, diag.Diagnostics) {
	if v == nil {
		return types.ObjectNull(CustomerManagedResourcesAWSDynamodbTableAttrTypes()), nil
	}
	return types.ObjectValueFrom(ctx, CustomerManagedResourcesAWSDynamodbTableAttrTypes(), v)
}

// DecodeCustomerManagedResourcesAWSManagementBucket decodes the sub-field from its parent typed struct.
// Returns (nil, nil) when the field is null or unknown.
func DecodeCustomerManagedResourcesAWSManagementBucket(ctx context.Context, v *CustomerManagedResourcesAWSModel) (*CustomerManagedResourcesAWSManagementBucketModel, diag.Diagnostics) {
	if v == nil || v.ManagementBucket.IsNull() || v.ManagementBucket.IsUnknown() {
		return nil, nil
	}
	var out CustomerManagedResourcesAWSManagementBucketModel
	d := v.ManagementBucket.As(ctx, &out, basetypes.ObjectAsOptions{})
	return &out, d
}

// CustomerManagedResourcesAWSManagementBucketToObject encodes a typed struct back into types.Object.
// A nil receiver returns types.ObjectNull with the correct attribute types.
func CustomerManagedResourcesAWSManagementBucketToObject(ctx context.Context, v *CustomerManagedResourcesAWSManagementBucketModel) (types.Object, diag.Diagnostics) {
	if v == nil {
		return types.ObjectNull(CustomerManagedResourcesAWSManagementBucketAttrTypes()), nil
	}
	return types.ObjectValueFrom(ctx, CustomerManagedResourcesAWSManagementBucketAttrTypes(), v)
}

// DecodeCustomerManagedResourcesAWSPrivateSubnets decodes the sub-field from its parent typed struct.
// Returns (nil, nil) when the field is null or unknown.
func DecodeCustomerManagedResourcesAWSPrivateSubnets(ctx context.Context, v *CustomerManagedResourcesAWSModel) (*CustomerManagedResourcesAWSPrivateSubnetsModel, diag.Diagnostics) {
	if v == nil || v.PrivateSubnets.IsNull() || v.PrivateSubnets.IsUnknown() {
		return nil, nil
	}
	var out CustomerManagedResourcesAWSPrivateSubnetsModel
	d := v.PrivateSubnets.As(ctx, &out, basetypes.ObjectAsOptions{})
	return &out, d
}

// CustomerManagedResourcesAWSPrivateSubnetsToObject encodes a typed struct back into types.Object.
// A nil receiver returns types.ObjectNull with the correct attribute types.
func CustomerManagedResourcesAWSPrivateSubnetsToObject(ctx context.Context, v *CustomerManagedResourcesAWSPrivateSubnetsModel) (types.Object, diag.Diagnostics) {
	if v == nil {
		return types.ObjectNull(CustomerManagedResourcesAWSPrivateSubnetsAttrTypes()), nil
	}
	return types.ObjectValueFrom(ctx, CustomerManagedResourcesAWSPrivateSubnetsAttrTypes(), v)
}

// DecodeCustomerManagedResourcesAWSVPC decodes the sub-field from its parent typed struct.
// Returns (nil, nil) when the field is null or unknown.
func DecodeCustomerManagedResourcesAWSVPC(ctx context.Context, v *CustomerManagedResourcesAWSModel) (*CustomerManagedResourcesAWSVPCModel, diag.Diagnostics) {
	if v == nil || v.VPC.IsNull() || v.VPC.IsUnknown() {
		return nil, nil
	}
	var out CustomerManagedResourcesAWSVPCModel
	d := v.VPC.As(ctx, &out, basetypes.ObjectAsOptions{})
	return &out, d
}

// CustomerManagedResourcesAWSVPCToObject encodes a typed struct back into types.Object.
// A nil receiver returns types.ObjectNull with the correct attribute types.
func CustomerManagedResourcesAWSVPCToObject(ctx context.Context, v *CustomerManagedResourcesAWSVPCModel) (types.Object, diag.Diagnostics) {
	if v == nil {
		return types.ObjectNull(CustomerManagedResourcesAWSVPCAttrTypes()), nil
	}
	return types.ObjectValueFrom(ctx, CustomerManagedResourcesAWSVPCAttrTypes(), v)
}

// DecodeCustomerManagedResourcesGCP decodes the sub-field from its parent typed struct.
// Returns (nil, nil) when the field is null or unknown.
func DecodeCustomerManagedResourcesGCP(ctx context.Context, v *CustomerManagedResourcesModel) (*CustomerManagedResourcesGCPModel, diag.Diagnostics) {
	if v == nil || v.GCP.IsNull() || v.GCP.IsUnknown() {
		return nil, nil
	}
	var out CustomerManagedResourcesGCPModel
	d := v.GCP.As(ctx, &out, basetypes.ObjectAsOptions{})
	return &out, d
}

// CustomerManagedResourcesGCPToObject encodes a typed struct back into types.Object.
// A nil receiver returns types.ObjectNull with the correct attribute types.
func CustomerManagedResourcesGCPToObject(ctx context.Context, v *CustomerManagedResourcesGCPModel) (types.Object, diag.Diagnostics) {
	if v == nil {
		return types.ObjectNull(CustomerManagedResourcesGCPAttrTypes()), nil
	}
	return types.ObjectValueFrom(ctx, CustomerManagedResourcesGCPAttrTypes(), v)
}

// DecodeCustomerManagedResourcesGCPManagementBucket decodes the sub-field from its parent typed struct.
// Returns (nil, nil) when the field is null or unknown.
func DecodeCustomerManagedResourcesGCPManagementBucket(ctx context.Context, v *CustomerManagedResourcesGCPModel) (*CustomerManagedResourcesGCPManagementBucketModel, diag.Diagnostics) {
	if v == nil || v.ManagementBucket.IsNull() || v.ManagementBucket.IsUnknown() {
		return nil, nil
	}
	var out CustomerManagedResourcesGCPManagementBucketModel
	d := v.ManagementBucket.As(ctx, &out, basetypes.ObjectAsOptions{})
	return &out, d
}

// CustomerManagedResourcesGCPManagementBucketToObject encodes a typed struct back into types.Object.
// A nil receiver returns types.ObjectNull with the correct attribute types.
func CustomerManagedResourcesGCPManagementBucketToObject(ctx context.Context, v *CustomerManagedResourcesGCPManagementBucketModel) (types.Object, diag.Diagnostics) {
	if v == nil {
		return types.ObjectNull(CustomerManagedResourcesGCPManagementBucketAttrTypes()), nil
	}
	return types.ObjectValueFrom(ctx, CustomerManagedResourcesGCPManagementBucketAttrTypes(), v)
}

// GenerateMinimalResourceModel returns a *ResourceModel populated only with
// the supplied id + timeouts; every other field is at its typed null (or its
// declared minimal_default). Used by resources that need to persist a
// partial state when Create / Read returns mid-flight.
func GenerateMinimalResourceModel(id types.String, timeout timeouts.Value) *ResourceModel {
	return &ResourceModel{
		CidrBlock:                types.StringNull(),
		CloudProvider:            types.StringNull(),
		ClusterType:              types.StringNull(),
		CustomerManagedResources: types.ObjectNull(CustomerManagedResourcesAttrTypes()),
		ID:                       id,
		Name:                     types.StringNull(),
		Region:                   types.StringNull(),
		ResourceGroupID:          types.StringNull(),
		State:                    types.StringNull(),
		Timeouts:                 timeout,
		Zones:                    types.ListNull(types.StringType),
	}
}
