// Code generated by schemagen. DO NOT EDIT.

// Copyright 2023 Redpanda Data, Inc.
//
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

package pipeline

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/redpanda-data/terraform-provider-redpanda/redpanda/validators"
)

// ResourcePipelineSchema returns the Terraform schema for the pipeline resource.
func ResourcePipelineSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Description: "Pipeline represents a Redpanda Connect pipeline",
		Attributes: map[string]schema.Attribute{
			"cluster_api_url": schema.StringAttribute{
				Description:   "The cluster API URL. Changing this will prevent deletion of the resource on the existing cluster. It is generally a better idea to delete an existing resource and create a new one than to change this value unless you are planning to do state imports.",
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},

			"config_yaml": schema.StringAttribute{
				Description: "The Redpanda Connect pipeline configuration in YAML format. See the [Redpanda Connect Configuration](https://docs.redpanda.com/redpanda-cloud/develop/connect/configuration/about) documentation for more details.",
				Required:    true,
				Sensitive:   true,
			},

			"display_name": schema.StringAttribute{
				Description: "User-friendly pipeline name. Length must be between 3 and 128. Must match pattern `^[A-Za-z0-9-_ /]+$`.",
				Required:    true,
				Validators:  []validator.String{stringvalidator.LengthAtLeast(1)},
			},

			"description": schema.StringAttribute{
				Description: "Optional pipeline description. Length must be at most 256.",
				Optional:    true,
			},

			"service_account": schema.SingleNestedAttribute{
				Description:   "Service Account configuration",
				Optional:      true,
				PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
				Attributes: map[string]schema.Attribute{
					"client_id": schema.StringAttribute{
						Description: "Client ID",
						Required:    true,
					},
					"client_secret": schema.StringAttribute{
						Description: "Client Secret. Must match pattern `^\\$\\{secrets\\.[A-Za-z_][A-Za-z0-9_]*(\\.[A-Za-z_][A-Za-z0-9_]*)?\\}$`.",
						Required:    true,
						WriteOnly:   true,
					},
					"secret_version": schema.Int64Attribute{
						Description:   "Version number for client_secret. Increment to trigger a secret update.",
						Optional:      true,
						PlanModifiers: []planmodifier.Int64{int64planmodifier.UseStateForUnknown()},
					},
				},
			},

			"tags": schema.MapAttribute{
				Description: "Tags are key-value pairs that can be assigned to a pipeline resource. They help organize pipelines and enable filtering when listing them. Must have at most 16 entries.",
				Optional:    true,
				ElementType: types.StringType,
			},

			"allow_deletion": schema.BoolAttribute{
				Description: "Whether Terraform may destroy this resource. Defaults to false; set to true to enable destruction. After `terraform import`, defaults to false — set to true in your config before running `terraform destroy`.",
				Optional:    true,
				Computed:    true,
				Default:     booldefault.StaticBool(false),
			},

			"resources": schema.SingleNestedAttribute{
				Description:   "Resources configuration",
				Optional:      true,
				Computed:      true,
				PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
				Attributes: map[string]schema.Attribute{
					"cpu_shares": schema.StringAttribute{
						Description: "`cpu_shares` is a string specifying the amount of CPU to allocate for the pipeline. This follows the [Kubernetes quantity](https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/quantity/) format. Acceptable units include: - Decimal SI units: \"m\" (e.g., \"500m\" for 500 millicores, \"2\" for 2 cores) CPU shares can be specified in millicores (1 core = 1000 millicores). If you don't specify a unit, the value is interpreted as the number of cores.",
						Optional:    true,
						Validators:  []validator.String{validators.CPUSharesValidator{}},
					},
					"memory_shares": schema.StringAttribute{
						Description: "`memory_shares` is a string specifying the amount of memory to allocate for the pipeline. This follows the [Kubernetes quantity](https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/quantity/) format. Acceptable units include: - Decimal SI units: \"K\", \"M\", \"G\", \"T\", \"P\", \"E\" (e.g., \"128M\" for 128 megabytes) - Binary SI units: \"Ki\", \"Mi\", \"Gi\", \"Ti\", \"Pi\", \"Ei\" (e.g., \"512Mi\" for 512 mebibytes) If you don't specify a unit, the value is interpreted as bytes.",
						Optional:    true,
						Validators:  []validator.String{validators.MemorySharesValidator{}},
					},
				},
			},

			"state": schema.StringAttribute{
				Description: "Desired state of the pipeline: 'running' or 'stopped'. The provider will ensure the pipeline reaches this state after create/update operations.",
				Optional:    true,
				Computed:    true,
				Default:     stringdefault.StaticString("stopped"),
				Validators:  []validator.String{stringvalidator.OneOf("", "running", "stopped")},
			},

			"id": schema.StringAttribute{
				Description:   "Pipeline ID. Must match pattern `^[A-Za-z0-9-_/]+$`.",
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},

			"status": schema.SingleNestedAttribute{
				Description:   "Pipeline status may contain an error message.",
				Computed:      true,
				PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
				Attributes: map[string]schema.Attribute{
					"error": schema.StringAttribute{
						Description:   "Error",
						Computed:      true,
						PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
					},
				},
			},

			"url": schema.StringAttribute{
				Description:   "URL to connect to the pipeline, for example, via http_server. May be empty if no http_server is used.",
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},

			"timeouts": timeouts.Attributes(ctx, timeouts.Opts{
				Create: true,
				Update: true,
				Delete: true,
			}),
		},
	}
}
