// Code generated by go generate; DO NOT EDIT.
// Generated by: redpanda/utils/testutil/generator

package schema

import (
	"github.com/redpanda-data/terraform-provider-redpanda/redpanda/utils/compare"
)

// Compare performs comprehensive field-by-field comparison between two ResourceModel instances
func (m *ResourceModel) Compare(other *ResourceModel) []compare.FieldDiff {
	var diffs []compare.FieldDiff

	// String fields
	compare.Collect(&diffs, compare.String("subject", m.Subject, other.Subject))
	compare.Collect(&diffs, compare.String("schema", m.Schema, other.Schema))
	compare.Collect(&diffs, compare.String("schema_type", m.SchemaType, other.SchemaType))
	compare.Collect(&diffs, compare.String("cluster_id", m.ClusterID, other.ClusterID))
	compare.Collect(&diffs, compare.String("compatibility", m.Compatibility, other.Compatibility))
	compare.Collect(&diffs, compare.String("username", m.Username, other.Username))
	compare.Collect(&diffs, compare.String("password", m.Password, other.Password))

	// Bool fields
	compare.Collect(&diffs, compare.Bool("allow_deletion", m.AllowDeletion, other.AllowDeletion))

	// Int fields
	compare.Collect(&diffs, compare.Int64("version", m.Version, other.Version))
	compare.Collect(&diffs, compare.Int64("id", m.ID, other.ID))

	// List fields
	compare.Collect(&diffs, compare.List("references", m.References, other.References))

	return diffs
}

// Compare performs comprehensive field-by-field comparison between two DataModel instances
func (m *DataModel) Compare(other *DataModel) []compare.FieldDiff {
	var diffs []compare.FieldDiff

	// String fields
	compare.Collect(&diffs, compare.String("subject", m.Subject, other.Subject))
	compare.Collect(&diffs, compare.String("schema", m.Schema, other.Schema))
	compare.Collect(&diffs, compare.String("schema_type", m.SchemaType, other.SchemaType))
	compare.Collect(&diffs, compare.String("cluster_id", m.ClusterID, other.ClusterID))

	// Int fields
	compare.Collect(&diffs, compare.Int64("version", m.Version, other.Version))
	compare.Collect(&diffs, compare.Int64("id", m.ID, other.ID))

	// List fields
	compare.Collect(&diffs, compare.List("references", m.References, other.References))

	return diffs
}
