// Code generated by schemagen. DO NOT EDIT.

// Copyright 2023 Redpanda Data, Inc.
//
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

package acl

import (
	dataplanev1 "buf.build/gen/go/redpandadata/dataplane/protocolbuffers/go/redpanda/api/dataplane/v1"
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/redpanda-data/terraform-provider-redpanda/redpanda/utils"
	"github.com/redpanda-data/terraform-provider-redpanda/redpanda/utils/enums"
)

type ACLResponse interface {
	GetResourceName() string
	GetResourcePatternType() dataplanev1.ACL_ResourcePatternType
	GetResourceType() dataplanev1.ACL_ResourceType
}

// Flatten populates a *ResourceModel from the API response payload.
// The prev *ResourceModel arg carries forward TF-only / sensitive / write-only
// fields that the response cannot supply; pass nil when no prior state exists
// (e.g., during ImportState).
func Flatten(_ context.Context, proto ACLResponse, prev *ResourceModel) (*ResourceModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	m := &ResourceModel{}
	m.ResourceName = types.StringValue(proto.GetResourceName())
	m.ResourcePatternType = types.StringValue(enums.ACLResourcePatternTypeToString(proto.GetResourcePatternType()))
	m.ResourceType = types.StringValue(enums.ACLResourceTypeToString(proto.GetResourceType()))
	if prev != nil && !prev.ClusterAPIURL.IsUnknown() {
		m.ClusterAPIURL = prev.ClusterAPIURL
	} else {
		m.ClusterAPIURL = types.StringNull()
	}
	if prev != nil && !prev.Host.IsUnknown() {
		m.Host = prev.Host
	} else {
		m.Host = types.StringNull()
	}
	if prev != nil && !prev.Operation.IsUnknown() {
		m.Operation = prev.Operation
	} else {
		m.Operation = types.StringNull()
	}
	if prev != nil && !prev.PermissionType.IsUnknown() {
		m.PermissionType = prev.PermissionType
	} else {
		m.PermissionType = types.StringNull()
	}
	if prev != nil && !prev.Principal.IsUnknown() {
		m.Principal = prev.Principal
	} else {
		m.Principal = types.StringNull()
	}
	if prev != nil && !prev.AllowDeletion.IsUnknown() {
		m.AllowDeletion = prev.AllowDeletion
	} else {
		m.AllowDeletion = types.BoolNull()
	}
	if prev != nil && !prev.ID.IsUnknown() {
		m.ID = prev.ID
	} else {
		m.ID = types.StringNull()
	}
	if m.AllowDeletion.IsNull() || m.AllowDeletion.IsUnknown() {
		m.AllowDeletion = types.BoolValue(false)
	}
	return m, diags
}

// ExpandCreate renders a *ResourceModel into the proto request envelope for
// the corresponding RPC.
func ExpandCreate(_ context.Context, m *ResourceModel) (*dataplanev1.CreateACLRequest, diag.Diagnostics) {
	var diags diag.Diagnostics
	req := &dataplanev1.CreateACLRequest{
		ResourceType:        enums.StringToACLResourceType(m.ResourceType.ValueString()),
		ResourceName:        m.ResourceName.ValueString(),
		ResourcePatternType: enums.StringToACLResourcePatternType(m.ResourcePatternType.ValueString()),
		Principal:           m.Principal.ValueString(),
		Host:                m.Host.ValueString(),
		Operation:           enums.StringToACLOperation(m.Operation.ValueString()),
		PermissionType:      enums.StringToACLPermissionType(m.PermissionType.ValueString()),
	}
	return req, diags
}

// ExpandDelete renders a *ResourceModel into the proto request envelope for
// the corresponding RPC.
func ExpandDelete(_ context.Context, m *ResourceModel) (*dataplanev1.DeleteACLsRequest, diag.Diagnostics) {
	var diags diag.Diagnostics
	payload := &dataplanev1.DeleteACLsRequest_Filter{
		Host:                utils.PointerOrNil(m.Host, types.String.ValueString),
		Operation:           enums.StringToACLOperation(m.Operation.ValueString()),
		PermissionType:      enums.StringToACLPermissionType(m.PermissionType.ValueString()),
		Principal:           utils.PointerOrNil(m.Principal, types.String.ValueString),
		ResourceName:        utils.PointerOrNil(m.ResourceName, types.String.ValueString),
		ResourcePatternType: enums.StringToACLResourcePatternType(m.ResourcePatternType.ValueString()),
		ResourceType:        enums.StringToACLResourceType(m.ResourceType.ValueString()),
	}
	req := &dataplanev1.DeleteACLsRequest{
		Filter: payload,
	}
	return req, diags
}
