// Code generated by schemagen. DO NOT EDIT.

// Copyright 2023 Redpanda Data, Inc.
//
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

package shadowlink

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-validators/boolvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int32planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// ResourceShadowLinkSchema returns the Terraform schema for the shadowlink resource.
func ResourceShadowLinkSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Description: "ShadowLink configures asynchronous data replication from a source Redpanda cluster to a shadow (destination) cluster. The link is configuration on the shadow cluster — no infrastructure is provisioned. Each broker in the shadow cluster runs internal replication tasks that pull from the source over the standard Kafka API. The shadow cluster must have `enable_shadow_linking=true` set in its `cluster_configuration.custom_properties_json`.",
		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				Description:   "Human-readable name for the shadow link. Must be unique. Must follow Kubernetes DNS-1123 subdomain naming convention: - lowercase alphanumeric characters, hyphens allowed - must start and end with alphanumeric character - maximum 63 characters. Length must be at most 63. Must match pattern `^[a-z0-9]([-a-z0-9]*[a-z0-9])?$`.",
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},

			"shadow_redpanda_id": schema.StringAttribute{
				Description:   "Shadow Redpanda cluster ID where the shadow link is created. This ID is immutable.",
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},

			"source_redpanda_id": schema.StringAttribute{
				Description:   "Source Redpanda ID",
				Optional:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},

			"allow_deletion": schema.BoolAttribute{
				Description: "Allows deletion of the shadow link. Defaults to false.",
				Optional:    true,
				Computed:    true,
				Default:     booldefault.StaticBool(false),
			},

			"client_options": schema.SingleNestedAttribute{
				Description:   "ShadowLinkClientOptions configures the Kafka client connection settings.",
				Optional:      true,
				Computed:      true,
				PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
				Attributes: map[string]schema.Attribute{
					"authentication_configuration": schema.SingleNestedAttribute{
						Description:   "Authentication config. Supports: * SASL/SCRAM * SASL/PLAIN",
						Optional:      true,
						Computed:      true,
						PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
						Attributes: map[string]schema.Attribute{
							"plain_configuration": schema.SingleNestedAttribute{
								Description:   "PLAIN settings",
								Optional:      true,
								Computed:      true,
								PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
								Attributes: map[string]schema.Attribute{
									"password": schema.StringAttribute{
										Description:   "Password",
										Optional:      true,
										Computed:      true,
										Sensitive:     true,
										PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
									},
									"username": schema.StringAttribute{
										Description:   "PLAIN username",
										Optional:      true,
										Computed:      true,
										PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
									},
									"password_set": schema.BoolAttribute{
										Description:   "Indicates that the password has been set",
										Computed:      true,
										PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseNonNullStateForUnknown()},
									},
								},
							},
							"scram_configuration": schema.SingleNestedAttribute{
								Description:   "SCRAM settings",
								Optional:      true,
								Computed:      true,
								PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
								Attributes: map[string]schema.Attribute{
									"password": schema.StringAttribute{
										Description:   "Password",
										Optional:      true,
										Computed:      true,
										Sensitive:     true,
										PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
									},
									"scram_mechanism": schema.StringAttribute{
										Description:   "- SCRAM_MECHANISM_SCRAM_SHA_256: SCRAM-SHA-256 - SCRAM_MECHANISM_SCRAM_SHA_512: SCRAM-SHA-512",
										Optional:      true,
										Computed:      true,
										PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
									},
									"username": schema.StringAttribute{
										Description:   "SCRAM username",
										Optional:      true,
										Computed:      true,
										PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
									},
									"password_set": schema.BoolAttribute{
										Description:   "Indicates that the password has been set",
										Computed:      true,
										PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseNonNullStateForUnknown()},
									},
								},
							},
						},
					},
					"bootstrap_servers": schema.ListAttribute{
						Description:   "Bootstrap servers for the source cluster. Required if source Redpanda ID is not provided.",
						Optional:      true,
						Computed:      true,
						PlanModifiers: []planmodifier.List{listplanmodifier.UseStateForUnknown()},
						ElementType:   types.StringType,
					},
					"connection_timeout_ms": schema.Int32Attribute{
						Description:   "Connection timeout in milliseconds (defaults to 1000ms if 0).",
						Optional:      true,
						Computed:      true,
						PlanModifiers: []planmodifier.Int32{int32planmodifier.UseStateForUnknown()},
					},
					"fetch_max_bytes": schema.Int32Attribute{
						Description:   "Maximum bytes to fetch (defaults to 20971520 bytes / 20 MiB if 0).",
						Optional:      true,
						Computed:      true,
						PlanModifiers: []planmodifier.Int32{int32planmodifier.UseStateForUnknown()},
					},
					"fetch_min_bytes": schema.Int32Attribute{
						Description:   "Minimum bytes to fetch (defaults to 5242880 bytes / 5 MiB if 0).",
						Optional:      true,
						Computed:      true,
						PlanModifiers: []planmodifier.Int32{int32planmodifier.UseStateForUnknown()},
					},
					"fetch_partition_max_bytes": schema.Int32Attribute{
						Description:   "Maximum bytes per partition to fetch (defaults to 1048576 bytes / 1 MiB if 0).",
						Optional:      true,
						Computed:      true,
						PlanModifiers: []planmodifier.Int32{int32planmodifier.UseStateForUnknown()},
					},
					"fetch_wait_max_ms": schema.Int32Attribute{
						Description:   "Maximum time to wait for fetch requests in milliseconds (defaults to 500ms if 0).",
						Optional:      true,
						Computed:      true,
						PlanModifiers: []planmodifier.Int32{int32planmodifier.UseStateForUnknown()},
					},
					"metadata_max_age_ms": schema.Int32Attribute{
						Description:   "Metadata refresh interval in milliseconds (defaults to 10000ms if 0).",
						Optional:      true,
						Computed:      true,
						PlanModifiers: []planmodifier.Int32{int32planmodifier.UseStateForUnknown()},
					},
					"retry_backoff_ms": schema.Int32Attribute{
						Description:   "Retry backoff in milliseconds (defaults to 100ms if 0).",
						Optional:      true,
						Computed:      true,
						PlanModifiers: []planmodifier.Int32{int32planmodifier.UseStateForUnknown()},
					},
					"source_cluster_id": schema.StringAttribute{
						Description:   "Source cluster ID.",
						Optional:      true,
						Computed:      true,
						PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
					},
					"tls_settings": schema.SingleNestedAttribute{
						Description:   "TLSSettings configures TLS encryption.",
						Optional:      true,
						Computed:      true,
						PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
						Attributes: map[string]schema.Attribute{
							"ca": schema.StringAttribute{
								Description:   "The CA certificate for TLS.",
								Optional:      true,
								Computed:      true,
								PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
							},
							"cert": schema.StringAttribute{
								Description:   "Cert is the certificate for TLS. Key and Cert are optional but if one is provided, then both must be provided.",
								Optional:      true,
								Computed:      true,
								PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
							},
							"do_not_set_sni_hostname": schema.BoolAttribute{
								Description:   "Do not set SNI hostname.",
								Optional:      true,
								Computed:      true,
								PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
							},
							"enabled": schema.BoolAttribute{
								Description:   "Enable TLS.",
								Optional:      true,
								Computed:      true,
								PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
							},
							"key": schema.StringAttribute{
								Description:   "The private key for TLS. Key and Cert are optional but if one is provided, then both must be provided.",
								Optional:      true,
								Computed:      true,
								Sensitive:     true,
								PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
							},
						},
					},
					"client_id": schema.StringAttribute{
						Description:   "Client ID for the connection.",
						Computed:      true,
						PlanModifiers: []planmodifier.String{stringplanmodifier.UseNonNullStateForUnknown()},
					},
					"effective_connection_timeout_ms": schema.Int32Attribute{
						Description:   "The effective connection timeout in milliseconds",
						Computed:      true,
						PlanModifiers: []planmodifier.Int32{int32planmodifier.UseNonNullStateForUnknown()},
					},
					"effective_fetch_max_bytes": schema.Int32Attribute{
						Description:   "The effective fetch max bytes",
						Computed:      true,
						PlanModifiers: []planmodifier.Int32{int32planmodifier.UseNonNullStateForUnknown()},
					},
					"effective_fetch_min_bytes": schema.Int32Attribute{
						Description:   "The effective fetch min bytes",
						Computed:      true,
						PlanModifiers: []planmodifier.Int32{int32planmodifier.UseNonNullStateForUnknown()},
					},
					"effective_fetch_partition_max_bytes": schema.Int32Attribute{
						Description:   "The effective fetch partition max bytes",
						Computed:      true,
						PlanModifiers: []planmodifier.Int32{int32planmodifier.UseNonNullStateForUnknown()},
					},
					"effective_fetch_wait_max_ms": schema.Int32Attribute{
						Description:   "The effective fetch wait max in milliseconds",
						Computed:      true,
						PlanModifiers: []planmodifier.Int32{int32planmodifier.UseNonNullStateForUnknown()},
					},
					"effective_metadata_max_age_ms": schema.Int32Attribute{
						Description:   "The effective metadata max age in milliseconds",
						Computed:      true,
						PlanModifiers: []planmodifier.Int32{int32planmodifier.UseNonNullStateForUnknown()},
					},
					"effective_retry_backoff_ms": schema.Int32Attribute{
						Description:   "The effective retry backoff in milliseconds",
						Computed:      true,
						PlanModifiers: []planmodifier.Int32{int32planmodifier.UseNonNullStateForUnknown()},
					},
				},
			},

			"consumer_offset_sync_options": schema.SingleNestedAttribute{
				Description:   "Options for syncing consumer offsets",
				Optional:      true,
				Computed:      true,
				PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
				Attributes: map[string]schema.Attribute{
					"group_filters": schema.ListNestedAttribute{
						Description:   "The filters",
						Optional:      true,
						Computed:      true,
						PlanModifiers: []planmodifier.List{listplanmodifier.UseStateForUnknown()},
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"filter_type": schema.StringAttribute{
									Description: "- FILTER_TYPE_INCLUDE: Include the items that match the filter - FILTER_TYPE_EXCLUDE: Exclude the items that match the filter",
									Required:    true,
								},
								"name": schema.StringAttribute{
									Description: "The resource name, or \"*\" Note if \"*\", must be the _only_ character and `pattern_type` must be `PATTERN_TYPE_LITERAL`",
									Required:    true,
								},
								"pattern_type": schema.StringAttribute{
									Description: "- PATTERN_TYPE_LITERAL: Must match the filter exactly - PATTERN_TYPE_PREFIX: Will match anything that starts with filter - PATTERN_TYPE_PREFIXED: Will match anything that starts with filter",
									Required:    true,
								},
							},
						},
					},
					"interval": schema.StringAttribute{
						Description:   "Sync interval If 0 provided, defaults to 30 seconds",
						Optional:      true,
						Computed:      true,
						PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
					},
					"paused": schema.BoolAttribute{
						Description:   "Allows user to pause the consumer offset sync task. If paused, then the task will enter the 'paused' state and not sync consumer offsets from the source cluster",
						Optional:      true,
						Computed:      true,
						PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
					},
				},
			},

			"schema_registry_sync_options": schema.SingleNestedAttribute{
				Description:   "Options for how the Schema Registry is synced.",
				Optional:      true,
				Computed:      true,
				PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
				Attributes: map[string]schema.Attribute{
					"shadow_schema_registry_topic": schema.BoolAttribute{
						Description:   "Shadow the entire source cluster's Schema Registry byte-for-byte. If set, the Shadow Link will attempt to add the `_schemas` topic to the list of Shadow Topics as long as: 1. The `_schemas` topic exists on the source cluster 2. The `_schemas` topic does not exist on the shadow cluster, or it is empty. If either of the above conditions are _not_ met, then the `_schemas` topic will _not_ be shadowed by this cluster. Unsetting this flag will _not_ remove the `_schemas` topic from shadowing if it has already been added. Once made a shadow topic, the `_schemas` topic will be replicated byte-for-byte. To stop shadowing the `_schemas` topic, unset this field, then either fail-over the topic or delete it.",
						Optional:      true,
						Computed:      true,
						PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
						Validators:    []validator.Bool{boolvalidator.Equals(true)},
					},
				},
			},

			"security_sync_options": schema.SingleNestedAttribute{
				Description:   "Options for syncing security settings",
				Optional:      true,
				Computed:      true,
				PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
				Attributes: map[string]schema.Attribute{
					"acl_filters": schema.ListNestedAttribute{
						Description:   "ACL filters",
						Optional:      true,
						Computed:      true,
						PlanModifiers: []planmodifier.List{listplanmodifier.UseStateForUnknown()},
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"access_filter": schema.SingleNestedAttribute{
									Description: "Filter an ACL based on its access",
									Required:    true,
									Attributes: map[string]schema.Attribute{
										"operation": schema.StringAttribute{
											Description: "The ACL operation to match",
											Required:    true,
										},
										"permission_type": schema.StringAttribute{
											Description: "ACL permission types",
											Required:    true,
										},
										"host": schema.StringAttribute{
											Description:   "The host to match. If not set, will default to match all hosts with the specified `operation` and `permission_type`. Note that the asterisk `*` is literal and matches hosts that are set to `*`",
											Optional:      true,
											Computed:      true,
											PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
										},
										"principal": schema.StringAttribute{
											Description:   "The name of the principal, if not set will default to match all principals with the specified `operation` and `permission_type`",
											Optional:      true,
											Computed:      true,
											PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
										},
									},
								},
								"resource_filter": schema.SingleNestedAttribute{
									Description: "A filter to match ACLs for resources",
									Required:    true,
									Attributes: map[string]schema.Attribute{
										"pattern_type": schema.StringAttribute{
											Description: "- ACL_PATTERN_ANY: Wildcard to match any pattern - ACL_PATTERN_LITERAL: Match a literal string - ACL_PATTERN_PREFIXED: Match a prefix - ACL_PATTERN_PREFIX: Match a prefix - ACL_PATTERN_MATCH: Match serves as a catch-all for all the names of a topic the principal is authorized to access",
											Required:    true,
										},
										"resource_type": schema.StringAttribute{
											Description: "- ACL_RESOURCE_ANY: Wildcard for selecting any ACL resource - ACL_RESOURCE_CLUSTER: Cluster wide resource - ACL_RESOURCE_GROUP: Consumer group resource - ACL_RESOURCE_TOPIC: Topic resource - ACL_RESOURCE_TXN_ID: Transaction ID resource - ACL_RESOURCE_SR_SUBJECT: Schema Registry subject resource - ACL_RESOURCE_SR_REGISTRY: Schema Registry wide resource - ACL_RESOURCE_SR_ANY: Wildcard to match any SR ACL resource",
											Required:    true,
										},
										"name": schema.StringAttribute{
											Description:   "Name, if not given will default to match all items in `resource_type`. Note that asterisk `*` is literal and matches resource ACLs that are named `*`",
											Optional:      true,
											Computed:      true,
											PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
										},
									},
								},
							},
						},
					},
					"interval": schema.StringAttribute{
						Description:   "Sync interval If 0 provided, defaults to 30 seconds",
						Optional:      true,
						Computed:      true,
						PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
					},
					"paused": schema.BoolAttribute{
						Description:   "Allows user to pause the security settings sync task. If paused, then the task will enter the 'paused' state and will not sync security settings from the source cluster",
						Optional:      true,
						Computed:      true,
						PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
					},
				},
			},

			"topic_metadata_sync_options": schema.SingleNestedAttribute{
				Description:   "Options for syncing topic metadata",
				Optional:      true,
				Computed:      true,
				PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
				Attributes: map[string]schema.Attribute{
					"auto_create_shadow_topic_filters": schema.ListNestedAttribute{
						Description:   "List of filters that indicate which topics should be automatically created as shadow topics on the shadow cluster. This only controls automatic creation of shadow topics and does not effect the state of the mirror topic once it is created. Literal filters for __consumer_offsets, _redpanda.audit_log and _schemas will be rejected as well as prefix filters to match topics prefixed with _redpanda or __redpanda. Wildcard `*` is permitted only for literal filters and will _not_ match any topics that start with _redpanda or __redpanda. If users wish to shadow topics that start with _redpanda or __redpanda, they should provide a literal filter for those topics.",
						Optional:      true,
						Computed:      true,
						PlanModifiers: []planmodifier.List{listplanmodifier.UseStateForUnknown()},
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"filter_type": schema.StringAttribute{
									Description: "- FILTER_TYPE_INCLUDE: Include the items that match the filter - FILTER_TYPE_EXCLUDE: Exclude the items that match the filter",
									Required:    true,
								},
								"name": schema.StringAttribute{
									Description: "The resource name, or \"*\" Note if \"*\", must be the _only_ character and `pattern_type` must be `PATTERN_TYPE_LITERAL`",
									Required:    true,
								},
								"pattern_type": schema.StringAttribute{
									Description: "- PATTERN_TYPE_LITERAL: Must match the filter exactly - PATTERN_TYPE_PREFIX: Will match anything that starts with filter - PATTERN_TYPE_PREFIXED: Will match anything that starts with filter",
									Required:    true,
								},
							},
						},
					},
					"exclude_default": schema.BoolAttribute{
						Description:   "If this is true, then only the properties listed in `synced_shadow_topic_properties` will be synced.",
						Optional:      true,
						Computed:      true,
						PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
					},
					"interval": schema.StringAttribute{
						Description:   "How often to sync metadata If 0 provided, defaults to 30 seconds",
						Optional:      true,
						Computed:      true,
						PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
					},
					"paused": schema.BoolAttribute{
						Description:   "Allows user to pause the topic sync task. If paused, then the task will enter the 'paused' state and not sync topics or their properties from the source cluster",
						Optional:      true,
						Computed:      true,
						PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
					},
					"start_at_earliest": schema.BoolAttribute{
						Description:   "Start at the earliest offset in the partition.",
						Optional:      true,
						Computed:      true,
						PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
						Validators:    []validator.Bool{boolvalidator.Equals(true)},
					},
					"start_at_latest": schema.BoolAttribute{
						Description:   "Start at the latest offset in the partition.",
						Optional:      true,
						Computed:      true,
						PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
						Validators:    []validator.Bool{boolvalidator.Equals(true)},
					},
					"start_at_timestamp": schema.StringAttribute{
						Description:   "Enables data replication from the first offset on the source topic/partition where the record's timestamp is at or after the specified timestamp.",
						Optional:      true,
						Computed:      true,
						PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
					},
					"synced_shadow_topic_properties": schema.ListAttribute{
						Description:   "The following properties are not allowed to be replicated and adding them to this list will result in an error: - `redpanda.remote.readreplica` - `redpanda.remote.recovery` - `redpanda.remote.allowgaps` - `redpanda.virtual.cluster.id` - `redpanda.leaders.preference` - `redpanda.storage.mode` This list is a list of properties in addition to the default properties that will be synced. See `exclude_default`.",
						Optional:      true,
						Computed:      true,
						PlanModifiers: []planmodifier.List{listplanmodifier.UseStateForUnknown()},
						ElementType:   types.StringType,
					},
				},
			},

			"id": schema.StringAttribute{
				Description:   "Shadow link ID.",
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},

			"reason": schema.StringAttribute{
				Description:   "Reason provides additional context for the current state.",
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},

			"state": schema.StringAttribute{
				Description:   "State represents the lifecycle state of a shadow link.",
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},

			"timeouts": timeouts.Attributes(ctx, timeouts.Opts{
				Create: true,
				Update: true,
				Delete: true,
			}),
		},
	}
}
