// Code generated by schemagen. DO NOT EDIT.

// Copyright 2023 Redpanda Data, Inc.
//
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

package serverlesscluster

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// DatasourceServerlessClusterSchema returns the Terraform schema for the serverlesscluster datasource.
func DatasourceServerlessClusterSchema(_ context.Context) schema.Schema {
	return schema.Schema{
		Description: "Data source for a Redpanda Cloud serverless cluster",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "The ID of the serverless cluster",
				Required:    true,
			},

			"cluster_api_url": schema.StringAttribute{
				Description: "The URL of the dataplane API for the serverless cluster",
				Computed:    true,
			},

			"console_private_url": schema.StringAttribute{
				Description: "Private Console URL",
				Computed:    true,
			},

			"console_url": schema.StringAttribute{
				Description: "Public Console URL",
				Computed:    true,
			},

			"dataplane_api": schema.SingleNestedAttribute{
				Description: "Cluster's Data Plane API properties.",
				Computed:    true,
				Attributes: map[string]schema.Attribute{
					"private_url": schema.StringAttribute{
						Description: "Private Dataplane API URL",
						Computed:    true,
					},
					"url": schema.StringAttribute{
						Description: "Public Dataplane API URL",
						Computed:    true,
					},
				},
			},

			"kafka_api": schema.SingleNestedAttribute{
				Description: "Cluster's Kafka API properties.",
				Computed:    true,
				Attributes: map[string]schema.Attribute{
					"private_seed_brokers": schema.ListAttribute{
						Description: "Private Kafka API seed brokers",
						Computed:    true,
						ElementType: types.StringType,
					},
					"seed_brokers": schema.ListAttribute{
						Description: "Public Kafka API seed brokers",
						Computed:    true,
						ElementType: types.StringType,
					},
				},
			},

			"name": schema.StringAttribute{
				Description: "Name of the serverless cluster",
				Computed:    true,
			},

			"networking_config": schema.SingleNestedAttribute{
				Description: "Networking Config configuration",
				Computed:    true,
				Attributes: map[string]schema.Attribute{
					"private": schema.StringAttribute{
						Description: "Private network state",
						Computed:    true,
					},
					"public": schema.StringAttribute{
						Description: "Public network state",
						Computed:    true,
					},
				},
			},

			"planned_deletion": schema.SingleNestedAttribute{
				Description: "Planned deletion information",
				Computed:    true,
				Attributes: map[string]schema.Attribute{
					"delete_after": schema.StringAttribute{
						Description: "Delete After",
						Computed:    true,
					},
					"reason": schema.StringAttribute{
						Description: "Reason",
						Computed:    true,
					},
				},
			},

			"private_link_id": schema.StringAttribute{
				Description: "Private link ID for the serverless cluster, if any",
				Computed:    true,
			},

			"prometheus": schema.SingleNestedAttribute{
				Description: "Prometheus metrics endpoint properties.",
				Computed:    true,
				Attributes: map[string]schema.Attribute{
					"private_url": schema.StringAttribute{
						Description: "Private Prometheus metrics URL",
						Computed:    true,
					},
					"url": schema.StringAttribute{
						Description: "Public Prometheus metrics URL",
						Computed:    true,
					},
				},
			},

			"resource_group_id": schema.StringAttribute{
				Description: "The ID of the resource group in which to create the serverless cluster",
				Computed:    true,
			},

			"schema_registry": schema.SingleNestedAttribute{
				Description: "Cluster's Schema Registry properties.",
				Computed:    true,
				Attributes: map[string]schema.Attribute{
					"private_url": schema.StringAttribute{
						Description: "Private Schema Registry URL",
						Computed:    true,
					},
					"url": schema.StringAttribute{
						Description: "Public Schema Registry URL",
						Computed:    true,
					},
				},
			},

			"serverless_region": schema.StringAttribute{
				Description: "Redpanda specific region for the serverless cluster",
				Computed:    true,
			},

			"state": schema.StringAttribute{
				Description: "Current state of the serverless cluster.",
				Computed:    true,
			},

			"tags": schema.MapAttribute{
				Description: "User-defined tags on the cluster",
				Computed:    true,
				ElementType: types.StringType,
			},
		},
	}
}
