// Copyright 2023 Redpanda Data, Inc.
//
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

package schemagen

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"
	"text/template"
)

// LicenseHeader returns the standard license header for generated files.
func LicenseHeader() string { return licenseHeader }

const licenseHeader = `// Copyright 2023 Redpanda Data, Inc.
//
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

`

const schemaTmpl = `// Code generated by schemagen. DO NOT EDIT.

{{.License}}package {{.Package}}

import (
{{- range .Imports}}
	"{{.}}"
{{- end}}
)

// {{.FuncName}} returns the Terraform schema for the {{.Package}} {{.SchemaType}}.
func {{.FuncName}}({{if .NeedsContext}}ctx context.Context{{else}}_ context.Context{{end}}) schema.Schema {
	return schema.Schema{
		Description: {{printf "%q" .Description}},
		Attributes: map[string]schema.Attribute{
{{- range .Attributes}}
{{renderAttr . 3}}
{{- end}}
{{- if .HasTimeouts}}
{{- if .IsDatasource}}
			"timeouts": timeouts.Attributes({{if .NeedsContext}}ctx{{end}}),
{{- else}}
			"timeouts": timeouts.Attributes({{if .NeedsContext}}ctx, {{end}}timeouts.Opts{
{{- if .TimeoutsCreate}}
				Create: true,
{{- end}}
{{- if .TimeoutsRead}}
				Read: true,
{{- end}}
{{- if .TimeoutsUpdate}}
				Update: true,
{{- end}}
{{- if .TimeoutsDelete}}
				Delete: true,
{{- end}}
			}),
{{- end}}
{{- end}}
		},
{{- if .Version}}
		Version: {{.Version}},
{{- end}}
	}
}
`

// TemplateData holds all data needed to render the schema template.
type TemplateData struct {
	License        string
	Package        string
	FuncName       string
	SchemaType     string
	Description    string
	NeedsContext   bool
	Imports        []string
	Attributes     []SchemaAttr
	HasTimeouts    bool
	IsDatasource   bool
	TimeoutsCreate bool
	TimeoutsRead   bool
	TimeoutsUpdate bool
	TimeoutsDelete bool
	Version        int64
}

// Generate produces formatted Go source code for a schema file.
func Generate(data TemplateData) ([]byte, error) {
	funcMap := template.FuncMap{
		"renderAttr": renderAttr,
	}

	tmpl, err := template.New("schema").Funcs(funcMap).Parse(schemaTmpl)
	if err != nil {
		return nil, fmt.Errorf("failed to parse schema template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("failed to execute schema template: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return buf.Bytes(), fmt.Errorf("failed to format generated code: %w\n%s", err, buf.String())
	}

	return formatted, nil
}

// ResolveImports determines the required imports from the schema attributes
// and configuration.
func ResolveImports(attrs []SchemaAttr, schemaType string, hasTimeouts bool, extraImports []string) []string {
	needed := make(map[string]bool)

	needed["context"] = true
	if schemaType == SchemaTypeDatasource {
		needed["github.com/hashicorp/terraform-plugin-framework/datasource/schema"] = true
	} else {
		needed["github.com/hashicorp/terraform-plugin-framework/resource/schema"] = true
	}

	scanImports(attrs, needed, schemaType)

	if hasTimeouts {
		if schemaType == SchemaTypeDatasource {
			needed["github.com/hashicorp/terraform-plugin-framework-timeouts/datasource/timeouts"] = true
		} else {
			needed["github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"] = true
		}
	}

	for _, imp := range extraImports {
		needed[imp] = true
	}

	imports := make([]string, 0, len(needed))
	for imp := range needed {
		imports = append(imports, imp)
	}
	sort.Strings(imports)
	return imports
}

func scanImports(attrs []SchemaAttr, needed map[string]bool, schemaType string) {
	for i := range attrs {
		attr := &attrs[i]
		if attr.ElementType != "" {
			needed["github.com/hashicorp/terraform-plugin-framework/types"] = true
		}
		for _, expr := range []string{attr.PlanModifiers, attr.Validators, attr.Default} {
			if expr == "" {
				continue
			}
			scanExprImports(expr, needed, schemaType)
		}
		scanImports(attr.NestedAttrs, needed, schemaType)
	}
}

var importPrefixes = map[string]string{
	"planmodifier.":        "github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier",
	"stringplanmodifier.":  "github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier",
	"boolplanmodifier.":    "github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier",
	"int32planmodifier.":   "github.com/hashicorp/terraform-plugin-framework/resource/schema/int32planmodifier",
	"int64planmodifier.":   "github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier",
	"float64planmodifier.": "github.com/hashicorp/terraform-plugin-framework/resource/schema/float64planmodifier",
	"numberplanmodifier.":  "github.com/hashicorp/terraform-plugin-framework/resource/schema/numberplanmodifier",
	"listplanmodifier.":    "github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier",
	"setplanmodifier.":     "github.com/hashicorp/terraform-plugin-framework/resource/schema/setplanmodifier",
	"mapplanmodifier.":     "github.com/hashicorp/terraform-plugin-framework/resource/schema/mapplanmodifier",
	"objectplanmodifier.":  "github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier",
	"booldefault.":         "github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault",
	"stringdefault.":       "github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault",
	"int32default.":        "github.com/hashicorp/terraform-plugin-framework/resource/schema/int32default",
	"int64default.":        "github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default",
	"float64default.":      "github.com/hashicorp/terraform-plugin-framework/resource/schema/float64default",
	"validator.":           "github.com/hashicorp/terraform-plugin-framework/schema/validator",
	"stringvalidator.":     "github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator",
	"listvalidator.":       "github.com/hashicorp/terraform-plugin-framework-validators/listvalidator",
	"types.":               "github.com/hashicorp/terraform-plugin-framework/types",
	"path.":                "github.com/hashicorp/terraform-plugin-framework/path",
	"validators.":          "github.com/redpanda-data/terraform-provider-redpanda/redpanda/validators",
}

func scanExprImports(expr string, needed map[string]bool, _ string) {
	for prefix, importPath := range importPrefixes {
		if strings.Contains(expr, prefix) {
			needed[importPath] = true
		}
	}
}

func renderAttr(attr SchemaAttr, indent int) string {
	prefix := strings.Repeat("\t", indent)
	inner := prefix + "\t"
	var b strings.Builder

	fmt.Fprintf(&b, "%s%q: schema.%s{\n", prefix, attr.Name, attr.AttrType)

	if attr.Description != "" {
		fmt.Fprintf(&b, "%sDescription: %q,\n", inner, attr.Description)
	}
	if attr.Required {
		fmt.Fprintf(&b, "%sRequired: true,\n", inner)
	}
	if attr.Optional {
		fmt.Fprintf(&b, "%sOptional: true,\n", inner)
	}
	if attr.Computed {
		fmt.Fprintf(&b, "%sComputed: true,\n", inner)
	}
	if attr.Sensitive {
		fmt.Fprintf(&b, "%sSensitive: true,\n", inner)
	}
	if attr.WriteOnly {
		fmt.Fprintf(&b, "%sWriteOnly: true,\n", inner)
	}
	if attr.DeprecationMessage != "" {
		fmt.Fprintf(&b, "%sDeprecationMessage: %q,\n", inner, attr.DeprecationMessage)
	}
	if attr.Default != "" {
		fmt.Fprintf(&b, "%sDefault: %s,\n", inner, attr.Default)
	}
	if attr.PlanModifiers != "" {
		fmt.Fprintf(&b, "%sPlanModifiers: %s,\n", inner, attr.PlanModifiers)
	}
	if attr.Validators != "" {
		fmt.Fprintf(&b, "%sValidators: %s,\n", inner, attr.Validators)
	}
	if attr.ElementType != "" {
		fmt.Fprintf(&b, "%sElementType: %s,\n", inner, attr.ElementType)
	}

	if len(attr.NestedAttrs) > 0 {
		switch attr.AttrType {
		case AttrTypeListNested, AttrTypeSetNested, AttrTypeMapNested:
			fmt.Fprintf(&b, "%sNestedObject: schema.NestedAttributeObject{\n", inner)
			fmt.Fprintf(&b, "%s\tAttributes: map[string]schema.Attribute{\n", inner)
			for i := range attr.NestedAttrs {
				b.WriteString(renderAttr(attr.NestedAttrs[i], indent+3))
			}
			fmt.Fprintf(&b, "%s\t},\n", inner)
			fmt.Fprintf(&b, "%s},\n", inner)
		default:
			fmt.Fprintf(&b, "%sAttributes: map[string]schema.Attribute{\n", inner)
			for i := range attr.NestedAttrs {
				b.WriteString(renderAttr(attr.NestedAttrs[i], indent+2))
			}
			fmt.Fprintf(&b, "%s},\n", inner)
		}
	}

	fmt.Fprintf(&b, "%s},\n", prefix)
	return b.String()
}
