// Copyright 2023 Redpanda Data, Inc.
//
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

package schemagen

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"
	"text/template"
	"unicode"
)

// ModelData is the template input for the resource/data-source model file.
type ModelData struct {
	License      string
	Package      string
	TypeName     string
	ResourceName string
	SchemaType   string
	Imports      []string
	Fields       []ModelField
	HasTimeouts  bool
	NestedTypes  []NestedType
	Converters   []Converter
	HasNested    bool

	// SubConverters emits free-standing Decode*/ToObject helpers for nested
	// types that are NOT at the root level. Required by NestedPreserveSubBlock
	// in the conv_gen template so that 2-level-deep sensitive fields can be
	// restored from prev-state.
	SubConverters []SubConverter

	EmitMinimal    bool
	MinimalAssigns []MinimalAssign
	IDFieldType    string
	HasTimeoutsArg bool
}

// SubConverter generates a free-standing Decode*/ToObject pair for a nested
// type whose parent is NOT the root model struct. Used by NestedPreserveSubBlock.
type SubConverter struct {
	// DecodeFuncName is the name of the decode function, e.g. "DecodeClientOptionsTLSSettings".
	DecodeFuncName string

	// ToObjectFuncName is the ToObject encode function, e.g. "ClientOptionsTLSSettingsToObject".
	ToObjectFuncName string

	// ParentType is the Go type of the parent struct, e.g. "ClientOptionsModel".
	ParentType string

	// FieldName is the Go field on the parent that holds the sub-type, e.g. "TLSSettings".
	FieldName string

	// NestedType is the Go type of the nested struct, e.g. "ClientOptionsTLSSettingsModel".
	NestedType string

	// AttrTypesFunc is the AttrTypes helper function, e.g. "ClientOptionsTLSSettingsAttrTypes".
	AttrTypesFunc string
}

// ModelField is a single struct field on the generated model.
type ModelField struct {
	Name string
	Type string
	Tag  string
}

// MinimalAssign is one field's RHS in GenerateMinimalResourceModel — either
// the id parameter, the timeouts parameter, an explicit minimal_default
// expression, or a typed null appropriate to the field's AttrType.
type MinimalAssign struct {
	GoName string
	Expr   string
}

const modelTmpl = `// Code generated by schemagen. DO NOT EDIT.

{{.License}}// Package {{.Package}} contains the model for the {{.ResourceName}} {{.SchemaType}}.
package {{.Package}}

import (
{{- range .Imports}}
	"{{.}}"
{{- end}}
)

// {{.TypeName}} represents the Terraform schema for the {{.ResourceName}} {{.SchemaType}}.
type {{.TypeName}} struct {
{{- range .Fields}}
	{{.Name}} {{.Type}} ` + "`tfsdk:\"{{.Tag}}\"`" + `
{{- end}}
}
{{- if .HasNested}}

// --- Nested typed structs (one per nested message in the proto tree) ---
{{range .NestedTypes}}
// {{.TypeName}} mirrors the nested "{{.Path}}" attribute. Use the As/To
// converters on the parent struct to move between types.Object and this
// typed form.
type {{.TypeName}} struct {
{{- range .Fields}}
	{{.Name}} {{.Type}} ` + "`tfsdk:\"{{.Tag}}\"`" + `
{{- end}}
}
{{end}}

// --- AttrType tables for nested types (consumed by types.ObjectValueFrom / ObjectNull) ---
{{range .NestedTypes}}
// {{.AttrTypesFunc}} returns the attr.Type map for the "{{.Path}}" nested
// attribute.
func {{.AttrTypesFunc}}() map[string]attr.Type {
	return map[string]attr.Type{
{{- range .AttrTypes}}
		"{{.Tag}}": {{.Expr}},
{{- end}}
	}
}
{{end}}

// --- Root-level converters (types.Object ⇄ typed struct ergonomics) ---
{{range .Converters}}
{{if eq .Kind "single"}}
// As{{.RootFieldName}} converts the root {{.FieldTag}} attribute from
// types.Object into its typed form. Returns (nil, nil) when the object is
// null or unknown. Use this when you want typed field access without
// manually unpacking .Attributes().
func (m *{{$.TypeName}}) As{{.RootFieldName}}(ctx context.Context) (*{{.NestedType}}, diag.Diagnostics) {
	if m == nil || m.{{.RootFieldName}}.IsNull() || m.{{.RootFieldName}}.IsUnknown() {
		return nil, nil
	}
	var out {{.NestedType}}
	d := m.{{.RootFieldName}}.As(ctx, &out, basetypes.ObjectAsOptions{})
	return &out, d
}

// {{.ConverterName}}ToObject encodes a typed struct back into the
// types.Object shape expected by the framework. A nil receiver returns
// types.ObjectNull with the correct attribute types.
func {{.ConverterName}}ToObject(ctx context.Context, v *{{.NestedType}}) (types.Object, diag.Diagnostics) {
	if v == nil {
		return types.ObjectNull({{.AttrTypesFunc}}()), nil
	}
	return types.ObjectValueFrom(ctx, {{.AttrTypesFunc}}(), v)
}
{{else if eq .Kind "list"}}
// As{{.RootFieldName}} decodes the root {{.FieldTag}} list attribute into
// a typed slice. Returns (nil, nil) when null or unknown.
func (m *{{$.TypeName}}) As{{.RootFieldName}}(ctx context.Context) ([]{{.NestedType}}, diag.Diagnostics) {
	if m == nil || m.{{.RootFieldName}}.IsNull() || m.{{.RootFieldName}}.IsUnknown() {
		return nil, nil
	}
	out := make([]{{.NestedType}}, 0, len(m.{{.RootFieldName}}.Elements()))
	d := m.{{.RootFieldName}}.ElementsAs(ctx, &out, false)
	return out, d
}

// {{.ConverterName}}ToList encodes a typed slice back into a types.List
// of types.Object elements. A nil receiver returns types.ListNull with
// the correct element type.
func {{.ConverterName}}ToList(ctx context.Context, v []{{.NestedType}}) (types.List, diag.Diagnostics) {
	elemType := types.ObjectType{AttrTypes: {{.AttrTypesFunc}}()}
	if v == nil {
		return types.ListNull(elemType), nil
	}
	return types.ListValueFrom(ctx, elemType, v)
}
{{else if eq .Kind "map"}}
// As{{.RootFieldName}} decodes the root {{.FieldTag}} map attribute into
// a typed map. Returns (nil, nil) when null or unknown.
func (m *{{$.TypeName}}) As{{.RootFieldName}}(ctx context.Context) (map[string]{{.NestedType}}, diag.Diagnostics) {
	if m == nil || m.{{.RootFieldName}}.IsNull() || m.{{.RootFieldName}}.IsUnknown() {
		return nil, nil
	}
	out := make(map[string]{{.NestedType}}, len(m.{{.RootFieldName}}.Elements()))
	d := m.{{.RootFieldName}}.ElementsAs(ctx, &out, false)
	return out, d
}

// {{.ConverterName}}ToMap encodes a typed map back into a types.Map.
// A nil receiver returns types.MapNull with the correct element type.
func {{.ConverterName}}ToMap(ctx context.Context, v map[string]{{.NestedType}}) (types.Map, diag.Diagnostics) {
	elemType := types.ObjectType{AttrTypes: {{.AttrTypesFunc}}()}
	if v == nil {
		return types.MapNull(elemType), nil
	}
	return types.MapValueFrom(ctx, elemType, v)
}
{{end}}
{{end}}
{{- if .SubConverters}}

// --- Sub-level converters (free-standing Decode*/ToObject for types nested beyond root level) ---
{{range .SubConverters}}
// {{.DecodeFuncName}} decodes the sub-field from its parent typed struct.
// Returns (nil, nil) when the field is null or unknown.
func {{.DecodeFuncName}}(ctx context.Context, v *{{.ParentType}}) (*{{.NestedType}}, diag.Diagnostics) {
	if v == nil || v.{{.FieldName}}.IsNull() || v.{{.FieldName}}.IsUnknown() {
		return nil, nil
	}
	var out {{.NestedType}}
	d := v.{{.FieldName}}.As(ctx, &out, basetypes.ObjectAsOptions{})
	return &out, d
}

// {{.ToObjectFuncName}} encodes a typed struct back into types.Object.
// A nil receiver returns types.ObjectNull with the correct attribute types.
func {{.ToObjectFuncName}}(ctx context.Context, v *{{.NestedType}}) (types.Object, diag.Diagnostics) {
	if v == nil {
		return types.ObjectNull({{.AttrTypesFunc}}()), nil
	}
	return types.ObjectValueFrom(ctx, {{.AttrTypesFunc}}(), v)
}
{{end}}
{{- end}}
{{- end}}
{{- if .EmitMinimal}}

// GenerateMinimalResourceModel returns a *{{.TypeName}} populated only with
// the supplied id{{if .HasTimeoutsArg}} + timeouts{{end}}; every other field is at its typed null (or its
// declared minimal_default). Used by resources that need to persist a
// partial state when Create / Read returns mid-flight.
func GenerateMinimalResourceModel(id {{.IDFieldType}}{{if .HasTimeoutsArg}}, timeout timeouts.Value{{end}}) *{{.TypeName}} {
	return &{{.TypeName}}{
{{- range .MinimalAssigns}}
		{{.GoName}}: {{.Expr}},
{{- end}}
	}
}
{{- end}}
`

// GenerateModel renders the resource/data-source model file from the merged
// schema attributes. Emits the root struct, any nested typed struct types,
// their AttrType tables, and root-level converters.
func GenerateModel(attrs []SchemaAttr, hasTimeouts bool, schemaType, pkgName, resourceName string) ([]byte, error) {
	typeName := ModelTypeResource
	if schemaType == SchemaTypeDatasource {
		typeName = ModelTypeDatasource
	}

	imports := map[string]bool{
		"github.com/hashicorp/terraform-plugin-framework/types": true,
	}
	fields := make([]ModelField, 0, len(attrs))
	for i := range attrs {
		a := &attrs[i]
		fields = append(fields, ModelField{
			Name: toGoFieldName(a.Name),
			Type: modelGoTypeForAttr(a.AttrType),
			Tag:  a.Name,
		})
	}

	if hasTimeouts {
		fields = append(fields, ModelField{
			Name: "Timeouts",
			Type: "timeouts.Value",
			Tag:  "timeouts",
		})
		if schemaType == SchemaTypeDatasource {
			imports["github.com/hashicorp/terraform-plugin-framework-timeouts/datasource/timeouts"] = true
		} else {
			imports["github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"] = true
		}
	}

	sort.Slice(fields, func(i, j int) bool {
		return fields[i].Name < fields[j].Name
	})

	prefix := ""
	if schemaType == SchemaTypeDatasource {
		prefix = DatasourcePrefix
	}
	nested, err := collectNestedTypes(attrs, prefix)
	if err != nil {
		return nil, err
	}
	converters := collectConverters(attrs, prefix)
	subConverters := collectSubConverters(attrs, prefix)
	hasNested := len(nested) > 0 || len(converters) > 0

	if hasNested {
		imports["context"] = true
		imports["github.com/hashicorp/terraform-plugin-framework/attr"] = true
		imports["github.com/hashicorp/terraform-plugin-framework/diag"] = true

		for _, c := range converters {
			if c.Kind == "single" {
				imports["github.com/hashicorp/terraform-plugin-framework/types/basetypes"] = true
				break
			}
		}
		if len(subConverters) > 0 {
			imports["github.com/hashicorp/terraform-plugin-framework/types/basetypes"] = true
		}
	}

	importList := make([]string, 0, len(imports))
	for imp := range imports {
		importList = append(importList, imp)
	}
	sort.Strings(importList)

	data := ModelData{
		License:       LicenseHeader(),
		Package:       pkgName,
		TypeName:      typeName,
		ResourceName:  resourceName,
		SchemaType:    schemaType,
		Imports:       importList,
		Fields:        fields,
		HasTimeouts:   hasTimeouts,
		NestedTypes:   nested,
		Converters:    converters,
		SubConverters: subConverters,
		HasNested:     hasNested,
	}

	if schemaType != SchemaTypeDatasource {
		assigns, idType, ok, err := planMinimalAssigns(attrs, hasTimeouts, prefix)
		if err != nil {
			return nil, err
		}
		if ok {
			data.EmitMinimal = true
			data.MinimalAssigns = assigns
			data.IDFieldType = idType
			data.HasTimeoutsArg = hasTimeouts
		}
	}

	tmpl, err := template.New("model").Parse(modelTmpl)
	if err != nil {
		return nil, fmt.Errorf("parse model template: %w", err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("execute model template: %w", err)
	}
	src, err := format.Source(buf.Bytes())
	if err != nil {
		return buf.Bytes(), fmt.Errorf("format generated model: %w\n%s", err, buf.String())
	}
	return src, nil
}

func toGoFieldName(name string) string {
	abbreviations := map[string]string{
		"id":   "ID",
		"url":  "URL",
		"uri":  "URI",
		"api":  "API",
		"http": "HTTP",
		"json": "JSON",
		"xml":  "XML",
		"sql":  "SQL",
		"ssh":  "SSH",
		"tls":  "TLS",
		"ssl":  "SSL",
		"aws":  "AWS",
		"gcp":  "GCP",
		"vpc":  "VPC",
		"dns":  "DNS",
		"arn":  "ARN",
		"cmr":  "CMR",
		"wo":   "WO",
	}

	parts := strings.Split(name, "_")
	var result strings.Builder
	for _, part := range parts {
		if part == "" {
			continue
		}
		if abbr, ok := abbreviations[strings.ToLower(part)]; ok {
			result.WriteString(abbr)
			continue
		}
		runes := []rune(part)
		runes[0] = unicode.ToUpper(runes[0])
		result.WriteString(string(runes))
	}
	return result.String()
}

func planMinimalAssigns(attrs []SchemaAttr, hasTimeouts bool, datasourcePrefix string) (assigns []MinimalAssign, idType string, ok bool, err error) {
	var idField *SchemaAttr
	for i := range attrs {
		if attrs[i].Name == "id" {
			idField = &attrs[i]
			break
		}
	}
	if idField == nil {
		return nil, "", false, nil
	}
	idType = modelGoTypeForAttr(idField.AttrType)

	for i := range attrs {
		a := &attrs[i]
		expr, exprErr := minimalAssignExpr(a, datasourcePrefix)
		if exprErr != nil {
			return nil, "", false, fmt.Errorf("minimal assign for %q: %w", a.Name, exprErr)
		}
		assigns = append(assigns, MinimalAssign{
			GoName: toGoFieldName(a.Name),
			Expr:   expr,
		})
	}
	if hasTimeouts {
		assigns = append(assigns, MinimalAssign{GoName: "Timeouts", Expr: "timeout"})
	}
	sort.Slice(assigns, func(i, j int) bool { return assigns[i].GoName < assigns[j].GoName })
	return assigns, idType, true, nil
}

func minimalAssignExpr(a *SchemaAttr, datasourcePrefix string) (string, error) {
	if a.Name == "id" {
		return "id", nil
	}
	if a.MinimalDefault != "" {
		return a.MinimalDefault, nil
	}
	return NullExpr(a, NullExprOptions{HelperPrefix: datasourcePrefix})
}
