// Copyright 2023 Redpanda Data, Inc.
//
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

package schemagen

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"text/template"
)

// ProtoValidatorData drives the per-resource protoValidator emit.
type ProtoValidatorData struct {
	License       string
	Package       string
	ResourceType  string
	ModelImport   string
	ModelAlias    string
	ModelType     string
	ExpandFunc    string
	ResourceLabel string

	PreValidateHook string

	PostExpandHook string

	SkippedFields []string
}

const protoValidatorTmpl = `// Code generated by schemagen. DO NOT EDIT.

{{.License}}package {{.Package}}

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"

	{{.ModelAlias}} "{{.ModelImport}}"
	rpvalidate "github.com/redpanda-data/terraform-provider-redpanda/redpanda/utils/protovalidate"
)

// ConfigValidators wires the protovalidate-driven validator into the
// resource's plan-time validation path. Implements
// resource.ResourceWithConfigValidators.
func (*{{.ResourceType}}) ConfigValidators(_ context.Context) []resource.ConfigValidator {
	return []resource.ConfigValidator{
		protoValidator{},
	}
}

// protoValidator runs the resource's Create-proto buf.validate rules
// against the planned config so violations surface at plan time instead
// of apply. Defers to apply-time API rejection when the config has
// unknowns that prevent a clean model deserialization.
type protoValidator struct{}

// Description implements resource.ConfigValidator.
func (protoValidator) Description(_ context.Context) string {
	return "Validates the {{.ResourceLabel}} against its proto buf.validate annotations."
}

// MarkdownDescription implements resource.ConfigValidator.
func (protoValidator) MarkdownDescription(_ context.Context) string {
	return "Validates against proto ` + "`" + `buf.validate` + "`" + ` annotations on the Create request."
}

// ValidateResource implements resource.ConfigValidator.
func (protoValidator) ValidateResource(ctx context.Context, req resource.ValidateConfigRequest, resp *resource.ValidateConfigResponse) {
	// Defer to apply-time API rejection when the config has any Unknown
	// values — typically cross-resource references that the framework has
	// not yet resolved at Validate timing. Expanding such a model produces
	// empty strings for required fields and would trip protovalidate with
	// spurious "value is required" diagnostics.
	if !req.Config.Raw.IsFullyKnown() {
		return
	}
	var m {{.ModelAlias}}.{{.ModelType}}
	if d := req.Config.Get(ctx, &m); d.HasError() {
		return
	}
{{- if .PreValidateHook }}
	// Resource-level hook: mirror deprecation aliases into canonical
	// fields so Validate sees the same model shape that Apply does.
	if hDiags := {{.PreValidateHook}}(ctx, &m); hDiags.HasError() {
		resp.Diagnostics.Append(hDiags...)
		return
	}
{{- end }}
	payload, eDiags := {{.ModelAlias}}.{{.ExpandFunc}}(ctx, &m)
	if eDiags.HasError() {
		return
	}
{{- if .PostExpandHook }}
	// Resource-level hook: thread TF-only fields onto the payload that
	// Create() also mutates after Expand. Keeps the validator's payload
	// shape in sync with what the API will receive.
	if hDiags := {{.PostExpandHook}}(ctx, &m, payload); hDiags.HasError() {
		resp.Diagnostics.Append(hDiags...)
		return
	}
{{- end }}
	resp.Diagnostics.Append(rpvalidate.Validate(path.Empty(), payload{{if .SkippedFields}},
{{- range $i, $f := .SkippedFields}}
		{{printf "%q" $f}},
{{- end}}
	{{- end }})...)
}
`

// CollectSkippedValidationFields scans cfg.Fields (recursive into nested
// `fields:`) and returns the proto field paths flagged with
// `skip_proto_validation: true`. Path uses dotted notation for nested
// fields (e.g. "cluster_configuration.custom_properties"). The returned
// list is rendered into proto_validator_gen.go as a static skip-set
// passed to rpvalidate.Validate.
//
// Operates on the merged FieldConfig map keyed by proto field name —
// schemagen authors use proto names in yaml, and the wrapper compares
// against the same names protovalidate reports for violations.
func CollectSkippedValidationFields(cfg *Config) []string {
	if cfg == nil {
		return nil
	}
	var out []string
	collectSkipped("", cfg.Fields, &out)
	sort.Strings(out)
	return out
}

func collectSkipped(prefix string, fields map[string]FieldConfig, out *[]string) {
	for name := range fields {
		fc := fields[name]
		path := name
		if prefix != "" {
			path = prefix + "." + name
		}
		if fc.SkipProtoValidation {
			*out = append(*out, path)
		}
		if len(fc.Fields) > 0 {
			collectSkipped(path, fc.Fields, out)
		}
	}
}

// GenerateProtoValidator emits the per-resource protoValidator
// implementation as gofmt-formatted Go source.
func GenerateProtoValidator(data ProtoValidatorData) ([]byte, error) {
	tmpl, err := template.New("proto_validator").Parse(protoValidatorTmpl)
	if err != nil {
		return nil, fmt.Errorf("parse proto_validator template: %w", err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("execute proto_validator template: %w", err)
	}
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return buf.Bytes(), fmt.Errorf("format proto_validator: %w\n%s", err, buf.String())
	}
	return formatted, nil
}
