agents:
  queue: k8s-builders

steps:
  - label: docs
    key: docs
    command: |
      git config --global --add safe.directory /workdir
      ./taskw docs
      if ! git diff --exit-code; then
        echo "Documentation is out of date. Run './taskw docs' locally and commit the changes."
        exit 1
      fi
    plugins:
      - docker#v5.11.0:
          image: "golang:1.24"
          environment:
            - BUILDKITE=true
  - label: generate
    key: generate
    command: |
      git config --global --add safe.directory /workdir
      ./taskw generate
      if ! git diff --exit-code; then
        echo "Generated code is out of date. Run './taskw generate' locally and commit the changes."
        exit 1
      fi
    plugins:
      - docker#v5.11.0:
          image: "golang:1.24"
          environment:
            - BUILDKITE=true
  - label: lint
    key: lint
    command: |
      ./taskw lint
    plugins:
      - docker#v5.11.0:
          image: "golang:1.24"
          environment:
            - BUILDKITE=true
  - label: unit
    key: unit
    command: |
      ./taskw test:unit
    plugins:
      - docker#v5.11.0:
          image: "golang:1.24"
    depends_on:
      - docs
      - generate
      - lint

  - label: test_network
    key: test_network
    if: build.tag == null && build.pull_request.labels includes 'ci-ready'
    command: |
      ./taskw test:network
    plugins:
      - seek-oss/aws-sm#v2.3.2:
          json-to-env:
            - secret-id: sdlc/prod/buildkite/terraform_provider_redpanda
      - docker#v5.11.0:
          image: "golang:1.24"
          environment:
            - REDPANDA_CLIENT_ID
            - REDPANDA_CLIENT_SECRET
            - TF_LOG=DEBUG
    depends_on:
      - lint
      - unit
  - label: test_datasource
    key: test_datasource
    if: build.tag == null && build.pull_request.labels includes 'ci-ready'
    command: |
      ./taskw test:datasource
    plugins:
      - seek-oss/aws-sm#v2.3.2:
          json-to-env:
            - secret-id: sdlc/prod/buildkite/terraform_provider_redpanda
      - docker#v5.11.0:
          image: "golang:1.24"
          environment:
            - REDPANDA_CLIENT_ID
            - REDPANDA_CLIENT_SECRET
            - TF_LOG=DEBUG
            - DATASOURCE_CLUSTER_ID
    depends_on:
      - lint
      - unit
  - label: test_cluster_aws
    key: test_cluster_aws
    if: build.tag == null && build.pull_request.labels includes 'ci-ready'
    command: |
      ./taskw test:cluster:aws
    plugins:
      - seek-oss/aws-sm#v2.3.2:
          json-to-env:
            - secret-id: sdlc/prod/buildkite/terraform_provider_redpanda
      - docker#v5.11.0:
          image: "golang:1.24"
          environment:
            - REDPANDA_CLIENT_ID
            - REDPANDA_CLIENT_SECRET
            - TF_LOG=DEBUG
    depends_on:
      - lint
      - unit
      - test_network
  - label: test_cluster_azure
    key: test_cluster_azure
    if: build.tag == null &&  build.pull_request.labels includes 'ci-ready'
    command: |
      ./taskw test:cluster:azure
    plugins:
      - seek-oss/aws-sm#v2.3.2:
          json-to-env:
            - secret-id: sdlc/prod/buildkite/terraform_provider_redpanda
      - docker#v5.11.0:
          image: "golang:1.24"
          environment:
            - REDPANDA_CLIENT_ID
            - REDPANDA_CLIENT_SECRET
            - TF_LOG=DEBUG
    depends_on:
      - lint
      - unit
      - test_network
  - label: test_cluster_gcp
    key: test_cluster_gcp
    if: build.tag == null && build.pull_request.labels includes 'ci-ready'
    command: |
      ./taskw test:cluster:gcp
    plugins:
      - seek-oss/aws-sm#v2.3.2:
          json-to-env:
            - secret-id: sdlc/prod/buildkite/terraform_provider_redpanda
      - docker#v5.11.0:
          image: "golang:1.24"
          environment:
            - REDPANDA_CLIENT_ID
            - REDPANDA_CLIENT_SECRET
            - TF_LOG=DEBUG
    depends_on:
      - lint
      - unit
      - test_network
  - label: test_serverless_cluster_aws_public
    key: test_serverless_cluster_aws_public
    if: build.tag == null && (build.pull_request.labels includes 'ci-ready' || build.pull_request.labels includes 'ci-ready-serverless')
    command: |
      ./taskw test:serverless:aws:public
    plugins:
      - seek-oss/aws-sm#v2.3.2:
          json-to-env:
            - secret-id: sdlc/prod/buildkite/terraform_provider_redpanda
      - docker#v5.11.0:
          image: "golang:1.24"
          environment:
            - REDPANDA_CLIENT_ID
            - REDPANDA_CLIENT_SECRET
            - TF_LOG=DEBUG
    depends_on:
      - lint
      - unit
      - test_network
  - label: test_serverless_cluster_gcp
    key: test_serverless_cluster_gcp
    if: build.tag == null && (build.pull_request.labels includes 'ci-ready' || build.pull_request.labels includes 'ci-ready-serverless')
    command: |
      ./taskw test:serverless:gcp
    plugins:
      - seek-oss/aws-sm#v2.3.2:
          json-to-env:
            - secret-id: sdlc/prod/buildkite/terraform_provider_redpanda
      - docker#v5.11.0:
          image: "golang:1.24"
          environment:
            - REDPANDA_CLIENT_ID
            - REDPANDA_CLIENT_SECRET
            - TF_LOG=DEBUG
    depends_on:
      - lint
      - unit
      - test_network
  - label: test_serverless_cluster_aws_private
    key: test_serverless_cluster_aws_private
    if: build.tag == null && (build.pull_request.labels includes 'ci-ready' || build.pull_request.labels includes 'ci-ready-serverless')
    command: |
      ./taskw test:serverless:aws:private
    plugins:
      - seek-oss/aws-sm#v2.3.2:
          json-to-env:
            - secret-id: sdlc/prod/buildkite/terraform_provider_redpanda
      - docker#v5.11.0:
          image: "golang:1.24"
          environment:
            - REDPANDA_CLIENT_ID
            - REDPANDA_CLIENT_SECRET
            - TF_LOG=DEBUG
    depends_on:
      - lint
      - unit
      - test_network
  - label: test_serverless_cluster_aws_both
    key: test_serverless_cluster_aws_both
    if: build.tag == null && (build.pull_request.labels includes 'ci-ready' || build.pull_request.labels includes 'ci-ready-serverless')
    command: |
      ./taskw test:serverless:aws:both
    plugins:
      - seek-oss/aws-sm#v2.3.2:
          json-to-env:
            - secret-id: sdlc/prod/buildkite/terraform_provider_redpanda
      - docker#v5.11.0:
          image: "golang:1.24"
          environment:
            - REDPANDA_CLIENT_ID
            - REDPANDA_CLIENT_SECRET
            - TF_LOG=DEBUG
    depends_on:
      - lint
      - unit
      - test_network
  - label: test_serverless_regions
    key: test_serverless_regions
    if: build.tag == null && (build.pull_request.labels includes 'ci-ready' || build.pull_request.labels includes 'ci-ready-serverless')
    command: |
      ./taskw test:serverless:regions
    plugins:
      - seek-oss/aws-sm#v2.3.2:
          json-to-env:
            - secret-id: sdlc/prod/buildkite/terraform_provider_redpanda
      - docker#v5.11.0:
          image: "golang:1.24"
          environment:
            - REDPANDA_CLIENT_ID
            - REDPANDA_CLIENT_SECRET
            - TF_LOG=DEBUG
            - DATASOURCE_CLUSTER_ID
    depends_on:
      - lint
      - unit
  - label: test_serverless_private_link
    key: test_serverless_private_link
    if: build.tag == null && (build.pull_request.labels includes 'ci-ready' || build.pull_request.labels includes 'ci-ready-serverless')
    command: |
      ./taskw test:serverless:privatelink
    plugins:
      - seek-oss/aws-sm#v2.3.2:
          json-to-env:
            - secret-id: sdlc/prod/buildkite/terraform_provider_redpanda
      - docker#v5.11.0:
          image: "golang:1.24"
          environment:
            - REDPANDA_CLIENT_ID
            - REDPANDA_CLIENT_SECRET
            - TF_LOG=DEBUG
    depends_on:
      - lint
      - unit
      - test_network
  - label: test_byoc_aws
    key: test_byoc_aws
    if: build.tag == null && build.pull_request.labels includes 'ci-ready'
    command: |
      ./taskw test:byoc:aws
    plugins:
      - seek-oss/aws-sm#v2.3.2:
          json-to-env:
            - secret-id: sdlc/prod/buildkite/terraform_provider_redpanda
      - docker#v5.12.0:
          image: "golang:1.24"
          environment:
            - REDPANDA_CLIENT_ID
            - REDPANDA_CLIENT_SECRET
            - TF_LOG=DEBUG
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
    depends_on:
      - lint
      - unit
      - test_network
  - label: test_byoc_gcp
    key: test_byoc_gcp
    if: build.tag == null && build.pull_request.labels includes 'ci-ready'
    command: |
      ./taskw test:byoc:gcp
    plugins:
      - seek-oss/aws-sm#v2.3.2:
          json-to-env:
            - secret-id: sdlc/prod/buildkite/terraform_provider_redpanda
      - docker#v5.11.0:
          image: "golang:1.24"
          environment:
            - REDPANDA_CLIENT_ID
            - REDPANDA_CLIENT_SECRET
            - TF_LOG=DEBUG
            - GOOGLE_CREDENTIALS_BASE64
            - GOOGLE_PROJECT
    depends_on:
      - lint
      - unit
      - test_network
  - label: test_byoc_azure
    key: test_byoc_azure
    if: build.tag == null && build.pull_request.labels includes 'ci-ready'
    command: |
      ./taskw test:byoc:azure
    plugins:
      - seek-oss/aws-sm#v2.3.2:
          json-to-env:
            - secret-id: sdlc/prod/buildkite/terraform_provider_redpanda
      - docker#v5.11.0:
          image: "golang:1.24"
          environment:
            - REDPANDA_CLIENT_ID
            - REDPANDA_CLIENT_SECRET
            - TF_LOG=DEBUG
            - AZURE_SUBSCRIPTION_ID
            - AZURE_CLIENT_ID
            - AZURE_CLIENT_SECRET
            - AZURE_TENANT_ID
    depends_on:
      - lint
      - unit
      - test_network

  - label: cleanup_byoc_aws
    key: cleanup_byoc_aws
    if: build.tag == null && build.pull_request.labels includes 'ci-ready'
    command: |
      ./taskw cleanup:aws:ci || echo "AWS cleanup completed with errors (non-blocking)"
    plugins:
      - seek-oss/aws-sm#v2.3.2:
          json-to-env:
            - secret-id: sdlc/prod/buildkite/terraform_provider_redpanda
      - docker#v5.12.0:
          image: "golang:1.24"
          environment:
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_REGION=us-east-2
            - CI=true
    depends_on:
      - test_byoc_aws
    allow_dependency_failure: true
    soft_fail: true

  - label: cleanup_byoc_gcp
    key: cleanup_byoc_gcp
    if: build.tag == null && build.pull_request.labels includes 'ci-ready'
    command: |
      ./taskw cleanup:gcp:ci PROJECT_ID="$$GOOGLE_PROJECT" || echo "GCP cleanup completed with errors (non-blocking)"
    plugins:
      - seek-oss/aws-sm#v2.3.2:
          json-to-env:
            - secret-id: sdlc/prod/buildkite/terraform_provider_redpanda
      - docker#v5.11.0:
          image: "golang:1.24"
          environment:
            - GOOGLE_CREDENTIALS_BASE64
            - GOOGLE_PROJECT
            - GCP_REGION=us-central1
            - CI=true
    depends_on:
      - test_byoc_gcp
    allow_dependency_failure: true
    soft_fail: true

  - label: cleanup_redpanda_cloud
    key: cleanup_redpanda_cloud
    if: build.tag == null && (build.pull_request.labels includes 'ci-ready' || build.pull_request.labels includes 'ci-ready-serverless')
    command: |
      ./taskw cleanup:redpanda || echo "Redpanda Cloud cleanup completed with errors (non-blocking)"
    plugins:
      - seek-oss/aws-sm#v2.3.2:
          json-to-env:
            - secret-id: sdlc/prod/buildkite/terraform_provider_redpanda
      - docker#v5.11.0:
          image: "golang:1.24"
          environment:
            - REDPANDA_CLIENT_ID
            - REDPANDA_CLIENT_SECRET
            - REDPANDA_CLOUD_ENVIRONMENT=pre
            - CI=true
    depends_on:
      - test_cluster_aws
      - test_cluster_azure
      - test_cluster_gcp
      - test_serverless_cluster_aws_public
      - test_serverless_cluster_gcp
      - test_serverless_cluster_aws_private
      - test_serverless_cluster_aws_both
      - test_serverless_private_link
      - test_byoc_aws
      - test_byoc_gcp
      - test_byoc_azure
    allow_dependency_failure: true
    soft_fail: true

