agents:
  queue: k8s-builders

steps:
  - label: lint
    key: lint
    command: make lint
    plugins:
      - docker#v5.11.0:
          image: "golang:1.22"
          environment:
            - BUILDKITE=true
  - label: unit
    key: unit
    command: make unit
    plugins:
      - docker#v5.11.0:
          image: "golang:1.22"
    depends_on:
      - lint

  - label: test_network
    key: test_network
    if: build.tag == null && build.pull_request.labels includes 'ci-ready'
    command: make test_network
    plugins:
      - seek-oss/aws-sm#v2.3.2:
          json-to-env:
            - secret-id: sdlc/prod/buildkite/terraform_provider_redpanda
      - docker#v5.11.0:
          image: "golang:1.22"
          environment:
            - REDPANDA_CLIENT_ID
            - REDPANDA_CLIENT_SECRET
            - TF_LOG=DEBUG
    depends_on:
      - lint
      - unit
  - label: test_cluster_aws
    key: test_cluster_aws
    if: build.tag == null && build.pull_request.labels includes 'ci-ready'
    command: make test_cluster_aws
    plugins:
      - seek-oss/aws-sm#v2.3.2:
          json-to-env:
            - secret-id: sdlc/prod/buildkite/terraform_provider_redpanda
      - docker#v5.11.0:
          image: "golang:1.22"
          environment:
            - REDPANDA_CLIENT_ID
            - REDPANDA_CLIENT_SECRET
            - TF_LOG=DEBUG
    depends_on:
      - lint
      - unit
      - test_network
  - label: test_cluster_azure
    key: test_cluster_azure
    if: build.tag == null &&  build.pull_request.labels includes 'ci-ready'
    command: make test_cluster_azure
    plugins:
      - seek-oss/aws-sm#v2.3.2:
          json-to-env:
            - secret-id: sdlc/prod/buildkite/terraform_provider_redpanda
      - docker#v5.11.0:
          image: "golang:1.22"
          environment:
            - REDPANDA_CLIENT_ID
            - REDPANDA_CLIENT_SECRET
            - TF_LOG=DEBUG
    depends_on:
      - lint
      - unit
      - test_network
  - label: test_cluster_gcp
    key: test_cluster_gcp
    if: build.tag == null && build.pull_request.labels includes 'ci-ready'
    command: make test_cluster_gcp
    plugins:
      - seek-oss/aws-sm#v2.3.2:
          json-to-env:
            - secret-id: sdlc/prod/buildkite/terraform_provider_redpanda
      - docker#v5.11.0:
          image: "golang:1.22"
          environment:
            - REDPANDA_CLIENT_ID
            - REDPANDA_CLIENT_SECRET
            - TF_LOG=DEBUG
    depends_on:
      - lint
      - unit
      - test_network
  - label: test_serverless_cluster
    key: test_serverless_cluster
    if: build.tag == null && build.pull_request.labels includes 'ci-ready'
    command: make test_serverless_cluster
    plugins:
      - seek-oss/aws-sm#v2.3.2:
          json-to-env:
            - secret-id: sdlc/prod/buildkite/terraform_provider_redpanda
      - docker#v5.11.0:
          image: "golang:1.22"
          environment:
            - REDPANDA_CLIENT_ID
            - REDPANDA_CLIENT_SECRET
            - TF_LOG=DEBUG
    depends_on:
      - lint
      - unit
      - test_network
  - label: test_byoc_aws
    key: test_byoc_aws
    if: build.tag == null && build.pull_request.labels includes 'byoc-ready'
    command: make test_byoc_aws
    plugins:
      - seek-oss/aws-sm#v2.3.2:
          json-to-env:
            - secret-id: sdlc/prod/buildkite/terraform_provider_redpanda
      - docker#v5.12.0:
          image: "golang:1.22"
          environment:
            - REDPANDA_CLIENT_ID
            - REDPANDA_CLIENT_SECRET
            - TF_LOG=DEBUG
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
    depends_on:
      - lint
      - unit
  - label: test_byoc_gcp
    key: test_byoc_gcp
    if: build.tag == null && build.pull_request.labels includes 'byoc-ready'
    command: make test_byoc_gcp
    plugins:
      - seek-oss/aws-sm#v2.3.2:
          json-to-env:
            - secret-id: sdlc/prod/buildkite/terraform_provider_redpanda
      - docker#v5.11.0:
          image: "golang:1.22"
          environment:
            - REDPANDA_CLIENT_ID
            - REDPANDA_CLIENT_SECRET
            - TF_LOG=DEBUG
            - GOOGLE_CREDENTIALS_BASE64
            - GOOGLE_PROJECT
    depends_on:
      - lint
      - unit
  - label: test_byoc_azure
    key: test_byoc_azure
    if: build.tag == null && build.pull_request.labels includes 'byoc-ready'
    command: make test_byoc_azure
    plugins:
      - seek-oss/aws-sm#v2.3.2:
          json-to-env:
            - secret-id: sdlc/prod/buildkite/terraform_provider_redpanda
      - docker#v5.11.0:
          image: "golang:1.22"
          environment:
            - REDPANDA_CLIENT_ID
            - REDPANDA_CLIENT_SECRET
            - TF_LOG=DEBUG
            - AZURE_SUBSCRIPTION_ID
            - AZURE_CLIENT_ID
            - AZURE_CLIENT_SECRET
            - AZURE_TENANT_ID
    depends_on:
      - lint
      - unit
  - label: Release
    key: release
    if: build.tag != null && build.tag =~ /^v/
    depends_on:
      - lint
      - unit
    plugins:
      - seek-oss/aws-sm#v2.3.2:
          json-to-env:
            - secret-id: sdlc/prod/buildkite/terraform_provider_redpanda
      - docker#v5.11.0:
          image: "goreleaser/goreleaser:latest"
          environment:
            - GITHUB_TOKEN
            - GPG_PRIVATE_KEY
            - GPG_FINGERPRINT
            - PASSPHRASE
          command:
            - release
            - --clean