// Copyright 2023 Redpanda Data, Inc.
//
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

// Package bufdeps owns the on-disk pin file that records the upstream git
// SHAs (cloudv2, console) and buf-gen Go module BSR commit IDs that
// cmd/apidesc-import and cmd/schemagen consume.
package bufdeps

import (
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// RelPath is the pin file location relative to the repo root.
const RelPath = "internal/buf_dependencies.yaml"

// Source records a single upstream git source.
type Source struct {
	Remote string `yaml:"remote"`
	SHA    string `yaml:"sha"`
}

// Deps is the full pin file payload.
//
// BufModules maps a parent buf-gen module path (e.g. "buf.build/redpandadata/cloud")
// to the truncated BSR commit ID from the matching pseudo-version in go.mod
// (e.g. "bea2c0f11c89"). protocolbuffers/go and grpc/go submodules of the same
// parent always carry the same commit, so we collapse them.
type Deps struct {
	Cloudv2    Source            `yaml:"cloudv2"`
	Console    Source            `yaml:"console"`
	BufModules map[string]string `yaml:"buf_modules"`
}

const header = `# Code generated by cmd/schemagen -update-deps. DO NOT EDIT.
#
# Upstream sources consumed by cmd/apidesc-import and cmd/schemagen.
# Both tools assert that local cloudv2 / console checkouts are at these
# SHAs before generating, and warn (not fail) when go.mod's buf-gen module
# BSR commit IDs diverge from buf_modules below. To bump: check out the
# target SHAs locally, then run
#   task generate:bump-deps
# which re-runs schemagen with -update-deps and regenerates everything.

`

// DefaultPath returns the pin file path relative to repoRoot.
func DefaultPath(repoRoot string) string {
	return filepath.Join(repoRoot, RelPath)
}

// Read loads the pin file at path.
func Read(path string) (*Deps, error) {
	data, err := os.ReadFile(filepath.Clean(path))
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	var d Deps
	if err := yaml.Unmarshal(data, &d); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	if d.Cloudv2.SHA == "" {
		return nil, fmt.Errorf("%s: cloudv2.sha is empty", path)
	}
	if d.Console.SHA == "" {
		return nil, fmt.Errorf("%s: console.sha is empty", path)
	}
	return &d, nil
}

// Write serializes deps to path, prepending the canonical header.
func Write(path string, d *Deps) error {
	body, err := yaml.Marshal(d)
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		return fmt.Errorf("mkdir: %w", err)
	}
	out := append([]byte(header), body...)
	if err := os.WriteFile(path, out, 0o600); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

// HeadSHA returns the full SHA at HEAD of the git repo at repoPath.
func HeadSHA(repoPath string) (string, error) {
	if repoPath == "" {
		return "", errors.New("repo path is empty")
	}
	cmd := exec.CommandContext(context.Background(), "git", "-C", repoPath, "rev-parse", "HEAD")
	out, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("git rev-parse HEAD %s: %w", repoPath, err)
	}
	return strings.TrimSpace(string(out)), nil
}

// AssertCheckoutAt fails if `git -C repoPath rev-parse HEAD` differs from
// expectedSHA. name is used in error messages (e.g. "cloudv2").
func AssertCheckoutAt(repoPath, expectedSHA, name string) error {
	got, err := HeadSHA(repoPath)
	if err != nil {
		return fmt.Errorf("%s: %w", name, err)
	}
	if got != expectedSHA {
		return fmt.Errorf("%s checkout at %s is at %s, pin requires %s — run `task generate:bump-deps` to update the pin, or check out the pinned SHA locally",
			name, repoPath, short(got), short(expectedSHA))
	}
	return nil
}

// bufGenPseudoVersion matches a pseudo-version on a buf-gen module require
// line in go.mod and extracts the truncated BSR commit ID.
//
// Example: `buf.build/gen/go/redpandadata/cloud/protocolbuffers/go v1.36.11-20260527154152-bea2c0f11c89.1`
// → module="buf.build/redpandadata/cloud", commit="bea2c0f11c89"
var bufGenPseudoVersion = regexp.MustCompile(`buf\.build/gen/go/([^/]+/[^/]+)/[^ \t]+\s+v[\d.]+-\d+-([a-f0-9]+)\.\d+`)

// LoadBufModulesFromGoMod scans go.mod and returns a {parent-module: commit}
// map for every buf-gen Go module pulled from the buf.build registry.
// protocolbuffers/go and grpc/go submodules of the same parent collapse into
// a single entry; if the two disagree the function returns an error.
func LoadBufModulesFromGoMod(goModPath string) (map[string]string, error) {
	data, err := os.ReadFile(filepath.Clean(goModPath))
	if err != nil {
		return nil, fmt.Errorf("read go.mod: %w", err)
	}
	out := map[string]string{}
	for _, m := range bufGenPseudoVersion.FindAllStringSubmatch(string(data), -1) {
		owner, commit := m[1], m[2]
		key := "buf.build/" + owner
		if prev, ok := out[key]; ok && prev != commit {
			return nil, fmt.Errorf("buf-gen module %s has divergent commits in go.mod: %s vs %s — bump them together",
				key, prev, commit)
		}
		out[key] = commit
	}
	return out, nil
}

// CompareBufModules reports module entries where pinned and current disagree.
// Returns a slice of human-readable messages suitable for log.Print as
// WARNINGs. An empty slice means everything matches.
func CompareBufModules(pinned, current map[string]string) []string {
	var msgs []string
	keys := map[string]struct{}{}
	for k := range pinned {
		keys[k] = struct{}{}
	}
	for k := range current {
		keys[k] = struct{}{}
	}
	sorted := make([]string, 0, len(keys))
	for k := range keys {
		sorted = append(sorted, k)
	}
	sort.Strings(sorted)
	for _, k := range sorted {
		p, c := pinned[k], current[k]
		switch {
		case p == c:
			// match — nothing to report
		case p == "" && c != "":
			msgs = append(msgs, fmt.Sprintf("buf module %s present in go.mod (%s) but not in pin file", k, c))
		case p != "" && c == "":
			msgs = append(msgs, fmt.Sprintf("buf module %s pinned to %s but absent from go.mod", k, p))
		default:
			msgs = append(msgs, fmt.Sprintf("buf module %s pinned to %s, go.mod has %s — run `task generate:bump-deps` to realign", k, p, c))
		}
	}
	return msgs
}

func short(sha string) string {
	if len(sha) > 12 {
		return sha[:12]
	}
	return sha
}
