// Copyright 2023 Redpanda Data, Inc.
//
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

package bufdeps

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

func TestReadWriteRoundTrip(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "buf_dependencies.yaml")

	want := &Deps{
		Cloudv2: Source{
			Remote: "github.com/redpanda-data/cloudv2",
			SHA:    "aea3fe56605ea15169f262252a571808417f164e",
		},
		Console: Source{
			Remote: "github.com/redpanda-data/console",
			SHA:    "4a8e3db68f5569812b65410afe37538f72728ac5",
		},
		BufModules: map[string]string{
			"buf.build/redpandadata/cloud":     "bea2c0f11c89",
			"buf.build/redpandadata/dataplane": "5d8d126492a6",
		},
	}
	if err := Write(path, want); err != nil {
		t.Fatalf("Write: %v", err)
	}
	got, err := Read(path)
	if err != nil {
		t.Fatalf("Read: %v", err)
	}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("round-trip mismatch:\n got: %+v\nwant: %+v", got, want)
	}

	// Header is preserved verbatim.
	data, err := os.ReadFile(filepath.Clean(path))
	if err != nil {
		t.Fatalf("read raw: %v", err)
	}
	if !strings.HasPrefix(string(data), "# Code generated by cmd/schemagen -update-deps. DO NOT EDIT.") {
		t.Fatalf("header missing from %q", string(data))
	}
}

func TestReadMissingSHA(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "buf_dependencies.yaml")
	if err := os.WriteFile(path, []byte("cloudv2:\n  remote: foo\nconsole:\n  remote: bar\n"), 0o600); err != nil {
		t.Fatalf("seed: %v", err)
	}
	if _, err := Read(path); err == nil {
		t.Fatal("expected error for empty SHA, got nil")
	}
}

func TestAssertCheckoutAt(t *testing.T) {
	if _, err := exec.LookPath("git"); err != nil {
		t.Skip("git not available")
	}
	dir := t.TempDir()
	mustRun(t, dir, "git", "init", "-q", "-b", "main")
	mustRun(t, dir, "git", "config", "user.email", "t@example.test")
	mustRun(t, dir, "git", "config", "user.name", "t")
	mustRun(t, dir, "git", "commit", "-q", "--allow-empty", "-m", "init")

	head := mustOut(t, dir, "git", "rev-parse", "HEAD")

	if err := AssertCheckoutAt(dir, head, "test"); err != nil {
		t.Fatalf("matching SHA: %v", err)
	}
	err := AssertCheckoutAt(dir, "0123456789abcdef0123456789abcdef01234567", "test")
	if err == nil {
		t.Fatal("expected mismatch error, got nil")
	}
	if !strings.Contains(err.Error(), "bump-deps") {
		t.Fatalf("error should hint at bump-deps: %v", err)
	}
}

func TestLoadBufModulesFromGoMod(t *testing.T) {
	dir := t.TempDir()
	goMod := filepath.Join(dir, "go.mod")
	body := `module example

go 1.25

require (
	buf.build/gen/go/redpandadata/cloud/grpc/go v1.6.2-20260527154152-bea2c0f11c89.1
	buf.build/gen/go/redpandadata/cloud/protocolbuffers/go v1.36.11-20260527154152-bea2c0f11c89.1
	buf.build/gen/go/redpandadata/dataplane/grpc/go v1.6.1-20260429204409-5d8d126492a6.1
	buf.build/gen/go/redpandadata/dataplane/protocolbuffers/go v1.36.11-20260429204409-5d8d126492a6.1
	buf.build/gen/go/redpandadata/core/protocolbuffers/go v1.36.11-20260410204044-2088239db14c.1
)
`
	if err := os.WriteFile(goMod, []byte(body), 0o600); err != nil {
		t.Fatalf("seed: %v", err)
	}
	got, err := LoadBufModulesFromGoMod(goMod)
	if err != nil {
		t.Fatalf("LoadBufModulesFromGoMod: %v", err)
	}
	want := map[string]string{
		"buf.build/redpandadata/cloud":     "bea2c0f11c89",
		"buf.build/redpandadata/dataplane": "5d8d126492a6",
		"buf.build/redpandadata/core":      "2088239db14c",
	}
	if len(got) != len(want) {
		t.Fatalf("len mismatch: got %d want %d (%v)", len(got), len(want), got)
	}
	for k, v := range want {
		if got[k] != v {
			t.Errorf("%s: got %q want %q", k, got[k], v)
		}
	}
}

func TestLoadBufModulesDivergent(t *testing.T) {
	dir := t.TempDir()
	goMod := filepath.Join(dir, "go.mod")
	body := `require (
	buf.build/gen/go/redpandadata/cloud/grpc/go v1.6.2-20260527154152-bea2c0f11c89.1
	buf.build/gen/go/redpandadata/cloud/protocolbuffers/go v1.36.11-20260504195947-32ca5808787d.1
)`
	if err := os.WriteFile(goMod, []byte(body), 0o600); err != nil {
		t.Fatalf("seed: %v", err)
	}
	if _, err := LoadBufModulesFromGoMod(goMod); err == nil {
		t.Fatal("expected divergent-commit error, got nil")
	}
}

func TestCompareBufModules(t *testing.T) {
	pinned := map[string]string{
		"buf.build/redpandadata/cloud":     "bea2c0f11c89",
		"buf.build/redpandadata/dataplane": "5d8d126492a6",
	}
	current := map[string]string{
		"buf.build/redpandadata/cloud":     "deadbeef0000", // changed
		"buf.build/redpandadata/dataplane": "5d8d126492a6", // same
		"buf.build/redpandadata/common":    "newmodule000", // new in go.mod
	}
	msgs := CompareBufModules(pinned, current)
	if len(msgs) != 2 {
		t.Fatalf("expected 2 messages, got %d: %v", len(msgs), msgs)
	}
	joined := strings.Join(msgs, "\n")
	if !strings.Contains(joined, "redpandadata/cloud") || !strings.Contains(joined, "bump-deps") {
		t.Errorf("messages missing expected content:\n%s", joined)
	}
	if !strings.Contains(joined, "redpandadata/common") {
		t.Errorf("new module not reported:\n%s", joined)
	}
}

func mustRun(t *testing.T, dir, name string, args ...string) {
	t.Helper()
	cmd := exec.CommandContext(context.Background(), name, args...)
	cmd.Dir = dir
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("%s %v: %v: %s", name, args, err, out)
	}
}

func mustOut(t *testing.T, dir, name string, args ...string) string {
	t.Helper()
	cmd := exec.CommandContext(context.Background(), name, args...)
	cmd.Dir = dir
	out, err := cmd.Output()
	if err != nil {
		t.Fatalf("%s %v: %v", name, args, err)
	}
	return strings.TrimSpace(string(out))
}
