// Code generated by modelgen. DO NOT EDIT.

// Copyright 2023 Redpanda Data, Inc.
//
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

// Package user contains the model for the user resource.
package user

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// ResourceModel represents the Terraform schema for the user resource.
type ResourceModel struct {
	AllowDeletion     types.Bool   `tfsdk:"allow_deletion"`
	ClusterAPIURL     types.String `tfsdk:"cluster_api_url"`
	ID                types.String `tfsdk:"id"`
	Mechanism         types.String `tfsdk:"mechanism"`
	Name              types.String `tfsdk:"name"`
	Password          types.String `tfsdk:"password"`
	PasswordWO        types.String `tfsdk:"password_wo"`
	PasswordWOVersion types.Int64  `tfsdk:"password_wo_version"`
}
