// Code generated by schemagen. DO NOT EDIT.

// Copyright 2023 Redpanda Data, Inc.
//
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

package topic

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/mapplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/numberplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// ResourceTopicSchema returns the Terraform schema for the topic resource.
func ResourceTopicSchema(_ context.Context) schema.Schema {
	return schema.Schema{
		Description: "Topic represents a Kafka topic configuration",
		Attributes: map[string]schema.Attribute{
			"cluster_api_url": schema.StringAttribute{
				Description:   "The cluster API URL. Changing this will prevent deletion of the resource on the existing cluster. It is generally a better idea to delete an existing resource and create a new one than to change this value unless you are planning to do state imports",
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},

			"name": schema.StringAttribute{
				Description:   "The name of the topic. Length must be between 1 and 249. Must match pattern `^[a-zA-Z0-9._\\-]*$`.",
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},

			"replica_assignments": schema.ListNestedAttribute{
				Description:   "Manually specify broker ID assignments for partition replicas. If manually assigning replicas, both replication_factor and partition_count must be -1. Mutually exclusive with partition_count and replication_factor.",
				Optional:      true,
				PlanModifiers: []planmodifier.List{listplanmodifier.RequiresReplace()},
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"partition_id": schema.Int32Attribute{
							Description: "A partition to create.",
							Required:    true,
						},
						"replica_ids": schema.ListAttribute{
							Description: "The broker IDs the partition replicas are assigned to.",
							Required:    true,
							ElementType: types.Int32Type,
						},
					},
				},
			},

			"allow_deletion": schema.BoolAttribute{
				Description: "Indicates whether the topic can be deleted.",
				Optional:    true,
				Computed:    true,
				Default:     booldefault.StaticBool(false),
			},

			"configuration": schema.MapAttribute{
				Description:   "A map of string key/value pairs of topic configurations.",
				Optional:      true,
				Computed:      true,
				PlanModifiers: []planmodifier.Map{mapplanmodifier.UseStateForUnknown()},
				ElementType:   types.StringType,
			},

			"partition_count": schema.NumberAttribute{
				Description:   "The number of partitions for the topic. This determines how the data is distributed across brokers. Increases are fully supported without data loss. Decreases will destroy and recreate the topic if allow_deletion is set to true (defaults to false). Must be at least -1.",
				Optional:      true,
				Computed:      true,
				PlanModifiers: []planmodifier.Number{numberplanmodifier.RequiresReplaceIf(partitionRequiresReplaceWhenShrinking, "Decreasing partition count requires recreating the topic", "Decreasing partition count requires recreating the topic"), numberplanmodifier.UseStateForUnknown()},
			},

			"replication_factor": schema.NumberAttribute{
				Description:   "The replication factor for the topic, which defines how many copies of the data are kept across different brokers for fault tolerance. Must be between -1 and 5 (inclusive).",
				Optional:      true,
				Computed:      true,
				PlanModifiers: []planmodifier.Number{numberplanmodifier.RequiresReplace(), numberplanmodifier.UseStateForUnknown()},
			},

			"id": schema.StringAttribute{
				Description:   "Unique identifier of the resource.",
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
		},
		Version: 1,
	}
}
