// Code generated by go generate; DO NOT EDIT.
// Generated by: redpanda/utils/testutil/generator

package resourcegroup

import (
	"github.com/redpanda-data/terraform-provider-redpanda/redpanda/utils/compare"
)

// Compare performs comprehensive field-by-field comparison between two ResourceModel instances
func (m *ResourceModel) Compare(other *ResourceModel) []compare.FieldDiff {
	var diffs []compare.FieldDiff

	// String fields
	compare.Collect(&diffs, compare.String("name", m.Name, other.Name))
	compare.Collect(&diffs, compare.String("id", m.ID, other.ID))

	return diffs
}

// Compare performs comprehensive field-by-field comparison between two DataModel instances
func (m *DataModel) Compare(other *DataModel) []compare.FieldDiff {
	var diffs []compare.FieldDiff

	// String fields
	compare.Collect(&diffs, compare.String("name", m.Name, other.Name))
	compare.Collect(&diffs, compare.String("id", m.ID, other.ID))

	return diffs
}
