// Code generated by schemagen. DO NOT EDIT.

// Copyright 2023 Redpanda Data, Inc.
//
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

package serverlessprivatelink

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/redpanda-data/terraform-provider-redpanda/redpanda/validators"
)

// ResourceServerlessPrivateLinkSchema returns the Terraform schema for the serverlessprivatelink resource.
func ResourceServerlessPrivateLinkSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Description: "Manages a Redpanda Serverless Private Link",
		Attributes: map[string]schema.Attribute{
			"cloud_provider": schema.StringAttribute{
				Description:   "Cloud provider (aws)",
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Validators:    validators.CloudProviders(),
			},

			"name": schema.StringAttribute{
				Description:   "Name of the serverless private link",
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},

			"resource_group_id": schema.StringAttribute{
				Description:   "The ID of the Resource Group in which to create the serverless private link",
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},

			"serverless_region": schema.StringAttribute{
				Description:   "Redpanda serverless region",
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},

			"cloud_provider_config": schema.SingleNestedAttribute{
				Description:        "Cloud Provider Config configuration",
				Optional:           true,
				DeprecationMessage: "cloud_provider_config has been replaced by aws_config. Move your configuration from cloud_provider_config.aws to aws_config.\n\nNone of this serverless private link resource's attributes are marked RequiresReplace, so updating in place is safe. To guarantee the transition will be a no-op, use terraform state rm followed by terraform import on each affected serverless private link resource:\n\n  terraform state rm redpanda_serverless_private_link.<resource_name>\n  terraform import redpanda_serverless_private_link.<resource_name> <serverless_private_link_id>",
				Validators:         []validator.Object{validators.ServerlessPrivateLinkConfigRemovedValidator{}},
				Attributes: map[string]schema.Attribute{
					"aws": schema.SingleNestedAttribute{
						Description: "AWS configuration",
						Optional:    true,
						Attributes: map[string]schema.Attribute{
							"allowed_principals": schema.ListAttribute{
								Description: "Allowed Principals",
								Optional:    true,
								ElementType: types.StringType,
							},
						},
					},
				},
			},

			"allow_deletion": schema.BoolAttribute{
				Description: "Allows deletion of the serverless private link. Defaults to false.",
				Optional:    true,
				Computed:    true,
				Default:     booldefault.StaticBool(false),
			},

			"aws_config": schema.SingleNestedAttribute{
				Description:   "AWS-specific configuration. Required when cloud_provider is 'aws'.",
				Optional:      true,
				Computed:      true,
				PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
				Attributes: map[string]schema.Attribute{
					"allowed_principals": schema.ListAttribute{
						Description: "AWS principals (ARNs) allowed to connect to the private link endpoint",
						Required:    true,
						Validators:  []validator.List{listvalidator.SizeAtLeast(1)},
						ElementType: types.StringType,
					},
				},
			},

			"id": schema.StringAttribute{
				Description:   "The ID of the serverless private link",
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},

			"state": schema.StringAttribute{
				Description:   "Current state of the serverless private link (STATE_CREATING, STATE_READY, STATE_DELETING, STATE_FAILED, STATE_UPDATING)",
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},

			"status": schema.SingleNestedAttribute{
				Description:   "Cloud provider specific status information",
				Computed:      true,
				PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
				Attributes: map[string]schema.Attribute{
					"aws": schema.SingleNestedAttribute{
						Description:   "AWS-specific status information",
						Computed:      true,
						PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
						Attributes: map[string]schema.Attribute{
							"availability_zones": schema.ListAttribute{
								Description:   "Availability zones where the private link endpoint service is available",
								Computed:      true,
								PlanModifiers: []planmodifier.List{listplanmodifier.UseStateForUnknown()},
								ElementType:   types.StringType,
							},
							"vpc_endpoint_service_name": schema.StringAttribute{
								Description:   "VPC endpoint service name for connecting to the private link",
								Computed:      true,
								PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
							},
						},
					},
				},
			},

			"timeouts": timeouts.Attributes(ctx, timeouts.Opts{
				Create: true,
				Update: true,
				Delete: true,
			}),
		},
	}
}
