// Code generated by modelgen. DO NOT EDIT.

// Copyright 2023 Redpanda Data, Inc.
//
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

// Package cluster contains the model for the cluster datasource.
package cluster

import (
	"github.com/hashicorp/terraform-plugin-framework-timeouts/datasource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// DataModel represents the Terraform schema for the cluster datasource.
type DataModel struct {
	AWSPrivateLink           types.Object   `tfsdk:"aws_private_link"`
	AllowDeletion            types.Bool     `tfsdk:"allow_deletion"`
	AzurePrivateLink         types.Object   `tfsdk:"azure_private_link"`
	CloudProvider            types.String   `tfsdk:"cloud_provider"`
	ClusterAPIURL            types.String   `tfsdk:"cluster_api_url"`
	ClusterConfiguration     types.Object   `tfsdk:"cluster_configuration"`
	ClusterType              types.String   `tfsdk:"cluster_type"`
	ConnectionType           types.String   `tfsdk:"connection_type"`
	CreatedAt                types.String   `tfsdk:"created_at"`
	CustomerManagedResources types.Object   `tfsdk:"customer_managed_resources"`
	GCPGlobalAccessEnabled   types.Bool     `tfsdk:"gcp_global_access_enabled"`
	GCPPrivateServiceConnect types.Object   `tfsdk:"gcp_private_service_connect"`
	HTTPProxy                types.Object   `tfsdk:"http_proxy"`
	ID                       types.String   `tfsdk:"id"`
	KafkaAPI                 types.Object   `tfsdk:"kafka_api"`
	KafkaConnect             types.Object   `tfsdk:"kafka_connect"`
	MaintenanceWindowConfig  types.Object   `tfsdk:"maintenance_window_config"`
	Name                     types.String   `tfsdk:"name"`
	NetworkID                types.String   `tfsdk:"network_id"`
	Prometheus               types.Object   `tfsdk:"prometheus"`
	ReadReplicaClusterIds    types.List     `tfsdk:"read_replica_cluster_ids"`
	RedpandaConsole          types.Object   `tfsdk:"redpanda_console"`
	RedpandaVersion          types.String   `tfsdk:"redpanda_version"`
	Region                   types.String   `tfsdk:"region"`
	ResourceGroupID          types.String   `tfsdk:"resource_group_id"`
	SchemaRegistry           types.Object   `tfsdk:"schema_registry"`
	State                    types.String   `tfsdk:"state"`
	StateDescription         types.Object   `tfsdk:"state_description"`
	Tags                     types.Map      `tfsdk:"tags"`
	ThroughputTier           types.String   `tfsdk:"throughput_tier"`
	Timeouts                 timeouts.Value `tfsdk:"timeouts"`
	Zones                    types.List     `tfsdk:"zones"`
}
