// Code generated by go generate; DO NOT EDIT.
// Generated by: redpanda/utils/testutil/generator

package cluster

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/redpanda-data/terraform-provider-redpanda/redpanda/utils/compare"
)

// Compare performs comprehensive field-by-field comparison between two ResourceModel instances
func (m *ResourceModel) Compare(other *ResourceModel) []compare.FieldDiff {
	var diffs []compare.FieldDiff

	// String fields
	compare.Collect(&diffs, compare.String("name", m.Name, other.Name))
	compare.Collect(&diffs, compare.String("id", m.ID, other.ID))
	compare.Collect(&diffs, compare.String("connection_type", m.ConnectionType, other.ConnectionType))
	compare.Collect(&diffs, compare.String("cloud_provider", m.CloudProvider, other.CloudProvider))
	compare.Collect(&diffs, compare.String("cluster_type", m.ClusterType, other.ClusterType))
	compare.Collect(&diffs, compare.String("redpanda_version", m.RedpandaVersion, other.RedpandaVersion))
	compare.Collect(&diffs, compare.String("throughput_tier", m.ThroughputTier, other.ThroughputTier))
	compare.Collect(&diffs, compare.String("region", m.Region, other.Region))
	compare.Collect(&diffs, compare.String("created_at", m.CreatedAt, other.CreatedAt))
	compare.Collect(&diffs, compare.String("state", m.State, other.State))
	compare.Collect(&diffs, compare.String("resource_group_id", m.ResourceGroupID, other.ResourceGroupID))
	compare.Collect(&diffs, compare.String("network_id", m.NetworkID, other.NetworkID))
	compare.Collect(&diffs, compare.String("cluster_api_url", m.ClusterAPIURL, other.ClusterAPIURL))

	// Bool fields
	compare.Collect(&diffs, compare.Bool("allow_deletion", m.AllowDeletion, other.AllowDeletion))
	compare.Collect(&diffs, compare.Bool("gcp_global_access_enabled", m.GCPGlobalAccessEnabled, other.GCPGlobalAccessEnabled))

	// Int fields
	compare.Collect(&diffs, compare.Int32("redpanda_node_count", m.RedpandaNodeCount, other.RedpandaNodeCount))

	// List fields
	compare.Collect(&diffs, compare.List("zones", m.Zones, other.Zones))
	compare.Collect(&diffs, compare.List("read_replica_cluster_ids", m.ReadReplicaClusterIDs, other.ReadReplicaClusterIDs))

	// Map fields
	compare.Collect(&diffs, compare.Map("tags", m.Tags, other.Tags))

	// Object fields (deep comparison)
	compare.CollectAll(&diffs, compareStateDescription("state_description", m.StateDescription, other.StateDescription))
	compare.CollectAll(&diffs, compareAwsPrivateLink("aws_private_link", m.AwsPrivateLink, other.AwsPrivateLink))
	compare.CollectAll(&diffs, compareGcpPrivateServiceConnect("gcp_private_service_connect", m.GcpPrivateServiceConnect, other.GcpPrivateServiceConnect))
	compare.CollectAll(&diffs, compareAzurePrivateLink("azure_private_link", m.AzurePrivateLink, other.AzurePrivateLink))
	compare.CollectAll(&diffs, compareKafkaAPI("kafka_api", m.KafkaAPI, other.KafkaAPI))
	compare.CollectAll(&diffs, compareHTTPProxy("http_proxy", m.HTTPProxy, other.HTTPProxy))
	compare.CollectAll(&diffs, compareSchemaRegistry("schema_registry", m.SchemaRegistry, other.SchemaRegistry))
	compare.CollectAll(&diffs, compareKafkaConnect("kafka_connect", m.KafkaConnect, other.KafkaConnect))
	compare.CollectAll(&diffs, compareCustomerManagedResources("customer_managed_resources", m.CustomerManagedResources, other.CustomerManagedResources))
	compare.CollectAll(&diffs, comparePrometheus("prometheus", m.Prometheus, other.Prometheus))
	compare.CollectAll(&diffs, compareRedpandaConsole("redpanda_console", m.RedpandaConsole, other.RedpandaConsole))
	compare.CollectAll(&diffs, compareMaintenanceWindowConfig("maintenance_window_config", m.MaintenanceWindowConfig, other.MaintenanceWindowConfig))
	compare.CollectAll(&diffs, compareClusterConfiguration("cluster_configuration", m.ClusterConfiguration, other.ClusterConfiguration))

	return diffs
}

// compareStateDescription compares state_description objects
func compareStateDescription(field string, a, b types.Object) []compare.FieldDiff {
	if d := compare.ObjectNullCheck(field, a, b); d != nil {
		return []compare.FieldDiff{*d}
	}
	if a.IsNull() {
		return nil
	}

	var diffs []compare.FieldDiff
	aAttrs := a.Attributes()
	bAttrs := b.Attributes()

	if aVal, ok := aAttrs["code"].(types.Int32); ok {
		if bVal, ok := bAttrs["code"].(types.Int32); ok {
			compare.Collect(&diffs, compare.Int32(field+".code", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["message"].(types.String); ok {
		if bVal, ok := bAttrs["message"].(types.String); ok {
			compare.Collect(&diffs, compare.String(field+".message", aVal, bVal))
		}
	}

	return diffs
}

// compareAwsPrivateLink compares aws_private_link objects
func compareAwsPrivateLink(field string, a, b types.Object) []compare.FieldDiff {
	if d := compare.ObjectNullCheck(field, a, b); d != nil {
		return []compare.FieldDiff{*d}
	}
	if a.IsNull() {
		return nil
	}

	var diffs []compare.FieldDiff
	aAttrs := a.Attributes()
	bAttrs := b.Attributes()

	if aVal, ok := aAttrs["allowed_principals"].(types.List); ok {
		if bVal, ok := bAttrs["allowed_principals"].(types.List); ok {
			compare.Collect(&diffs, compare.List(field+".allowed_principals", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["connect_console"].(types.Bool); ok {
		if bVal, ok := bAttrs["connect_console"].(types.Bool); ok {
			compare.Collect(&diffs, compare.Bool(field+".connect_console", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["enabled"].(types.Bool); ok {
		if bVal, ok := bAttrs["enabled"].(types.Bool); ok {
			compare.Collect(&diffs, compare.Bool(field+".enabled", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["status"].(types.Object); ok {
		if bVal, ok := bAttrs["status"].(types.Object); ok {
			compare.CollectAll(&diffs, compareAwsPrivateLinkStatus(field+".status", aVal, bVal))
		}
	}

	return diffs
}

// compareAwsPrivateLinkStatus compares aws_private_link_status objects
func compareAwsPrivateLinkStatus(field string, a, b types.Object) []compare.FieldDiff {
	if d := compare.ObjectNullCheck(field, a, b); d != nil {
		return []compare.FieldDiff{*d}
	}
	if a.IsNull() {
		return nil
	}

	var diffs []compare.FieldDiff
	aAttrs := a.Attributes()
	bAttrs := b.Attributes()

	if aVal, ok := aAttrs["console_port"].(types.Int32); ok {
		if bVal, ok := bAttrs["console_port"].(types.Int32); ok {
			compare.Collect(&diffs, compare.Int32(field+".console_port", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["created_at"].(types.String); ok {
		if bVal, ok := bAttrs["created_at"].(types.String); ok {
			compare.Collect(&diffs, compare.String(field+".created_at", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["deleted_at"].(types.String); ok {
		if bVal, ok := bAttrs["deleted_at"].(types.String); ok {
			compare.Collect(&diffs, compare.String(field+".deleted_at", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["kafka_api_node_base_port"].(types.Int32); ok {
		if bVal, ok := bAttrs["kafka_api_node_base_port"].(types.Int32); ok {
			compare.Collect(&diffs, compare.Int32(field+".kafka_api_node_base_port", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["kafka_api_seed_port"].(types.Int32); ok {
		if bVal, ok := bAttrs["kafka_api_seed_port"].(types.Int32); ok {
			compare.Collect(&diffs, compare.Int32(field+".kafka_api_seed_port", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["redpanda_proxy_node_base_port"].(types.Int32); ok {
		if bVal, ok := bAttrs["redpanda_proxy_node_base_port"].(types.Int32); ok {
			compare.Collect(&diffs, compare.Int32(field+".redpanda_proxy_node_base_port", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["redpanda_proxy_seed_port"].(types.Int32); ok {
		if bVal, ok := bAttrs["redpanda_proxy_seed_port"].(types.Int32); ok {
			compare.Collect(&diffs, compare.Int32(field+".redpanda_proxy_seed_port", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["schema_registry_seed_port"].(types.Int32); ok {
		if bVal, ok := bAttrs["schema_registry_seed_port"].(types.Int32); ok {
			compare.Collect(&diffs, compare.Int32(field+".schema_registry_seed_port", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["service_id"].(types.String); ok {
		if bVal, ok := bAttrs["service_id"].(types.String); ok {
			compare.Collect(&diffs, compare.String(field+".service_id", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["service_name"].(types.String); ok {
		if bVal, ok := bAttrs["service_name"].(types.String); ok {
			compare.Collect(&diffs, compare.String(field+".service_name", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["service_state"].(types.String); ok {
		if bVal, ok := bAttrs["service_state"].(types.String); ok {
			compare.Collect(&diffs, compare.String(field+".service_state", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["vpc_endpoint_connections"].(types.List); ok {
		if bVal, ok := bAttrs["vpc_endpoint_connections"].(types.List); ok {
			compare.Collect(&diffs, compare.List(field+".vpc_endpoint_connections", aVal, bVal))
		}
	}

	return diffs
}

// compareVpcEndpointConnection compares vpc_endpoint_connection objects
func compareVpcEndpointConnection(field string, a, b types.Object) []compare.FieldDiff {
	if d := compare.ObjectNullCheck(field, a, b); d != nil {
		return []compare.FieldDiff{*d}
	}
	if a.IsNull() {
		return nil
	}

	var diffs []compare.FieldDiff
	aAttrs := a.Attributes()
	bAttrs := b.Attributes()

	if aVal, ok := aAttrs["connection_id"].(types.String); ok {
		if bVal, ok := bAttrs["connection_id"].(types.String); ok {
			compare.Collect(&diffs, compare.String(field+".connection_id", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["created_at"].(types.String); ok {
		if bVal, ok := bAttrs["created_at"].(types.String); ok {
			compare.Collect(&diffs, compare.String(field+".created_at", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["dns_entries"].(types.List); ok {
		if bVal, ok := bAttrs["dns_entries"].(types.List); ok {
			compare.Collect(&diffs, compare.List(field+".dns_entries", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["id"].(types.String); ok {
		if bVal, ok := bAttrs["id"].(types.String); ok {
			compare.Collect(&diffs, compare.String(field+".id", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["load_balancer_arns"].(types.List); ok {
		if bVal, ok := bAttrs["load_balancer_arns"].(types.List); ok {
			compare.Collect(&diffs, compare.List(field+".load_balancer_arns", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["owner"].(types.String); ok {
		if bVal, ok := bAttrs["owner"].(types.String); ok {
			compare.Collect(&diffs, compare.String(field+".owner", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["state"].(types.String); ok {
		if bVal, ok := bAttrs["state"].(types.String); ok {
			compare.Collect(&diffs, compare.String(field+".state", aVal, bVal))
		}
	}

	return diffs
}

// compareDNSEntry compares dns_entry objects
func compareDNSEntry(field string, a, b types.Object) []compare.FieldDiff {
	if d := compare.ObjectNullCheck(field, a, b); d != nil {
		return []compare.FieldDiff{*d}
	}
	if a.IsNull() {
		return nil
	}

	var diffs []compare.FieldDiff
	aAttrs := a.Attributes()
	bAttrs := b.Attributes()

	if aVal, ok := aAttrs["dns_name"].(types.String); ok {
		if bVal, ok := bAttrs["dns_name"].(types.String); ok {
			compare.Collect(&diffs, compare.String(field+".dns_name", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["hosted_zone_id"].(types.String); ok {
		if bVal, ok := bAttrs["hosted_zone_id"].(types.String); ok {
			compare.Collect(&diffs, compare.String(field+".hosted_zone_id", aVal, bVal))
		}
	}

	return diffs
}

// compareGcpPrivateServiceConnect compares gcp_private_service_connect objects
func compareGcpPrivateServiceConnect(field string, a, b types.Object) []compare.FieldDiff {
	if d := compare.ObjectNullCheck(field, a, b); d != nil {
		return []compare.FieldDiff{*d}
	}
	if a.IsNull() {
		return nil
	}

	var diffs []compare.FieldDiff
	aAttrs := a.Attributes()
	bAttrs := b.Attributes()

	if aVal, ok := aAttrs["consumer_accept_list"].(types.List); ok {
		if bVal, ok := bAttrs["consumer_accept_list"].(types.List); ok {
			compare.Collect(&diffs, compare.List(field+".consumer_accept_list", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["enabled"].(types.Bool); ok {
		if bVal, ok := bAttrs["enabled"].(types.Bool); ok {
			compare.Collect(&diffs, compare.Bool(field+".enabled", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["global_access_enabled"].(types.Bool); ok {
		if bVal, ok := bAttrs["global_access_enabled"].(types.Bool); ok {
			compare.Collect(&diffs, compare.Bool(field+".global_access_enabled", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["source"].(types.String); ok {
		if bVal, ok := bAttrs["source"].(types.String); ok {
			compare.Collect(&diffs, compare.String(field+".source", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["status"].(types.Object); ok {
		if bVal, ok := bAttrs["status"].(types.Object); ok {
			compare.CollectAll(&diffs, compareGcpPrivateServiceConnectStatus(field+".status", aVal, bVal))
		}
	}

	return diffs
}

// compareGcpPrivateServiceConnectStatus compares gcp_private_service_connect_status objects
func compareGcpPrivateServiceConnectStatus(field string, a, b types.Object) []compare.FieldDiff {
	if d := compare.ObjectNullCheck(field, a, b); d != nil {
		return []compare.FieldDiff{*d}
	}
	if a.IsNull() {
		return nil
	}

	var diffs []compare.FieldDiff
	aAttrs := a.Attributes()
	bAttrs := b.Attributes()

	if aVal, ok := aAttrs["connected_endpoints"].(types.List); ok {
		if bVal, ok := bAttrs["connected_endpoints"].(types.List); ok {
			compare.Collect(&diffs, compare.List(field+".connected_endpoints", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["created_at"].(types.String); ok {
		if bVal, ok := bAttrs["created_at"].(types.String); ok {
			compare.Collect(&diffs, compare.String(field+".created_at", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["deleted_at"].(types.String); ok {
		if bVal, ok := bAttrs["deleted_at"].(types.String); ok {
			compare.Collect(&diffs, compare.String(field+".deleted_at", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["dns_a_records"].(types.List); ok {
		if bVal, ok := bAttrs["dns_a_records"].(types.List); ok {
			compare.Collect(&diffs, compare.List(field+".dns_a_records", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["kafka_api_node_base_port"].(types.Int32); ok {
		if bVal, ok := bAttrs["kafka_api_node_base_port"].(types.Int32); ok {
			compare.Collect(&diffs, compare.Int32(field+".kafka_api_node_base_port", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["kafka_api_seed_port"].(types.Int32); ok {
		if bVal, ok := bAttrs["kafka_api_seed_port"].(types.Int32); ok {
			compare.Collect(&diffs, compare.Int32(field+".kafka_api_seed_port", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["redpanda_proxy_node_base_port"].(types.Int32); ok {
		if bVal, ok := bAttrs["redpanda_proxy_node_base_port"].(types.Int32); ok {
			compare.Collect(&diffs, compare.Int32(field+".redpanda_proxy_node_base_port", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["redpanda_proxy_seed_port"].(types.Int32); ok {
		if bVal, ok := bAttrs["redpanda_proxy_seed_port"].(types.Int32); ok {
			compare.Collect(&diffs, compare.Int32(field+".redpanda_proxy_seed_port", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["schema_registry_seed_port"].(types.Int32); ok {
		if bVal, ok := bAttrs["schema_registry_seed_port"].(types.Int32); ok {
			compare.Collect(&diffs, compare.Int32(field+".schema_registry_seed_port", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["seed_hostname"].(types.String); ok {
		if bVal, ok := bAttrs["seed_hostname"].(types.String); ok {
			compare.Collect(&diffs, compare.String(field+".seed_hostname", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["service_attachment"].(types.String); ok {
		if bVal, ok := bAttrs["service_attachment"].(types.String); ok {
			compare.Collect(&diffs, compare.String(field+".service_attachment", aVal, bVal))
		}
	}

	return diffs
}

// compareConnectedEndpoint compares connected_endpoint objects
func compareConnectedEndpoint(field string, a, b types.Object) []compare.FieldDiff {
	if d := compare.ObjectNullCheck(field, a, b); d != nil {
		return []compare.FieldDiff{*d}
	}
	if a.IsNull() {
		return nil
	}

	var diffs []compare.FieldDiff
	aAttrs := a.Attributes()
	bAttrs := b.Attributes()

	if aVal, ok := aAttrs["connection_id"].(types.String); ok {
		if bVal, ok := bAttrs["connection_id"].(types.String); ok {
			compare.Collect(&diffs, compare.String(field+".connection_id", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["consumer_network"].(types.String); ok {
		if bVal, ok := bAttrs["consumer_network"].(types.String); ok {
			compare.Collect(&diffs, compare.String(field+".consumer_network", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["endpoint"].(types.String); ok {
		if bVal, ok := bAttrs["endpoint"].(types.String); ok {
			compare.Collect(&diffs, compare.String(field+".endpoint", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["status"].(types.String); ok {
		if bVal, ok := bAttrs["status"].(types.String); ok {
			compare.Collect(&diffs, compare.String(field+".status", aVal, bVal))
		}
	}

	return diffs
}

// compareAzurePrivateLink compares azure_private_link objects
func compareAzurePrivateLink(field string, a, b types.Object) []compare.FieldDiff {
	if d := compare.ObjectNullCheck(field, a, b); d != nil {
		return []compare.FieldDiff{*d}
	}
	if a.IsNull() {
		return nil
	}

	var diffs []compare.FieldDiff
	aAttrs := a.Attributes()
	bAttrs := b.Attributes()

	if aVal, ok := aAttrs["allowed_subscriptions"].(types.List); ok {
		if bVal, ok := bAttrs["allowed_subscriptions"].(types.List); ok {
			compare.Collect(&diffs, compare.List(field+".allowed_subscriptions", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["connect_console"].(types.Bool); ok {
		if bVal, ok := bAttrs["connect_console"].(types.Bool); ok {
			compare.Collect(&diffs, compare.Bool(field+".connect_console", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["enabled"].(types.Bool); ok {
		if bVal, ok := bAttrs["enabled"].(types.Bool); ok {
			compare.Collect(&diffs, compare.Bool(field+".enabled", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["status"].(types.Object); ok {
		if bVal, ok := bAttrs["status"].(types.Object); ok {
			compare.CollectAll(&diffs, compareAzurePrivateLinkStatus(field+".status", aVal, bVal))
		}
	}

	return diffs
}

// compareAzurePrivateLinkStatus compares azure_private_link_status objects
func compareAzurePrivateLinkStatus(field string, a, b types.Object) []compare.FieldDiff {
	if d := compare.ObjectNullCheck(field, a, b); d != nil {
		return []compare.FieldDiff{*d}
	}
	if a.IsNull() {
		return nil
	}

	var diffs []compare.FieldDiff
	aAttrs := a.Attributes()
	bAttrs := b.Attributes()

	if aVal, ok := aAttrs["approved_subscriptions"].(types.List); ok {
		if bVal, ok := bAttrs["approved_subscriptions"].(types.List); ok {
			compare.Collect(&diffs, compare.List(field+".approved_subscriptions", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["console_port"].(types.Int32); ok {
		if bVal, ok := bAttrs["console_port"].(types.Int32); ok {
			compare.Collect(&diffs, compare.Int32(field+".console_port", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["created_at"].(types.String); ok {
		if bVal, ok := bAttrs["created_at"].(types.String); ok {
			compare.Collect(&diffs, compare.String(field+".created_at", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["deleted_at"].(types.String); ok {
		if bVal, ok := bAttrs["deleted_at"].(types.String); ok {
			compare.Collect(&diffs, compare.String(field+".deleted_at", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["dns_a_record"].(types.String); ok {
		if bVal, ok := bAttrs["dns_a_record"].(types.String); ok {
			compare.Collect(&diffs, compare.String(field+".dns_a_record", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["kafka_api_node_base_port"].(types.Int32); ok {
		if bVal, ok := bAttrs["kafka_api_node_base_port"].(types.Int32); ok {
			compare.Collect(&diffs, compare.Int32(field+".kafka_api_node_base_port", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["kafka_api_seed_port"].(types.Int32); ok {
		if bVal, ok := bAttrs["kafka_api_seed_port"].(types.Int32); ok {
			compare.Collect(&diffs, compare.Int32(field+".kafka_api_seed_port", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["private_endpoint_connections"].(types.List); ok {
		if bVal, ok := bAttrs["private_endpoint_connections"].(types.List); ok {
			compare.Collect(&diffs, compare.List(field+".private_endpoint_connections", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["redpanda_proxy_node_base_port"].(types.Int32); ok {
		if bVal, ok := bAttrs["redpanda_proxy_node_base_port"].(types.Int32); ok {
			compare.Collect(&diffs, compare.Int32(field+".redpanda_proxy_node_base_port", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["redpanda_proxy_seed_port"].(types.Int32); ok {
		if bVal, ok := bAttrs["redpanda_proxy_seed_port"].(types.Int32); ok {
			compare.Collect(&diffs, compare.Int32(field+".redpanda_proxy_seed_port", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["schema_registry_seed_port"].(types.Int32); ok {
		if bVal, ok := bAttrs["schema_registry_seed_port"].(types.Int32); ok {
			compare.Collect(&diffs, compare.Int32(field+".schema_registry_seed_port", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["service_id"].(types.String); ok {
		if bVal, ok := bAttrs["service_id"].(types.String); ok {
			compare.Collect(&diffs, compare.String(field+".service_id", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["service_name"].(types.String); ok {
		if bVal, ok := bAttrs["service_name"].(types.String); ok {
			compare.Collect(&diffs, compare.String(field+".service_name", aVal, bVal))
		}
	}

	return diffs
}

// compareAzureEndpointConnection compares azure_endpoint_connection objects
func compareAzureEndpointConnection(field string, a, b types.Object) []compare.FieldDiff {
	if d := compare.ObjectNullCheck(field, a, b); d != nil {
		return []compare.FieldDiff{*d}
	}
	if a.IsNull() {
		return nil
	}

	var diffs []compare.FieldDiff
	aAttrs := a.Attributes()
	bAttrs := b.Attributes()

	if aVal, ok := aAttrs["connection_id"].(types.String); ok {
		if bVal, ok := bAttrs["connection_id"].(types.String); ok {
			compare.Collect(&diffs, compare.String(field+".connection_id", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["connection_name"].(types.String); ok {
		if bVal, ok := bAttrs["connection_name"].(types.String); ok {
			compare.Collect(&diffs, compare.String(field+".connection_name", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["created_at"].(types.String); ok {
		if bVal, ok := bAttrs["created_at"].(types.String); ok {
			compare.Collect(&diffs, compare.String(field+".created_at", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["private_endpoint_id"].(types.String); ok {
		if bVal, ok := bAttrs["private_endpoint_id"].(types.String); ok {
			compare.Collect(&diffs, compare.String(field+".private_endpoint_id", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["private_endpoint_name"].(types.String); ok {
		if bVal, ok := bAttrs["private_endpoint_name"].(types.String); ok {
			compare.Collect(&diffs, compare.String(field+".private_endpoint_name", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["status"].(types.String); ok {
		if bVal, ok := bAttrs["status"].(types.String); ok {
			compare.Collect(&diffs, compare.String(field+".status", aVal, bVal))
		}
	}

	return diffs
}

// compareKafkaAPI compares kafka_api objects
func compareKafkaAPI(field string, a, b types.Object) []compare.FieldDiff {
	if d := compare.ObjectNullCheck(field, a, b); d != nil {
		return []compare.FieldDiff{*d}
	}
	if a.IsNull() {
		return nil
	}

	var diffs []compare.FieldDiff
	aAttrs := a.Attributes()
	bAttrs := b.Attributes()

	if aVal, ok := aAttrs["mtls"].(types.Object); ok {
		if bVal, ok := bAttrs["mtls"].(types.Object); ok {
			compare.CollectAll(&diffs, compareMtls(field+".mtls", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["seed_brokers"].(types.List); ok {
		if bVal, ok := bAttrs["seed_brokers"].(types.List); ok {
			compare.Collect(&diffs, compare.List(field+".seed_brokers", aVal, bVal))
		}
	}

	return diffs
}

// compareMtls compares mtls objects
func compareMtls(field string, a, b types.Object) []compare.FieldDiff {
	if d := compare.ObjectNullCheck(field, a, b); d != nil {
		return []compare.FieldDiff{*d}
	}
	if a.IsNull() {
		return nil
	}

	var diffs []compare.FieldDiff
	aAttrs := a.Attributes()
	bAttrs := b.Attributes()

	if aVal, ok := aAttrs["ca_certificates_pem"].(types.List); ok {
		if bVal, ok := bAttrs["ca_certificates_pem"].(types.List); ok {
			compare.Collect(&diffs, compare.List(field+".ca_certificates_pem", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["enabled"].(types.Bool); ok {
		if bVal, ok := bAttrs["enabled"].(types.Bool); ok {
			compare.Collect(&diffs, compare.Bool(field+".enabled", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["principal_mapping_rules"].(types.List); ok {
		if bVal, ok := bAttrs["principal_mapping_rules"].(types.List); ok {
			compare.Collect(&diffs, compare.List(field+".principal_mapping_rules", aVal, bVal))
		}
	}

	return diffs
}

// compareHTTPProxy compares http_proxy objects
func compareHTTPProxy(field string, a, b types.Object) []compare.FieldDiff {
	if d := compare.ObjectNullCheck(field, a, b); d != nil {
		return []compare.FieldDiff{*d}
	}
	if a.IsNull() {
		return nil
	}

	var diffs []compare.FieldDiff
	aAttrs := a.Attributes()
	bAttrs := b.Attributes()

	if aVal, ok := aAttrs["mtls"].(types.Object); ok {
		if bVal, ok := bAttrs["mtls"].(types.Object); ok {
			compare.CollectAll(&diffs, compareMtls(field+".mtls", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["url"].(types.String); ok {
		if bVal, ok := bAttrs["url"].(types.String); ok {
			compare.Collect(&diffs, compare.String(field+".url", aVal, bVal))
		}
	}

	return diffs
}

// compareSchemaRegistry compares schema_registry objects
func compareSchemaRegistry(field string, a, b types.Object) []compare.FieldDiff {
	if d := compare.ObjectNullCheck(field, a, b); d != nil {
		return []compare.FieldDiff{*d}
	}
	if a.IsNull() {
		return nil
	}

	var diffs []compare.FieldDiff
	aAttrs := a.Attributes()
	bAttrs := b.Attributes()

	if aVal, ok := aAttrs["mtls"].(types.Object); ok {
		if bVal, ok := bAttrs["mtls"].(types.Object); ok {
			compare.CollectAll(&diffs, compareMtls(field+".mtls", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["url"].(types.String); ok {
		if bVal, ok := bAttrs["url"].(types.String); ok {
			compare.Collect(&diffs, compare.String(field+".url", aVal, bVal))
		}
	}

	return diffs
}

// compareKafkaConnect compares kafka_connect objects
func compareKafkaConnect(field string, a, b types.Object) []compare.FieldDiff {
	if d := compare.ObjectNullCheck(field, a, b); d != nil {
		return []compare.FieldDiff{*d}
	}
	if a.IsNull() {
		return nil
	}

	var diffs []compare.FieldDiff
	aAttrs := a.Attributes()
	bAttrs := b.Attributes()

	if aVal, ok := aAttrs["enabled"].(types.Bool); ok {
		if bVal, ok := bAttrs["enabled"].(types.Bool); ok {
			compare.Collect(&diffs, compare.Bool(field+".enabled", aVal, bVal))
		}
	}

	return diffs
}

// compareCustomerManagedResources compares customer_managed_resources objects
func compareCustomerManagedResources(field string, a, b types.Object) []compare.FieldDiff {
	if d := compare.ObjectNullCheck(field, a, b); d != nil {
		return []compare.FieldDiff{*d}
	}
	if a.IsNull() {
		return nil
	}

	var diffs []compare.FieldDiff
	aAttrs := a.Attributes()
	bAttrs := b.Attributes()

	if aVal, ok := aAttrs["aws"].(types.Object); ok {
		if bVal, ok := bAttrs["aws"].(types.Object); ok {
			compare.CollectAll(&diffs, compareAwsCmr(field+".aws", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["gcp"].(types.Object); ok {
		if bVal, ok := bAttrs["gcp"].(types.Object); ok {
			compare.CollectAll(&diffs, compareGcpCmr(field+".gcp", aVal, bVal))
		}
	}

	return diffs
}

// compareAwsCmr compares aws_cmr objects
func compareAwsCmr(field string, a, b types.Object) []compare.FieldDiff {
	if d := compare.ObjectNullCheck(field, a, b); d != nil {
		return []compare.FieldDiff{*d}
	}
	if a.IsNull() {
		return nil
	}

	var diffs []compare.FieldDiff
	aAttrs := a.Attributes()
	bAttrs := b.Attributes()

	if aVal, ok := aAttrs["agent_instance_profile"].(types.Object); ok {
		if bVal, ok := bAttrs["agent_instance_profile"].(types.Object); ok {
			compare.CollectAll(&diffs, compareArnContainer(field+".agent_instance_profile", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["cloud_storage_bucket"].(types.Object); ok {
		if bVal, ok := bAttrs["cloud_storage_bucket"].(types.Object); ok {
			compare.CollectAll(&diffs, compareArnContainer(field+".cloud_storage_bucket", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["cluster_security_group"].(types.Object); ok {
		if bVal, ok := bAttrs["cluster_security_group"].(types.Object); ok {
			compare.CollectAll(&diffs, compareArnContainer(field+".cluster_security_group", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["connectors_node_group_instance_profile"].(types.Object); ok {
		if bVal, ok := bAttrs["connectors_node_group_instance_profile"].(types.Object); ok {
			compare.CollectAll(&diffs, compareArnContainer(field+".connectors_node_group_instance_profile", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["connectors_security_group"].(types.Object); ok {
		if bVal, ok := bAttrs["connectors_security_group"].(types.Object); ok {
			compare.CollectAll(&diffs, compareArnContainer(field+".connectors_security_group", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["k8s_cluster_role"].(types.Object); ok {
		if bVal, ok := bAttrs["k8s_cluster_role"].(types.Object); ok {
			compare.CollectAll(&diffs, compareArnContainer(field+".k8s_cluster_role", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["node_security_group"].(types.Object); ok {
		if bVal, ok := bAttrs["node_security_group"].(types.Object); ok {
			compare.CollectAll(&diffs, compareArnContainer(field+".node_security_group", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["permissions_boundary_policy"].(types.Object); ok {
		if bVal, ok := bAttrs["permissions_boundary_policy"].(types.Object); ok {
			compare.CollectAll(&diffs, compareArnContainer(field+".permissions_boundary_policy", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["redpanda_agent_security_group"].(types.Object); ok {
		if bVal, ok := bAttrs["redpanda_agent_security_group"].(types.Object); ok {
			compare.CollectAll(&diffs, compareArnContainer(field+".redpanda_agent_security_group", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["redpanda_node_group_instance_profile"].(types.Object); ok {
		if bVal, ok := bAttrs["redpanda_node_group_instance_profile"].(types.Object); ok {
			compare.CollectAll(&diffs, compareArnContainer(field+".redpanda_node_group_instance_profile", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["redpanda_node_group_security_group"].(types.Object); ok {
		if bVal, ok := bAttrs["redpanda_node_group_security_group"].(types.Object); ok {
			compare.CollectAll(&diffs, compareArnContainer(field+".redpanda_node_group_security_group", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["utility_node_group_instance_profile"].(types.Object); ok {
		if bVal, ok := bAttrs["utility_node_group_instance_profile"].(types.Object); ok {
			compare.CollectAll(&diffs, compareArnContainer(field+".utility_node_group_instance_profile", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["utility_security_group"].(types.Object); ok {
		if bVal, ok := bAttrs["utility_security_group"].(types.Object); ok {
			compare.CollectAll(&diffs, compareArnContainer(field+".utility_security_group", aVal, bVal))
		}
	}

	return diffs
}

// compareArnContainer compares arn_container objects
func compareArnContainer(field string, a, b types.Object) []compare.FieldDiff {
	if d := compare.ObjectNullCheck(field, a, b); d != nil {
		return []compare.FieldDiff{*d}
	}
	if a.IsNull() {
		return nil
	}

	var diffs []compare.FieldDiff
	aAttrs := a.Attributes()
	bAttrs := b.Attributes()

	if aVal, ok := aAttrs["arn"].(types.String); ok {
		if bVal, ok := bAttrs["arn"].(types.String); ok {
			compare.Collect(&diffs, compare.String(field+".arn", aVal, bVal))
		}
	}

	return diffs
}

// compareGcpCmr compares gcp_cmr objects
func compareGcpCmr(field string, a, b types.Object) []compare.FieldDiff {
	if d := compare.ObjectNullCheck(field, a, b); d != nil {
		return []compare.FieldDiff{*d}
	}
	if a.IsNull() {
		return nil
	}

	var diffs []compare.FieldDiff
	aAttrs := a.Attributes()
	bAttrs := b.Attributes()

	if aVal, ok := aAttrs["agent_service_account"].(types.Object); ok {
		if bVal, ok := bAttrs["agent_service_account"].(types.Object); ok {
			compare.CollectAll(&diffs, compareGcpServiceAccount(field+".agent_service_account", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["connector_service_account"].(types.Object); ok {
		if bVal, ok := bAttrs["connector_service_account"].(types.Object); ok {
			compare.CollectAll(&diffs, compareGcpServiceAccount(field+".connector_service_account", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["console_service_account"].(types.Object); ok {
		if bVal, ok := bAttrs["console_service_account"].(types.Object); ok {
			compare.CollectAll(&diffs, compareGcpServiceAccount(field+".console_service_account", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["gke_service_account"].(types.Object); ok {
		if bVal, ok := bAttrs["gke_service_account"].(types.Object); ok {
			compare.CollectAll(&diffs, compareGcpServiceAccount(field+".gke_service_account", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["psc_nat_subnet_name"].(types.String); ok {
		if bVal, ok := bAttrs["psc_nat_subnet_name"].(types.String); ok {
			compare.Collect(&diffs, compare.String(field+".psc_nat_subnet_name", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["redpanda_cluster_service_account"].(types.Object); ok {
		if bVal, ok := bAttrs["redpanda_cluster_service_account"].(types.Object); ok {
			compare.CollectAll(&diffs, compareGcpServiceAccount(field+".redpanda_cluster_service_account", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["subnet"].(types.Object); ok {
		if bVal, ok := bAttrs["subnet"].(types.Object); ok {
			compare.CollectAll(&diffs, compareGcpSubnet(field+".subnet", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["tiered_storage_bucket"].(types.Object); ok {
		if bVal, ok := bAttrs["tiered_storage_bucket"].(types.Object); ok {
			compare.CollectAll(&diffs, compareGcpBucket(field+".tiered_storage_bucket", aVal, bVal))
		}
	}

	return diffs
}

// compareGcpSubnet compares gcp_subnet objects
func compareGcpSubnet(field string, a, b types.Object) []compare.FieldDiff {
	if d := compare.ObjectNullCheck(field, a, b); d != nil {
		return []compare.FieldDiff{*d}
	}
	if a.IsNull() {
		return nil
	}

	var diffs []compare.FieldDiff
	aAttrs := a.Attributes()
	bAttrs := b.Attributes()

	if aVal, ok := aAttrs["k8s_master_ipv4_range"].(types.String); ok {
		if bVal, ok := bAttrs["k8s_master_ipv4_range"].(types.String); ok {
			compare.Collect(&diffs, compare.String(field+".k8s_master_ipv4_range", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["name"].(types.String); ok {
		if bVal, ok := bAttrs["name"].(types.String); ok {
			compare.Collect(&diffs, compare.String(field+".name", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["secondary_ipv4_range_pods"].(types.Object); ok {
		if bVal, ok := bAttrs["secondary_ipv4_range_pods"].(types.Object); ok {
			compare.CollectAll(&diffs, compareGcpSecondaryIPv4Range(field+".secondary_ipv4_range_pods", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["secondary_ipv4_range_services"].(types.Object); ok {
		if bVal, ok := bAttrs["secondary_ipv4_range_services"].(types.Object); ok {
			compare.CollectAll(&diffs, compareGcpSecondaryIPv4Range(field+".secondary_ipv4_range_services", aVal, bVal))
		}
	}

	return diffs
}

// compareGcpSecondaryIPv4Range compares gcp_secondary_i_pv4_range objects
func compareGcpSecondaryIPv4Range(field string, a, b types.Object) []compare.FieldDiff {
	if d := compare.ObjectNullCheck(field, a, b); d != nil {
		return []compare.FieldDiff{*d}
	}
	if a.IsNull() {
		return nil
	}

	var diffs []compare.FieldDiff
	aAttrs := a.Attributes()
	bAttrs := b.Attributes()

	if aVal, ok := aAttrs["name"].(types.String); ok {
		if bVal, ok := bAttrs["name"].(types.String); ok {
			compare.Collect(&diffs, compare.String(field+".name", aVal, bVal))
		}
	}

	return diffs
}

// compareGcpServiceAccount compares gcp_service_account objects
func compareGcpServiceAccount(field string, a, b types.Object) []compare.FieldDiff {
	if d := compare.ObjectNullCheck(field, a, b); d != nil {
		return []compare.FieldDiff{*d}
	}
	if a.IsNull() {
		return nil
	}

	var diffs []compare.FieldDiff
	aAttrs := a.Attributes()
	bAttrs := b.Attributes()

	if aVal, ok := aAttrs["email"].(types.String); ok {
		if bVal, ok := bAttrs["email"].(types.String); ok {
			compare.Collect(&diffs, compare.String(field+".email", aVal, bVal))
		}
	}

	return diffs
}

// compareGcpBucket compares gcp_bucket objects
func compareGcpBucket(field string, a, b types.Object) []compare.FieldDiff {
	if d := compare.ObjectNullCheck(field, a, b); d != nil {
		return []compare.FieldDiff{*d}
	}
	if a.IsNull() {
		return nil
	}

	var diffs []compare.FieldDiff
	aAttrs := a.Attributes()
	bAttrs := b.Attributes()

	if aVal, ok := aAttrs["name"].(types.String); ok {
		if bVal, ok := bAttrs["name"].(types.String); ok {
			compare.Collect(&diffs, compare.String(field+".name", aVal, bVal))
		}
	}

	return diffs
}

// comparePrometheus compares prometheus objects
func comparePrometheus(field string, a, b types.Object) []compare.FieldDiff {
	if d := compare.ObjectNullCheck(field, a, b); d != nil {
		return []compare.FieldDiff{*d}
	}
	if a.IsNull() {
		return nil
	}

	var diffs []compare.FieldDiff
	aAttrs := a.Attributes()
	bAttrs := b.Attributes()

	if aVal, ok := aAttrs["url"].(types.String); ok {
		if bVal, ok := bAttrs["url"].(types.String); ok {
			compare.Collect(&diffs, compare.String(field+".url", aVal, bVal))
		}
	}

	return diffs
}

// compareRedpandaConsole compares redpanda_console objects
func compareRedpandaConsole(field string, a, b types.Object) []compare.FieldDiff {
	if d := compare.ObjectNullCheck(field, a, b); d != nil {
		return []compare.FieldDiff{*d}
	}
	if a.IsNull() {
		return nil
	}

	var diffs []compare.FieldDiff
	aAttrs := a.Attributes()
	bAttrs := b.Attributes()

	if aVal, ok := aAttrs["url"].(types.String); ok {
		if bVal, ok := bAttrs["url"].(types.String); ok {
			compare.Collect(&diffs, compare.String(field+".url", aVal, bVal))
		}
	}

	return diffs
}

// compareMaintenanceWindowConfig compares maintenance_window_config objects
func compareMaintenanceWindowConfig(field string, a, b types.Object) []compare.FieldDiff {
	if d := compare.ObjectNullCheck(field, a, b); d != nil {
		return []compare.FieldDiff{*d}
	}
	if a.IsNull() {
		return nil
	}

	var diffs []compare.FieldDiff
	aAttrs := a.Attributes()
	bAttrs := b.Attributes()

	if aVal, ok := aAttrs["anytime"].(types.Bool); ok {
		if bVal, ok := bAttrs["anytime"].(types.Bool); ok {
			compare.Collect(&diffs, compare.Bool(field+".anytime", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["day_hour"].(types.Object); ok {
		if bVal, ok := bAttrs["day_hour"].(types.Object); ok {
			compare.CollectAll(&diffs, compareDayHour(field+".day_hour", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["unspecified"].(types.Bool); ok {
		if bVal, ok := bAttrs["unspecified"].(types.Bool); ok {
			compare.Collect(&diffs, compare.Bool(field+".unspecified", aVal, bVal))
		}
	}

	return diffs
}

// compareDayHour compares day_hour objects
func compareDayHour(field string, a, b types.Object) []compare.FieldDiff {
	if d := compare.ObjectNullCheck(field, a, b); d != nil {
		return []compare.FieldDiff{*d}
	}
	if a.IsNull() {
		return nil
	}

	var diffs []compare.FieldDiff
	aAttrs := a.Attributes()
	bAttrs := b.Attributes()

	if aVal, ok := aAttrs["day_of_week"].(types.String); ok {
		if bVal, ok := bAttrs["day_of_week"].(types.String); ok {
			compare.Collect(&diffs, compare.String(field+".day_of_week", aVal, bVal))
		}
	}
	if aVal, ok := aAttrs["hour_of_day"].(types.Int32); ok {
		if bVal, ok := bAttrs["hour_of_day"].(types.Int32); ok {
			compare.Collect(&diffs, compare.Int32(field+".hour_of_day", aVal, bVal))
		}
	}

	return diffs
}

// compareClusterConfiguration compares cluster_configuration objects
func compareClusterConfiguration(field string, a, b types.Object) []compare.FieldDiff {
	if d := compare.ObjectNullCheck(field, a, b); d != nil {
		return []compare.FieldDiff{*d}
	}
	if a.IsNull() {
		return nil
	}

	var diffs []compare.FieldDiff
	aAttrs := a.Attributes()
	bAttrs := b.Attributes()

	if aVal, ok := aAttrs["custom_properties_json"].(types.String); ok {
		if bVal, ok := bAttrs["custom_properties_json"].(types.String); ok {
			compare.Collect(&diffs, compare.String(field+".custom_properties_json", aVal, bVal))
		}
	}

	return diffs
}
