// Code generated by schemagen. DO NOT EDIT.

// Copyright 2023 Redpanda Data, Inc.
//
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

package acl

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

// ResourceACLSchema returns the Terraform schema for the acl resource.
func ResourceACLSchema(_ context.Context) schema.Schema {
	return schema.Schema{
		Description: "Acl resource",
		Attributes: map[string]schema.Attribute{
			"cluster_api_url": schema.StringAttribute{
				Description:   "The cluster API URL. Changing this will prevent deletion of the resource on the existing cluster. It is generally a better idea to delete an existing resource and create a new one than to change this value unless you are planning to do state imports",
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},

			"host": schema.StringAttribute{
				Description:   "The host address to use for this ACL. To allow a principal access from multiple hosts, you must create an ACL for each host.",
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},

			"operation": schema.StringAttribute{
				Description:   "The operation type that shall be allowed or denied (e.g READ)",
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Validators:    aclOperationValidator(),
			},

			"permission_type": schema.StringAttribute{
				Description:   "The permission type. It determines whether the operation should be ALLOWED or DENIED. Must be one of (enum values): 2, 3.",
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Validators:    aclPermissionTypeValidator(),
			},

			"principal": schema.StringAttribute{
				Description:   "The principal to apply this ACL for (e.g., User:alice or RedpandaRole:admin)",
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},

			"resource_name": schema.StringAttribute{
				Description:   "The name of the resource this ACL entry will be on",
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},

			"resource_pattern_type": schema.StringAttribute{
				Description:   "The pattern type of the resource. It determines the strategy how the provided resource name is matched (LITERAL, MATCH, PREFIXED, etc ...) against the actual resource names. Must be one of (enum values): 3, 4.",
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Validators:    aclResourcePatternTypeValidator(),
			},

			"resource_type": schema.StringAttribute{
				Description:   "The type of the resource (TOPIC, GROUP, etc...) this ACL shall target",
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Validators:    aclResourceTypeValidator(),
			},

			"allow_deletion": schema.BoolAttribute{
				Description: "When set to true, allows the resource to be removed from state even if the cluster is unreachable",
				Optional:    true,
				Computed:    true,
				Default:     booldefault.StaticBool(false),
			},

			"id": schema.StringAttribute{
				Description:   "Unique identifier of the resource.",
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
		},
		Version: 1,
	}
}
