// Copyright 2026 Redpanda Data, Inc.
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

package fileutil

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func TestLicenseHeader_CurrentYearSingleBlankLine(t *testing.T) {
	h := LicenseHeader()
	want := fmt.Sprintf("// Copyright %d Redpanda Data, Inc.\n//\n//    Licensed", time.Now().Year())
	if !strings.HasPrefix(h, want) {
		t.Fatalf("header prefix = %q, want %q", h[:len(want)], want)
	}
	if strings.Contains(h, "//\n//\n") {
		t.Fatal("header carries a double blank comment line")
	}
	if !strings.HasSuffix(h, "limitations under the License.\n\n") {
		t.Fatalf("header must end with the license line and one blank line, got %q", h[len(h)-40:])
	}
}

func TestLicenseHeaderYear_Pinned(t *testing.T) {
	if got := LicenseHeaderYear(2023); !strings.HasPrefix(got, "// Copyright 2023 Redpanda Data, Inc.\n") {
		t.Fatalf("got %q", strings.SplitN(got, "\n", 2)[0])
	}
}

func TestPreserveHeaderYear(t *testing.T) {
	src := []byte(LicenseHeader() + "package x\n")
	genSrc := []byte("// Code generated by schemagen. DO NOT EDIT.\n\n" + LicenseHeader() + "package x\n")
	cases := []struct {
		name     string
		existing string
		wantYear string
	}{
		{"existing file keeps its year", "// Copyright 2024 Redpanda Data, Inc.\n//\n//    Licensed\n\npackage x\n", "2024"},
		{"existing file with double blank keeps its year", "// Copyright 2023 Redpanda Data, Inc.\n//\n//\n//    Licensed\n\npackage x\n", "2023"},
		{"missing file uses current year", "", fmt.Sprint(time.Now().Year())},
		{"existing file without header uses current year", "package x\n", fmt.Sprint(time.Now().Year())},
		{"schemagen shape: header after the generated marker keeps its year", "// Code generated by schemagen. DO NOT EDIT.\n\n// Copyright 2023 Redpanda Data, Inc.\n//\n//\n//    Licensed\n\npackage x\n", "2023"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			path := filepath.Join(t.TempDir(), "out.go")
			if tc.existing != "" {
				if err := os.WriteFile(path, []byte(tc.existing), 0o600); err != nil {
					t.Fatal(err)
				}
			}
			in := src
			if strings.HasPrefix(tc.existing, "// Code generated") {
				in = genSrc
			}
			got := string(PreserveHeaderYear(path, in))
			got = strings.TrimPrefix(got, "// Code generated by schemagen. DO NOT EDIT.\n\n")
			wantFirst := "// Copyright " + tc.wantYear + " Redpanda Data, Inc.\n"
			if !strings.HasPrefix(got, wantFirst) {
				t.Fatalf("first line = %q, want %q", strings.SplitN(got, "\n", 2)[0], strings.TrimSpace(wantFirst))
			}
			if strings.Count(got, "Copyright") != 1 {
				t.Fatalf("expected exactly one Copyright line, got %d", strings.Count(got, "Copyright"))
			}
			if !strings.HasSuffix(got, "package x\n") {
				t.Fatal("body was altered")
			}
		})
	}
}
