// Code generated by schemagen. DO NOT EDIT.

// Copyright 2026 Redpanda Data, Inc.
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

// Package cloudprovideraccess contains the model for the cloudprovideraccess resource.
package cloudprovideraccess

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

// ResourceModel represents the Terraform schema for the cloudprovideraccess resource.
type ResourceModel struct {
	AWS           types.Object `tfsdk:"aws"`
	CloudProvider types.String `tfsdk:"cloud_provider"`
	ID            types.String `tfsdk:"id"`
	Name          types.String `tfsdk:"name"`
	State         types.String `tfsdk:"state"`
}

// --- Nested typed structs (one per nested message in the proto tree) ---

// AWSModel mirrors the nested "aws" attribute. Use the As/To
// converters on the parent struct to move between types.Object and this
// typed form.
type AWSModel struct {
	RoleARN    types.String `tfsdk:"role_arn"`
	ExternalID types.String `tfsdk:"external_id"`
}

// --- AttrType tables for nested types (consumed by types.ObjectValueFrom / ObjectNull) ---

// AWSAttrTypes returns the attr.Type map for the "aws" nested
// attribute.
func AWSAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"role_arn":    types.StringType,
		"external_id": types.StringType,
	}
}

// --- Root-level converters (types.Object ⇄ typed struct ergonomics) ---

// AsAWS converts the root aws attribute from
// types.Object into its typed form. Returns (nil, nil) when the object is
// null or unknown. Use this when you want typed field access without
// manually unpacking .Attributes().
func (m *ResourceModel) AsAWS(ctx context.Context) (*AWSModel, diag.Diagnostics) {
	if m == nil || m.AWS.IsNull() || m.AWS.IsUnknown() {
		return nil, nil
	}
	var out AWSModel
	d := m.AWS.As(ctx, &out, basetypes.ObjectAsOptions{})
	return &out, d
}

// AWSToObject encodes a typed struct back into the
// types.Object shape expected by the framework. A nil receiver returns
// types.ObjectNull with the correct attribute types.
func AWSToObject(ctx context.Context, v *AWSModel) (types.Object, diag.Diagnostics) {
	if v == nil {
		return types.ObjectNull(AWSAttrTypes()), nil
	}
	return types.ObjectValueFrom(ctx, AWSAttrTypes(), v)
}

// GenerateMinimalResourceModel returns a *ResourceModel populated only with
// the supplied id; every other field is at its typed null (or its
// declared minimal_default). Used by resources that need to persist a
// partial state when Create / Read returns mid-flight.
func GenerateMinimalResourceModel(id types.String) *ResourceModel {
	return &ResourceModel{
		AWS:           types.ObjectNull(AWSAttrTypes()),
		CloudProvider: types.StringNull(),
		ID:            id,
		Name:          types.StringNull(),
		State:         types.StringNull(),
	}
}
