// Code generated by schemagen. DO NOT EDIT.

// Copyright 2023 Redpanda Data, Inc.
//
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

// Package shadowlink contains the model for the shadowlink resource.
package shadowlink

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

// ResourceModel represents the Terraform schema for the shadowlink resource.
type ResourceModel struct {
	AllowDeletion             types.Bool     `tfsdk:"allow_deletion"`
	ClientOptions             types.Object   `tfsdk:"client_options"`
	ConsumerOffsetSyncOptions types.Object   `tfsdk:"consumer_offset_sync_options"`
	ID                        types.String   `tfsdk:"id"`
	Name                      types.String   `tfsdk:"name"`
	Reason                    types.String   `tfsdk:"reason"`
	SchemaRegistrySyncOptions types.Object   `tfsdk:"schema_registry_sync_options"`
	SecuritySyncOptions       types.Object   `tfsdk:"security_sync_options"`
	ShadowRedpandaID          types.String   `tfsdk:"shadow_redpanda_id"`
	SourceRedpandaID          types.String   `tfsdk:"source_redpanda_id"`
	State                     types.String   `tfsdk:"state"`
	Timeouts                  timeouts.Value `tfsdk:"timeouts"`
	TopicMetadataSyncOptions  types.Object   `tfsdk:"topic_metadata_sync_options"`
}

// --- Nested typed structs (one per nested message in the proto tree) ---

// ClientOptionsModel mirrors the nested "client_options" attribute. Use the As/To
// converters on the parent struct to move between types.Object and this
// typed form.
type ClientOptionsModel struct {
	AuthenticationConfiguration     types.Object `tfsdk:"authentication_configuration"`
	BootstrapServers                types.List   `tfsdk:"bootstrap_servers"`
	ConnectionTimeoutMs             types.Int32  `tfsdk:"connection_timeout_ms"`
	FetchMaxBytes                   types.Int32  `tfsdk:"fetch_max_bytes"`
	FetchMinBytes                   types.Int32  `tfsdk:"fetch_min_bytes"`
	FetchPartitionMaxBytes          types.Int32  `tfsdk:"fetch_partition_max_bytes"`
	FetchWaitMaxMs                  types.Int32  `tfsdk:"fetch_wait_max_ms"`
	MetadataMaxAgeMs                types.Int32  `tfsdk:"metadata_max_age_ms"`
	RetryBackoffMs                  types.Int32  `tfsdk:"retry_backoff_ms"`
	SourceClusterID                 types.String `tfsdk:"source_cluster_id"`
	TLSSettings                     types.Object `tfsdk:"tls_settings"`
	ClientID                        types.String `tfsdk:"client_id"`
	EffectiveConnectionTimeoutMs    types.Int32  `tfsdk:"effective_connection_timeout_ms"`
	EffectiveFetchMaxBytes          types.Int32  `tfsdk:"effective_fetch_max_bytes"`
	EffectiveFetchMinBytes          types.Int32  `tfsdk:"effective_fetch_min_bytes"`
	EffectiveFetchPartitionMaxBytes types.Int32  `tfsdk:"effective_fetch_partition_max_bytes"`
	EffectiveFetchWaitMaxMs         types.Int32  `tfsdk:"effective_fetch_wait_max_ms"`
	EffectiveMetadataMaxAgeMs       types.Int32  `tfsdk:"effective_metadata_max_age_ms"`
	EffectiveRetryBackoffMs         types.Int32  `tfsdk:"effective_retry_backoff_ms"`
}

// ClientOptionsAuthenticationConfigurationModel mirrors the nested "client_options.authentication_configuration" attribute. Use the As/To
// converters on the parent struct to move between types.Object and this
// typed form.
type ClientOptionsAuthenticationConfigurationModel struct {
	PlainConfiguration types.Object `tfsdk:"plain_configuration"`
	ScramConfiguration types.Object `tfsdk:"scram_configuration"`
}

// ClientOptionsAuthenticationConfigurationPlainConfigurationModel mirrors the nested "client_options.authentication_configuration.plain_configuration" attribute. Use the As/To
// converters on the parent struct to move between types.Object and this
// typed form.
type ClientOptionsAuthenticationConfigurationPlainConfigurationModel struct {
	Password    types.String `tfsdk:"password"`
	Username    types.String `tfsdk:"username"`
	PasswordSet types.Bool   `tfsdk:"password_set"`
}

// ClientOptionsAuthenticationConfigurationScramConfigurationModel mirrors the nested "client_options.authentication_configuration.scram_configuration" attribute. Use the As/To
// converters on the parent struct to move between types.Object and this
// typed form.
type ClientOptionsAuthenticationConfigurationScramConfigurationModel struct {
	Password       types.String `tfsdk:"password"`
	ScramMechanism types.String `tfsdk:"scram_mechanism"`
	Username       types.String `tfsdk:"username"`
	PasswordSet    types.Bool   `tfsdk:"password_set"`
}

// ClientOptionsTLSSettingsModel mirrors the nested "client_options.tls_settings" attribute. Use the As/To
// converters on the parent struct to move between types.Object and this
// typed form.
type ClientOptionsTLSSettingsModel struct {
	Ca                  types.String `tfsdk:"ca"`
	Cert                types.String `tfsdk:"cert"`
	DoNotSetSniHostname types.Bool   `tfsdk:"do_not_set_sni_hostname"`
	Enabled             types.Bool   `tfsdk:"enabled"`
	Key                 types.String `tfsdk:"key"`
}

// ConsumerOffsetSyncOptionsModel mirrors the nested "consumer_offset_sync_options" attribute. Use the As/To
// converters on the parent struct to move between types.Object and this
// typed form.
type ConsumerOffsetSyncOptionsModel struct {
	GroupFilters types.List   `tfsdk:"group_filters"`
	Interval     types.String `tfsdk:"interval"`
	Paused       types.Bool   `tfsdk:"paused"`
}

// ConsumerOffsetSyncOptionsGroupFiltersModel mirrors the nested "consumer_offset_sync_options.group_filters" attribute. Use the As/To
// converters on the parent struct to move between types.Object and this
// typed form.
type ConsumerOffsetSyncOptionsGroupFiltersModel struct {
	FilterType  types.String `tfsdk:"filter_type"`
	Name        types.String `tfsdk:"name"`
	PatternType types.String `tfsdk:"pattern_type"`
}

// SchemaRegistrySyncOptionsModel mirrors the nested "schema_registry_sync_options" attribute. Use the As/To
// converters on the parent struct to move between types.Object and this
// typed form.
type SchemaRegistrySyncOptionsModel struct {
	ShadowSchemaRegistryTopic types.Bool `tfsdk:"shadow_schema_registry_topic"`
}

// SecuritySyncOptionsModel mirrors the nested "security_sync_options" attribute. Use the As/To
// converters on the parent struct to move between types.Object and this
// typed form.
type SecuritySyncOptionsModel struct {
	AclFilters types.List   `tfsdk:"acl_filters"`
	Interval   types.String `tfsdk:"interval"`
	Paused     types.Bool   `tfsdk:"paused"`
}

// SecuritySyncOptionsAclFiltersModel mirrors the nested "security_sync_options.acl_filters" attribute. Use the As/To
// converters on the parent struct to move between types.Object and this
// typed form.
type SecuritySyncOptionsAclFiltersModel struct {
	AccessFilter   types.Object `tfsdk:"access_filter"`
	ResourceFilter types.Object `tfsdk:"resource_filter"`
}

// SecuritySyncOptionsAclFiltersAccessFilterModel mirrors the nested "security_sync_options.acl_filters.access_filter" attribute. Use the As/To
// converters on the parent struct to move between types.Object and this
// typed form.
type SecuritySyncOptionsAclFiltersAccessFilterModel struct {
	Operation      types.String `tfsdk:"operation"`
	PermissionType types.String `tfsdk:"permission_type"`
	Host           types.String `tfsdk:"host"`
	Principal      types.String `tfsdk:"principal"`
}

// SecuritySyncOptionsAclFiltersResourceFilterModel mirrors the nested "security_sync_options.acl_filters.resource_filter" attribute. Use the As/To
// converters on the parent struct to move between types.Object and this
// typed form.
type SecuritySyncOptionsAclFiltersResourceFilterModel struct {
	PatternType  types.String `tfsdk:"pattern_type"`
	ResourceType types.String `tfsdk:"resource_type"`
	Name         types.String `tfsdk:"name"`
}

// TopicMetadataSyncOptionsModel mirrors the nested "topic_metadata_sync_options" attribute. Use the As/To
// converters on the parent struct to move between types.Object and this
// typed form.
type TopicMetadataSyncOptionsModel struct {
	AutoCreateShadowTopicFilters types.List   `tfsdk:"auto_create_shadow_topic_filters"`
	ExcludeDefault               types.Bool   `tfsdk:"exclude_default"`
	Interval                     types.String `tfsdk:"interval"`
	Paused                       types.Bool   `tfsdk:"paused"`
	StartAtEarliest              types.Bool   `tfsdk:"start_at_earliest"`
	StartAtLatest                types.Bool   `tfsdk:"start_at_latest"`
	StartAtTimestamp             types.String `tfsdk:"start_at_timestamp"`
	SyncedShadowTopicProperties  types.List   `tfsdk:"synced_shadow_topic_properties"`
}

// TopicMetadataSyncOptionsAutoCreateShadowTopicFiltersModel mirrors the nested "topic_metadata_sync_options.auto_create_shadow_topic_filters" attribute. Use the As/To
// converters on the parent struct to move between types.Object and this
// typed form.
type TopicMetadataSyncOptionsAutoCreateShadowTopicFiltersModel struct {
	FilterType  types.String `tfsdk:"filter_type"`
	Name        types.String `tfsdk:"name"`
	PatternType types.String `tfsdk:"pattern_type"`
}

// --- AttrType tables for nested types (consumed by types.ObjectValueFrom / ObjectNull) ---

// ClientOptionsAttrTypes returns the attr.Type map for the "client_options" nested
// attribute.
func ClientOptionsAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"authentication_configuration":        types.ObjectType{AttrTypes: ClientOptionsAuthenticationConfigurationAttrTypes()},
		"bootstrap_servers":                   types.ListType{ElemType: types.StringType},
		"connection_timeout_ms":               types.Int32Type,
		"fetch_max_bytes":                     types.Int32Type,
		"fetch_min_bytes":                     types.Int32Type,
		"fetch_partition_max_bytes":           types.Int32Type,
		"fetch_wait_max_ms":                   types.Int32Type,
		"metadata_max_age_ms":                 types.Int32Type,
		"retry_backoff_ms":                    types.Int32Type,
		"source_cluster_id":                   types.StringType,
		"tls_settings":                        types.ObjectType{AttrTypes: ClientOptionsTLSSettingsAttrTypes()},
		"client_id":                           types.StringType,
		"effective_connection_timeout_ms":     types.Int32Type,
		"effective_fetch_max_bytes":           types.Int32Type,
		"effective_fetch_min_bytes":           types.Int32Type,
		"effective_fetch_partition_max_bytes": types.Int32Type,
		"effective_fetch_wait_max_ms":         types.Int32Type,
		"effective_metadata_max_age_ms":       types.Int32Type,
		"effective_retry_backoff_ms":          types.Int32Type,
	}
}

// ClientOptionsAuthenticationConfigurationAttrTypes returns the attr.Type map for the "client_options.authentication_configuration" nested
// attribute.
func ClientOptionsAuthenticationConfigurationAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"plain_configuration": types.ObjectType{AttrTypes: ClientOptionsAuthenticationConfigurationPlainConfigurationAttrTypes()},
		"scram_configuration": types.ObjectType{AttrTypes: ClientOptionsAuthenticationConfigurationScramConfigurationAttrTypes()},
	}
}

// ClientOptionsAuthenticationConfigurationPlainConfigurationAttrTypes returns the attr.Type map for the "client_options.authentication_configuration.plain_configuration" nested
// attribute.
func ClientOptionsAuthenticationConfigurationPlainConfigurationAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"password":     types.StringType,
		"username":     types.StringType,
		"password_set": types.BoolType,
	}
}

// ClientOptionsAuthenticationConfigurationScramConfigurationAttrTypes returns the attr.Type map for the "client_options.authentication_configuration.scram_configuration" nested
// attribute.
func ClientOptionsAuthenticationConfigurationScramConfigurationAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"password":        types.StringType,
		"scram_mechanism": types.StringType,
		"username":        types.StringType,
		"password_set":    types.BoolType,
	}
}

// ClientOptionsTLSSettingsAttrTypes returns the attr.Type map for the "client_options.tls_settings" nested
// attribute.
func ClientOptionsTLSSettingsAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"ca":                      types.StringType,
		"cert":                    types.StringType,
		"do_not_set_sni_hostname": types.BoolType,
		"enabled":                 types.BoolType,
		"key":                     types.StringType,
	}
}

// ConsumerOffsetSyncOptionsAttrTypes returns the attr.Type map for the "consumer_offset_sync_options" nested
// attribute.
func ConsumerOffsetSyncOptionsAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"group_filters": types.ListType{ElemType: types.ObjectType{AttrTypes: ConsumerOffsetSyncOptionsGroupFiltersAttrTypes()}},
		"interval":      types.StringType,
		"paused":        types.BoolType,
	}
}

// ConsumerOffsetSyncOptionsGroupFiltersAttrTypes returns the attr.Type map for the "consumer_offset_sync_options.group_filters" nested
// attribute.
func ConsumerOffsetSyncOptionsGroupFiltersAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"filter_type":  types.StringType,
		"name":         types.StringType,
		"pattern_type": types.StringType,
	}
}

// SchemaRegistrySyncOptionsAttrTypes returns the attr.Type map for the "schema_registry_sync_options" nested
// attribute.
func SchemaRegistrySyncOptionsAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"shadow_schema_registry_topic": types.BoolType,
	}
}

// SecuritySyncOptionsAttrTypes returns the attr.Type map for the "security_sync_options" nested
// attribute.
func SecuritySyncOptionsAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"acl_filters": types.ListType{ElemType: types.ObjectType{AttrTypes: SecuritySyncOptionsAclFiltersAttrTypes()}},
		"interval":    types.StringType,
		"paused":      types.BoolType,
	}
}

// SecuritySyncOptionsAclFiltersAttrTypes returns the attr.Type map for the "security_sync_options.acl_filters" nested
// attribute.
func SecuritySyncOptionsAclFiltersAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"access_filter":   types.ObjectType{AttrTypes: SecuritySyncOptionsAclFiltersAccessFilterAttrTypes()},
		"resource_filter": types.ObjectType{AttrTypes: SecuritySyncOptionsAclFiltersResourceFilterAttrTypes()},
	}
}

// SecuritySyncOptionsAclFiltersAccessFilterAttrTypes returns the attr.Type map for the "security_sync_options.acl_filters.access_filter" nested
// attribute.
func SecuritySyncOptionsAclFiltersAccessFilterAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"operation":       types.StringType,
		"permission_type": types.StringType,
		"host":            types.StringType,
		"principal":       types.StringType,
	}
}

// SecuritySyncOptionsAclFiltersResourceFilterAttrTypes returns the attr.Type map for the "security_sync_options.acl_filters.resource_filter" nested
// attribute.
func SecuritySyncOptionsAclFiltersResourceFilterAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"pattern_type":  types.StringType,
		"resource_type": types.StringType,
		"name":          types.StringType,
	}
}

// TopicMetadataSyncOptionsAttrTypes returns the attr.Type map for the "topic_metadata_sync_options" nested
// attribute.
func TopicMetadataSyncOptionsAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"auto_create_shadow_topic_filters": types.ListType{ElemType: types.ObjectType{AttrTypes: TopicMetadataSyncOptionsAutoCreateShadowTopicFiltersAttrTypes()}},
		"exclude_default":                  types.BoolType,
		"interval":                         types.StringType,
		"paused":                           types.BoolType,
		"start_at_earliest":                types.BoolType,
		"start_at_latest":                  types.BoolType,
		"start_at_timestamp":               types.StringType,
		"synced_shadow_topic_properties":   types.ListType{ElemType: types.StringType},
	}
}

// TopicMetadataSyncOptionsAutoCreateShadowTopicFiltersAttrTypes returns the attr.Type map for the "topic_metadata_sync_options.auto_create_shadow_topic_filters" nested
// attribute.
func TopicMetadataSyncOptionsAutoCreateShadowTopicFiltersAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"filter_type":  types.StringType,
		"name":         types.StringType,
		"pattern_type": types.StringType,
	}
}

// --- Root-level converters (types.Object ⇄ typed struct ergonomics) ---

// AsClientOptions converts the root client_options attribute from
// types.Object into its typed form. Returns (nil, nil) when the object is
// null or unknown. Use this when you want typed field access without
// manually unpacking .Attributes().
func (m *ResourceModel) AsClientOptions(ctx context.Context) (*ClientOptionsModel, diag.Diagnostics) {
	if m == nil || m.ClientOptions.IsNull() || m.ClientOptions.IsUnknown() {
		return nil, nil
	}
	var out ClientOptionsModel
	d := m.ClientOptions.As(ctx, &out, basetypes.ObjectAsOptions{})
	return &out, d
}

// ClientOptionsToObject encodes a typed struct back into the
// types.Object shape expected by the framework. A nil receiver returns
// types.ObjectNull with the correct attribute types.
func ClientOptionsToObject(ctx context.Context, v *ClientOptionsModel) (types.Object, diag.Diagnostics) {
	if v == nil {
		return types.ObjectNull(ClientOptionsAttrTypes()), nil
	}
	return types.ObjectValueFrom(ctx, ClientOptionsAttrTypes(), v)
}

// AsConsumerOffsetSyncOptions converts the root consumer_offset_sync_options attribute from
// types.Object into its typed form. Returns (nil, nil) when the object is
// null or unknown. Use this when you want typed field access without
// manually unpacking .Attributes().
func (m *ResourceModel) AsConsumerOffsetSyncOptions(ctx context.Context) (*ConsumerOffsetSyncOptionsModel, diag.Diagnostics) {
	if m == nil || m.ConsumerOffsetSyncOptions.IsNull() || m.ConsumerOffsetSyncOptions.IsUnknown() {
		return nil, nil
	}
	var out ConsumerOffsetSyncOptionsModel
	d := m.ConsumerOffsetSyncOptions.As(ctx, &out, basetypes.ObjectAsOptions{})
	return &out, d
}

// ConsumerOffsetSyncOptionsToObject encodes a typed struct back into the
// types.Object shape expected by the framework. A nil receiver returns
// types.ObjectNull with the correct attribute types.
func ConsumerOffsetSyncOptionsToObject(ctx context.Context, v *ConsumerOffsetSyncOptionsModel) (types.Object, diag.Diagnostics) {
	if v == nil {
		return types.ObjectNull(ConsumerOffsetSyncOptionsAttrTypes()), nil
	}
	return types.ObjectValueFrom(ctx, ConsumerOffsetSyncOptionsAttrTypes(), v)
}

// AsSchemaRegistrySyncOptions converts the root schema_registry_sync_options attribute from
// types.Object into its typed form. Returns (nil, nil) when the object is
// null or unknown. Use this when you want typed field access without
// manually unpacking .Attributes().
func (m *ResourceModel) AsSchemaRegistrySyncOptions(ctx context.Context) (*SchemaRegistrySyncOptionsModel, diag.Diagnostics) {
	if m == nil || m.SchemaRegistrySyncOptions.IsNull() || m.SchemaRegistrySyncOptions.IsUnknown() {
		return nil, nil
	}
	var out SchemaRegistrySyncOptionsModel
	d := m.SchemaRegistrySyncOptions.As(ctx, &out, basetypes.ObjectAsOptions{})
	return &out, d
}

// SchemaRegistrySyncOptionsToObject encodes a typed struct back into the
// types.Object shape expected by the framework. A nil receiver returns
// types.ObjectNull with the correct attribute types.
func SchemaRegistrySyncOptionsToObject(ctx context.Context, v *SchemaRegistrySyncOptionsModel) (types.Object, diag.Diagnostics) {
	if v == nil {
		return types.ObjectNull(SchemaRegistrySyncOptionsAttrTypes()), nil
	}
	return types.ObjectValueFrom(ctx, SchemaRegistrySyncOptionsAttrTypes(), v)
}

// AsSecuritySyncOptions converts the root security_sync_options attribute from
// types.Object into its typed form. Returns (nil, nil) when the object is
// null or unknown. Use this when you want typed field access without
// manually unpacking .Attributes().
func (m *ResourceModel) AsSecuritySyncOptions(ctx context.Context) (*SecuritySyncOptionsModel, diag.Diagnostics) {
	if m == nil || m.SecuritySyncOptions.IsNull() || m.SecuritySyncOptions.IsUnknown() {
		return nil, nil
	}
	var out SecuritySyncOptionsModel
	d := m.SecuritySyncOptions.As(ctx, &out, basetypes.ObjectAsOptions{})
	return &out, d
}

// SecuritySyncOptionsToObject encodes a typed struct back into the
// types.Object shape expected by the framework. A nil receiver returns
// types.ObjectNull with the correct attribute types.
func SecuritySyncOptionsToObject(ctx context.Context, v *SecuritySyncOptionsModel) (types.Object, diag.Diagnostics) {
	if v == nil {
		return types.ObjectNull(SecuritySyncOptionsAttrTypes()), nil
	}
	return types.ObjectValueFrom(ctx, SecuritySyncOptionsAttrTypes(), v)
}

// AsTopicMetadataSyncOptions converts the root topic_metadata_sync_options attribute from
// types.Object into its typed form. Returns (nil, nil) when the object is
// null or unknown. Use this when you want typed field access without
// manually unpacking .Attributes().
func (m *ResourceModel) AsTopicMetadataSyncOptions(ctx context.Context) (*TopicMetadataSyncOptionsModel, diag.Diagnostics) {
	if m == nil || m.TopicMetadataSyncOptions.IsNull() || m.TopicMetadataSyncOptions.IsUnknown() {
		return nil, nil
	}
	var out TopicMetadataSyncOptionsModel
	d := m.TopicMetadataSyncOptions.As(ctx, &out, basetypes.ObjectAsOptions{})
	return &out, d
}

// TopicMetadataSyncOptionsToObject encodes a typed struct back into the
// types.Object shape expected by the framework. A nil receiver returns
// types.ObjectNull with the correct attribute types.
func TopicMetadataSyncOptionsToObject(ctx context.Context, v *TopicMetadataSyncOptionsModel) (types.Object, diag.Diagnostics) {
	if v == nil {
		return types.ObjectNull(TopicMetadataSyncOptionsAttrTypes()), nil
	}
	return types.ObjectValueFrom(ctx, TopicMetadataSyncOptionsAttrTypes(), v)
}

// --- Sub-level converters (free-standing Decode*/ToObject for types nested beyond root level) ---

// DecodeClientOptionsAuthenticationConfiguration decodes the sub-field from its parent typed struct.
// Returns (nil, nil) when the field is null or unknown.
func DecodeClientOptionsAuthenticationConfiguration(ctx context.Context, v *ClientOptionsModel) (*ClientOptionsAuthenticationConfigurationModel, diag.Diagnostics) {
	if v == nil || v.AuthenticationConfiguration.IsNull() || v.AuthenticationConfiguration.IsUnknown() {
		return nil, nil
	}
	var out ClientOptionsAuthenticationConfigurationModel
	d := v.AuthenticationConfiguration.As(ctx, &out, basetypes.ObjectAsOptions{})
	return &out, d
}

// ClientOptionsAuthenticationConfigurationToObject encodes a typed struct back into types.Object.
// A nil receiver returns types.ObjectNull with the correct attribute types.
func ClientOptionsAuthenticationConfigurationToObject(ctx context.Context, v *ClientOptionsAuthenticationConfigurationModel) (types.Object, diag.Diagnostics) {
	if v == nil {
		return types.ObjectNull(ClientOptionsAuthenticationConfigurationAttrTypes()), nil
	}
	return types.ObjectValueFrom(ctx, ClientOptionsAuthenticationConfigurationAttrTypes(), v)
}

// DecodeClientOptionsAuthenticationConfigurationPlainConfiguration decodes the sub-field from its parent typed struct.
// Returns (nil, nil) when the field is null or unknown.
func DecodeClientOptionsAuthenticationConfigurationPlainConfiguration(ctx context.Context, v *ClientOptionsAuthenticationConfigurationModel) (*ClientOptionsAuthenticationConfigurationPlainConfigurationModel, diag.Diagnostics) {
	if v == nil || v.PlainConfiguration.IsNull() || v.PlainConfiguration.IsUnknown() {
		return nil, nil
	}
	var out ClientOptionsAuthenticationConfigurationPlainConfigurationModel
	d := v.PlainConfiguration.As(ctx, &out, basetypes.ObjectAsOptions{})
	return &out, d
}

// ClientOptionsAuthenticationConfigurationPlainConfigurationToObject encodes a typed struct back into types.Object.
// A nil receiver returns types.ObjectNull with the correct attribute types.
func ClientOptionsAuthenticationConfigurationPlainConfigurationToObject(ctx context.Context, v *ClientOptionsAuthenticationConfigurationPlainConfigurationModel) (types.Object, diag.Diagnostics) {
	if v == nil {
		return types.ObjectNull(ClientOptionsAuthenticationConfigurationPlainConfigurationAttrTypes()), nil
	}
	return types.ObjectValueFrom(ctx, ClientOptionsAuthenticationConfigurationPlainConfigurationAttrTypes(), v)
}

// DecodeClientOptionsAuthenticationConfigurationScramConfiguration decodes the sub-field from its parent typed struct.
// Returns (nil, nil) when the field is null or unknown.
func DecodeClientOptionsAuthenticationConfigurationScramConfiguration(ctx context.Context, v *ClientOptionsAuthenticationConfigurationModel) (*ClientOptionsAuthenticationConfigurationScramConfigurationModel, diag.Diagnostics) {
	if v == nil || v.ScramConfiguration.IsNull() || v.ScramConfiguration.IsUnknown() {
		return nil, nil
	}
	var out ClientOptionsAuthenticationConfigurationScramConfigurationModel
	d := v.ScramConfiguration.As(ctx, &out, basetypes.ObjectAsOptions{})
	return &out, d
}

// ClientOptionsAuthenticationConfigurationScramConfigurationToObject encodes a typed struct back into types.Object.
// A nil receiver returns types.ObjectNull with the correct attribute types.
func ClientOptionsAuthenticationConfigurationScramConfigurationToObject(ctx context.Context, v *ClientOptionsAuthenticationConfigurationScramConfigurationModel) (types.Object, diag.Diagnostics) {
	if v == nil {
		return types.ObjectNull(ClientOptionsAuthenticationConfigurationScramConfigurationAttrTypes()), nil
	}
	return types.ObjectValueFrom(ctx, ClientOptionsAuthenticationConfigurationScramConfigurationAttrTypes(), v)
}

// DecodeClientOptionsTLSSettings decodes the sub-field from its parent typed struct.
// Returns (nil, nil) when the field is null or unknown.
func DecodeClientOptionsTLSSettings(ctx context.Context, v *ClientOptionsModel) (*ClientOptionsTLSSettingsModel, diag.Diagnostics) {
	if v == nil || v.TLSSettings.IsNull() || v.TLSSettings.IsUnknown() {
		return nil, nil
	}
	var out ClientOptionsTLSSettingsModel
	d := v.TLSSettings.As(ctx, &out, basetypes.ObjectAsOptions{})
	return &out, d
}

// ClientOptionsTLSSettingsToObject encodes a typed struct back into types.Object.
// A nil receiver returns types.ObjectNull with the correct attribute types.
func ClientOptionsTLSSettingsToObject(ctx context.Context, v *ClientOptionsTLSSettingsModel) (types.Object, diag.Diagnostics) {
	if v == nil {
		return types.ObjectNull(ClientOptionsTLSSettingsAttrTypes()), nil
	}
	return types.ObjectValueFrom(ctx, ClientOptionsTLSSettingsAttrTypes(), v)
}

// DecodeSecuritySyncOptionsAclFiltersAccessFilter decodes the sub-field from its parent typed struct.
// Returns (nil, nil) when the field is null or unknown.
func DecodeSecuritySyncOptionsAclFiltersAccessFilter(ctx context.Context, v *SecuritySyncOptionsAclFiltersModel) (*SecuritySyncOptionsAclFiltersAccessFilterModel, diag.Diagnostics) {
	if v == nil || v.AccessFilter.IsNull() || v.AccessFilter.IsUnknown() {
		return nil, nil
	}
	var out SecuritySyncOptionsAclFiltersAccessFilterModel
	d := v.AccessFilter.As(ctx, &out, basetypes.ObjectAsOptions{})
	return &out, d
}

// SecuritySyncOptionsAclFiltersAccessFilterToObject encodes a typed struct back into types.Object.
// A nil receiver returns types.ObjectNull with the correct attribute types.
func SecuritySyncOptionsAclFiltersAccessFilterToObject(ctx context.Context, v *SecuritySyncOptionsAclFiltersAccessFilterModel) (types.Object, diag.Diagnostics) {
	if v == nil {
		return types.ObjectNull(SecuritySyncOptionsAclFiltersAccessFilterAttrTypes()), nil
	}
	return types.ObjectValueFrom(ctx, SecuritySyncOptionsAclFiltersAccessFilterAttrTypes(), v)
}

// DecodeSecuritySyncOptionsAclFiltersResourceFilter decodes the sub-field from its parent typed struct.
// Returns (nil, nil) when the field is null or unknown.
func DecodeSecuritySyncOptionsAclFiltersResourceFilter(ctx context.Context, v *SecuritySyncOptionsAclFiltersModel) (*SecuritySyncOptionsAclFiltersResourceFilterModel, diag.Diagnostics) {
	if v == nil || v.ResourceFilter.IsNull() || v.ResourceFilter.IsUnknown() {
		return nil, nil
	}
	var out SecuritySyncOptionsAclFiltersResourceFilterModel
	d := v.ResourceFilter.As(ctx, &out, basetypes.ObjectAsOptions{})
	return &out, d
}

// SecuritySyncOptionsAclFiltersResourceFilterToObject encodes a typed struct back into types.Object.
// A nil receiver returns types.ObjectNull with the correct attribute types.
func SecuritySyncOptionsAclFiltersResourceFilterToObject(ctx context.Context, v *SecuritySyncOptionsAclFiltersResourceFilterModel) (types.Object, diag.Diagnostics) {
	if v == nil {
		return types.ObjectNull(SecuritySyncOptionsAclFiltersResourceFilterAttrTypes()), nil
	}
	return types.ObjectValueFrom(ctx, SecuritySyncOptionsAclFiltersResourceFilterAttrTypes(), v)
}

// GenerateMinimalResourceModel returns a *ResourceModel populated only with
// the supplied id + timeouts; every other field is at its typed null (or its
// declared minimal_default). Used by resources that need to persist a
// partial state when Create / Read returns mid-flight.
func GenerateMinimalResourceModel(id types.String, timeout timeouts.Value) *ResourceModel {
	return &ResourceModel{
		AllowDeletion:             types.BoolNull(),
		ClientOptions:             types.ObjectNull(ClientOptionsAttrTypes()),
		ConsumerOffsetSyncOptions: types.ObjectNull(ConsumerOffsetSyncOptionsAttrTypes()),
		ID:                        id,
		Name:                      types.StringNull(),
		Reason:                    types.StringNull(),
		SchemaRegistrySyncOptions: types.ObjectNull(SchemaRegistrySyncOptionsAttrTypes()),
		SecuritySyncOptions:       types.ObjectNull(SecuritySyncOptionsAttrTypes()),
		ShadowRedpandaID:          types.StringNull(),
		SourceRedpandaID:          types.StringNull(),
		State:                     types.StringNull(),
		Timeouts:                  timeout,
		TopicMetadataSyncOptions:  types.ObjectNull(TopicMetadataSyncOptionsAttrTypes()),
	}
}
