// Code generated by schemagen. DO NOT EDIT.

// Copyright 2023 Redpanda Data, Inc.
//
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

package serverlessprivatelink

import (
	controlplanev1 "buf.build/gen/go/redpandadata/cloud/protocolbuffers/go/redpanda/api/controlplane/v1"
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/redpanda-data/terraform-provider-redpanda/internal/modelconv"
	"github.com/redpanda-data/terraform-provider-redpanda/redpanda/utils/enums"
)

type ServerlessPrivateLinkResponse interface {
	GetAwsConfig() *controlplanev1.ServerlessPrivateLink_AWS
	GetCloudprovider() controlplanev1.CloudProvider
	GetId() string
	GetName() string
	GetResourceGroupId() string
	GetServerlessRegion() string
	GetState() controlplanev1.ServerlessPrivateLink_State
	GetStatus() *controlplanev1.ServerlessPrivateLinkStatus
}

// Flatten populates a *ResourceModel from the API response payload.
// The prev *ResourceModel arg carries forward TF-only / sensitive / write-only
// fields that the response cannot supply; pass nil when no prior state exists
// (e.g., during ImportState).
func Flatten(ctx context.Context, proto ServerlessPrivateLinkResponse, prev *ResourceModel) (*ResourceModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	m := &ResourceModel{}
	m.CloudProvider = types.StringValue(enums.CloudProviderToString(proto.GetCloudprovider()))
	m.Name = types.StringValue(proto.GetName())
	m.ResourceGroupID = types.StringValue(proto.GetResourceGroupId())
	m.ServerlessRegion = types.StringValue(proto.GetServerlessRegion())
	m.AWSConfig = modelconv.ObjectFromMessageWithDiagsAndPrev(ctx, proto.GetAwsConfig(), func() *AWSConfigModel { v, _ := prev.AsAWSConfig(ctx); return v }(), AWSConfigAttrTypes(), FlattenAWSConfig, &diags)
	m.ID = types.StringValue(proto.GetId())
	m.State = types.StringValue(enums.ServerlessPrivateLinkStateToString(proto.GetState()))
	m.Status = modelconv.ObjectFromMessageWithDiagsAndPrev(ctx, proto.GetStatus(), func() *StatusModel { v, _ := prev.AsStatus(ctx); return v }(), StatusAttrTypes(), FlattenStatus, &diags)
	if prev != nil && !prev.AllowDeletion.IsUnknown() {
		m.AllowDeletion = prev.AllowDeletion
	} else {
		m.AllowDeletion = types.BoolNull()
	}
	if prev != nil {
		m.Timeouts = prev.Timeouts
	}
	if m.AllowDeletion.IsNull() || m.AllowDeletion.IsUnknown() {
		m.AllowDeletion = types.BoolValue(false)
	}
	return m, diags
}

// ExpandCreate renders a *ResourceModel into the proto request envelope for
// the corresponding RPC.
func ExpandCreate(ctx context.Context, m *ResourceModel) (*controlplanev1.CreateServerlessPrivateLinkRequest, diag.Diagnostics) {
	var diags diag.Diagnostics
	payload := &controlplanev1.ServerlessPrivateLinkCreate{
		Cloudprovider:    enums.StringToCloudProvider(m.CloudProvider.ValueString()),
		Name:             m.Name.ValueString(),
		ResourceGroupId:  m.ResourceGroupID.ValueString(),
		ServerlessRegion: m.ServerlessRegion.ValueString(),
	}
	if v := modelconv.ObjectToMessageWithDiags(ctx, m.AWSConfig, ExpandCreateAWSConfig, &diags); v != nil {
		payload.SetAwsConfig(v)
	}
	req := &controlplanev1.CreateServerlessPrivateLinkRequest{
		ServerlessPrivateLink: payload,
	}
	return req, diags
}

// ExpandUpdate renders a *ResourceModel into the proto request envelope for
// the corresponding RPC.
func ExpandUpdate(ctx context.Context, m *ResourceModel) (*controlplanev1.UpdateServerlessPrivateLinkRequest, diag.Diagnostics) {
	var diags diag.Diagnostics
	req := &controlplanev1.UpdateServerlessPrivateLinkRequest{
		Id: m.ID.ValueString(),
	}
	if v := modelconv.ObjectToMessageWithDiags(ctx, m.AWSConfig, ExpandUpdateAWSConfig, &diags); v != nil {
		req.SetAwsConfig(v)
	}
	return req, diags
}

// ExpandDelete renders a *ResourceModel into the proto request envelope for
// the corresponding RPC.
func ExpandDelete(_ context.Context, m *ResourceModel) (*controlplanev1.DeleteServerlessPrivateLinkRequest, diag.Diagnostics) {
	var diags diag.Diagnostics
	req := &controlplanev1.DeleteServerlessPrivateLinkRequest{
		Id: m.ID.ValueString(),
	}
	return req, diags
}

// FlattenAWSConfig converts a single proto controlplanev1.ServerlessPrivateLink_AWS into the
// corresponding nested model. The prev *AWSConfigModel arg carries forward
// TF-only / sensitive / write-only fields and resolves the proto3
// null-vs-empty ambiguity for Optional-only scalars; pass nil when no prior
// nested state is available.
func FlattenAWSConfig(ctx context.Context, proto *controlplanev1.ServerlessPrivateLink_AWS, prev *AWSConfigModel) (AWSConfigModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	_ = prev
	m := AWSConfigModel{}
	m.AllowedPrincipals = modelconv.ListFromStringsWithDiags(ctx, proto.GetAllowedPrincipals(), &diags)
	return m, diags
}

// ExpandAWSConfig renders a nested model back into the proto type.
func ExpandAWSConfig(ctx context.Context, m *AWSConfigModel) (*controlplanev1.ServerlessPrivateLink_AWS, diag.Diagnostics) {
	var diags diag.Diagnostics
	if m == nil {
		return nil, diags
	}
	out := &controlplanev1.ServerlessPrivateLink_AWS{
		AllowedPrincipals: modelconv.ListToStringsWithDiags(ctx, m.AllowedPrincipals, &diags),
	}
	return out, diags
}

// FlattenStatus converts a single proto controlplanev1.ServerlessPrivateLinkStatus into the
// corresponding nested model. The prev *StatusModel arg carries forward
// TF-only / sensitive / write-only fields and resolves the proto3
// null-vs-empty ambiguity for Optional-only scalars; pass nil when no prior
// nested state is available.
func FlattenStatus(ctx context.Context, proto *controlplanev1.ServerlessPrivateLinkStatus, prev *StatusModel) (StatusModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	_ = prev
	m := StatusModel{}
	m.AWS = modelconv.ObjectFromMessageWithDiagsAndPrev(ctx, proto.GetAws(), func() *StatusAWSModel { v, _ := DecodeStatusAWS(ctx, prev); return v }(), StatusAWSAttrTypes(), FlattenStatusAWS, &diags)
	return m, diags
}

// ExpandStatus renders a nested model back into the proto type.
func ExpandStatus(ctx context.Context, m *StatusModel) (*controlplanev1.ServerlessPrivateLinkStatus, diag.Diagnostics) {
	var diags diag.Diagnostics
	if m == nil {
		return nil, diags
	}
	out := &controlplanev1.ServerlessPrivateLinkStatus{}
	if v := modelconv.ObjectToMessageWithDiags(ctx, m.AWS, ExpandStatusAWS, &diags); v != nil {
		out.SetAws(v)
	}
	return out, diags
}

// FlattenStatusAWS converts a single proto controlplanev1.ServerlessPrivateLinkStatus_AWS into the
// corresponding nested model. The prev *StatusAWSModel arg carries forward
// TF-only / sensitive / write-only fields and resolves the proto3
// null-vs-empty ambiguity for Optional-only scalars; pass nil when no prior
// nested state is available.
func FlattenStatusAWS(ctx context.Context, proto *controlplanev1.ServerlessPrivateLinkStatus_AWS, prev *StatusAWSModel) (StatusAWSModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	_ = prev
	m := StatusAWSModel{}
	m.AvailabilityZones = modelconv.ListFromStringsWithDiags(ctx, proto.GetAvailabilityZones(), &diags)
	m.VPCEndpointServiceName = types.StringValue(proto.GetVpcEndpointServiceName())
	return m, diags
}

// ExpandStatusAWS renders a nested model back into the proto type.
func ExpandStatusAWS(ctx context.Context, m *StatusAWSModel) (*controlplanev1.ServerlessPrivateLinkStatus_AWS, diag.Diagnostics) {
	var diags diag.Diagnostics
	if m == nil {
		return nil, diags
	}
	out := &controlplanev1.ServerlessPrivateLinkStatus_AWS{
		AvailabilityZones:      modelconv.ListToStringsWithDiags(ctx, m.AvailabilityZones, &diags),
		VpcEndpointServiceName: m.VPCEndpointServiceName.ValueString(),
	}
	return out, diags
}

// ExpandCreateAWSConfig renders a nested model back into the proto type.
func ExpandCreateAWSConfig(ctx context.Context, m *AWSConfigModel) (*controlplanev1.ServerlessPrivateLinkCreate_AWS, diag.Diagnostics) {
	var diags diag.Diagnostics
	if m == nil {
		return nil, diags
	}
	out := &controlplanev1.ServerlessPrivateLinkCreate_AWS{
		AllowedPrincipals: modelconv.ListToStringsWithDiags(ctx, m.AllowedPrincipals, &diags),
	}
	return out, diags
}

// ExpandUpdateAWSConfig renders a nested model back into the proto type.
func ExpandUpdateAWSConfig(ctx context.Context, m *AWSConfigModel) (*controlplanev1.UpdateServerlessPrivateLinkRequest_AWS, diag.Diagnostics) {
	var diags diag.Diagnostics
	if m == nil {
		return nil, diags
	}
	out := &controlplanev1.UpdateServerlessPrivateLinkRequest_AWS{
		AllowedPrincipals: modelconv.ListToStringsWithDiags(ctx, m.AllowedPrincipals, &diags),
	}
	return out, diags
}
