// Code generated by schemagen. DO NOT EDIT.

// Copyright 2023 Redpanda Data, Inc.
//
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

// Package serverlessprivatelink contains the model for the serverlessprivatelink resource.
package serverlessprivatelink

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

// ResourceModel represents the Terraform schema for the serverlessprivatelink resource.
type ResourceModel struct {
	AWSConfig        types.Object   `tfsdk:"aws_config"`
	AllowDeletion    types.Bool     `tfsdk:"allow_deletion"`
	CloudProvider    types.String   `tfsdk:"cloud_provider"`
	ID               types.String   `tfsdk:"id"`
	Name             types.String   `tfsdk:"name"`
	ResourceGroupID  types.String   `tfsdk:"resource_group_id"`
	ServerlessRegion types.String   `tfsdk:"serverless_region"`
	State            types.String   `tfsdk:"state"`
	Status           types.Object   `tfsdk:"status"`
	Timeouts         timeouts.Value `tfsdk:"timeouts"`
}

// --- Nested typed structs (one per nested message in the proto tree) ---

// AWSConfigModel mirrors the nested "aws_config" attribute. Use the As/To
// converters on the parent struct to move between types.Object and this
// typed form.
type AWSConfigModel struct {
	AllowedPrincipals types.List `tfsdk:"allowed_principals"`
}

// StatusModel mirrors the nested "status" attribute. Use the As/To
// converters on the parent struct to move between types.Object and this
// typed form.
type StatusModel struct {
	AWS types.Object `tfsdk:"aws"`
}

// StatusAWSModel mirrors the nested "status.aws" attribute. Use the As/To
// converters on the parent struct to move between types.Object and this
// typed form.
type StatusAWSModel struct {
	AvailabilityZones      types.List   `tfsdk:"availability_zones"`
	VPCEndpointServiceName types.String `tfsdk:"vpc_endpoint_service_name"`
}

// --- AttrType tables for nested types (consumed by types.ObjectValueFrom / ObjectNull) ---

// AWSConfigAttrTypes returns the attr.Type map for the "aws_config" nested
// attribute.
func AWSConfigAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"allowed_principals": types.ListType{ElemType: types.StringType},
	}
}

// StatusAttrTypes returns the attr.Type map for the "status" nested
// attribute.
func StatusAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"aws": types.ObjectType{AttrTypes: StatusAWSAttrTypes()},
	}
}

// StatusAWSAttrTypes returns the attr.Type map for the "status.aws" nested
// attribute.
func StatusAWSAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"availability_zones":        types.ListType{ElemType: types.StringType},
		"vpc_endpoint_service_name": types.StringType,
	}
}

// --- Root-level converters (types.Object ⇄ typed struct ergonomics) ---

// AsAWSConfig converts the root aws_config attribute from
// types.Object into its typed form. Returns (nil, nil) when the object is
// null or unknown. Use this when you want typed field access without
// manually unpacking .Attributes().
func (m *ResourceModel) AsAWSConfig(ctx context.Context) (*AWSConfigModel, diag.Diagnostics) {
	if m == nil || m.AWSConfig.IsNull() || m.AWSConfig.IsUnknown() {
		return nil, nil
	}
	var out AWSConfigModel
	d := m.AWSConfig.As(ctx, &out, basetypes.ObjectAsOptions{})
	return &out, d
}

// AWSConfigToObject encodes a typed struct back into the
// types.Object shape expected by the framework. A nil receiver returns
// types.ObjectNull with the correct attribute types.
func AWSConfigToObject(ctx context.Context, v *AWSConfigModel) (types.Object, diag.Diagnostics) {
	if v == nil {
		return types.ObjectNull(AWSConfigAttrTypes()), nil
	}
	return types.ObjectValueFrom(ctx, AWSConfigAttrTypes(), v)
}

// AsStatus converts the root status attribute from
// types.Object into its typed form. Returns (nil, nil) when the object is
// null or unknown. Use this when you want typed field access without
// manually unpacking .Attributes().
func (m *ResourceModel) AsStatus(ctx context.Context) (*StatusModel, diag.Diagnostics) {
	if m == nil || m.Status.IsNull() || m.Status.IsUnknown() {
		return nil, nil
	}
	var out StatusModel
	d := m.Status.As(ctx, &out, basetypes.ObjectAsOptions{})
	return &out, d
}

// StatusToObject encodes a typed struct back into the
// types.Object shape expected by the framework. A nil receiver returns
// types.ObjectNull with the correct attribute types.
func StatusToObject(ctx context.Context, v *StatusModel) (types.Object, diag.Diagnostics) {
	if v == nil {
		return types.ObjectNull(StatusAttrTypes()), nil
	}
	return types.ObjectValueFrom(ctx, StatusAttrTypes(), v)
}

// --- Sub-level converters (free-standing Decode*/ToObject for types nested beyond root level) ---

// DecodeStatusAWS decodes the sub-field from its parent typed struct.
// Returns (nil, nil) when the field is null or unknown.
func DecodeStatusAWS(ctx context.Context, v *StatusModel) (*StatusAWSModel, diag.Diagnostics) {
	if v == nil || v.AWS.IsNull() || v.AWS.IsUnknown() {
		return nil, nil
	}
	var out StatusAWSModel
	d := v.AWS.As(ctx, &out, basetypes.ObjectAsOptions{})
	return &out, d
}

// StatusAWSToObject encodes a typed struct back into types.Object.
// A nil receiver returns types.ObjectNull with the correct attribute types.
func StatusAWSToObject(ctx context.Context, v *StatusAWSModel) (types.Object, diag.Diagnostics) {
	if v == nil {
		return types.ObjectNull(StatusAWSAttrTypes()), nil
	}
	return types.ObjectValueFrom(ctx, StatusAWSAttrTypes(), v)
}

// GenerateMinimalResourceModel returns a *ResourceModel populated only with
// the supplied id + timeouts; every other field is at its typed null (or its
// declared minimal_default). Used by resources that need to persist a
// partial state when Create / Read returns mid-flight.
func GenerateMinimalResourceModel(id types.String, timeout timeouts.Value) *ResourceModel {
	return &ResourceModel{
		AWSConfig:        types.ObjectNull(AWSConfigAttrTypes()),
		AllowDeletion:    types.BoolNull(),
		CloudProvider:    types.StringNull(),
		ID:               id,
		Name:             types.StringNull(),
		ResourceGroupID:  types.StringNull(),
		ServerlessRegion: types.StringNull(),
		State:            types.StringNull(),
		Status:           types.ObjectNull(StatusAttrTypes()),
		Timeouts:         timeout,
	}
}
