// Code generated by MockGen. DO NOT EDIT.
// Source: buf.build/gen/go/redpandadata/cloud/grpc/go/redpanda/api/controlplane/v1/controlplanev1grpc (interfaces: ServerlessClusterServiceClient)
//
// Generated by this command:
//
//	mockgen -destination=./mock_serverless_cluster_service_client.go -package=mocks buf.build/gen/go/redpandadata/cloud/grpc/go/redpanda/api/controlplane/v1/controlplanev1grpc ServerlessClusterServiceClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	v1 "buf.build/gen/go/redpandadata/cloud/protocolbuffers/go/redpanda/api/controlplane/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockServerlessClusterServiceClient is a mock of ServerlessClusterServiceClient interface.
type MockServerlessClusterServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockServerlessClusterServiceClientMockRecorder
	isgomock struct{}
}

// MockServerlessClusterServiceClientMockRecorder is the mock recorder for MockServerlessClusterServiceClient.
type MockServerlessClusterServiceClientMockRecorder struct {
	mock *MockServerlessClusterServiceClient
}

// NewMockServerlessClusterServiceClient creates a new mock instance.
func NewMockServerlessClusterServiceClient(ctrl *gomock.Controller) *MockServerlessClusterServiceClient {
	mock := &MockServerlessClusterServiceClient{ctrl: ctrl}
	mock.recorder = &MockServerlessClusterServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServerlessClusterServiceClient) EXPECT() *MockServerlessClusterServiceClientMockRecorder {
	return m.recorder
}

// CreateServerlessCluster mocks base method.
func (m *MockServerlessClusterServiceClient) CreateServerlessCluster(ctx context.Context, in *v1.CreateServerlessClusterRequest, opts ...grpc.CallOption) (*v1.CreateServerlessClusterOperation, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateServerlessCluster", varargs...)
	ret0, _ := ret[0].(*v1.CreateServerlessClusterOperation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateServerlessCluster indicates an expected call of CreateServerlessCluster.
func (mr *MockServerlessClusterServiceClientMockRecorder) CreateServerlessCluster(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateServerlessCluster", reflect.TypeOf((*MockServerlessClusterServiceClient)(nil).CreateServerlessCluster), varargs...)
}

// DeleteServerlessCluster mocks base method.
func (m *MockServerlessClusterServiceClient) DeleteServerlessCluster(ctx context.Context, in *v1.DeleteServerlessClusterRequest, opts ...grpc.CallOption) (*v1.DeleteServerlessClusterOperation, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteServerlessCluster", varargs...)
	ret0, _ := ret[0].(*v1.DeleteServerlessClusterOperation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteServerlessCluster indicates an expected call of DeleteServerlessCluster.
func (mr *MockServerlessClusterServiceClientMockRecorder) DeleteServerlessCluster(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteServerlessCluster", reflect.TypeOf((*MockServerlessClusterServiceClient)(nil).DeleteServerlessCluster), varargs...)
}

// DummyCreateMetadata mocks base method.
func (m *MockServerlessClusterServiceClient) DummyCreateMetadata(ctx context.Context, in *v1.CreateServerlessClusterRequest, opts ...grpc.CallOption) (*v1.CreateServerlessClusterMetadata, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DummyCreateMetadata", varargs...)
	ret0, _ := ret[0].(*v1.CreateServerlessClusterMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DummyCreateMetadata indicates an expected call of DummyCreateMetadata.
func (mr *MockServerlessClusterServiceClientMockRecorder) DummyCreateMetadata(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DummyCreateMetadata", reflect.TypeOf((*MockServerlessClusterServiceClient)(nil).DummyCreateMetadata), varargs...)
}

// DummyDeleteMetadata mocks base method.
func (m *MockServerlessClusterServiceClient) DummyDeleteMetadata(ctx context.Context, in *v1.DeleteServerlessClusterRequest, opts ...grpc.CallOption) (*v1.DeleteServerlessClusterMetadata, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DummyDeleteMetadata", varargs...)
	ret0, _ := ret[0].(*v1.DeleteServerlessClusterMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DummyDeleteMetadata indicates an expected call of DummyDeleteMetadata.
func (mr *MockServerlessClusterServiceClientMockRecorder) DummyDeleteMetadata(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DummyDeleteMetadata", reflect.TypeOf((*MockServerlessClusterServiceClient)(nil).DummyDeleteMetadata), varargs...)
}

// GetPrometheusCredentials mocks base method.
func (m *MockServerlessClusterServiceClient) GetPrometheusCredentials(ctx context.Context, in *v1.GetPrometheusCredentialsRequest, opts ...grpc.CallOption) (*v1.GetPrometheusCredentialsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPrometheusCredentials", varargs...)
	ret0, _ := ret[0].(*v1.GetPrometheusCredentialsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrometheusCredentials indicates an expected call of GetPrometheusCredentials.
func (mr *MockServerlessClusterServiceClientMockRecorder) GetPrometheusCredentials(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrometheusCredentials", reflect.TypeOf((*MockServerlessClusterServiceClient)(nil).GetPrometheusCredentials), varargs...)
}

// GetServerlessCluster mocks base method.
func (m *MockServerlessClusterServiceClient) GetServerlessCluster(ctx context.Context, in *v1.GetServerlessClusterRequest, opts ...grpc.CallOption) (*v1.GetServerlessClusterResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetServerlessCluster", varargs...)
	ret0, _ := ret[0].(*v1.GetServerlessClusterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServerlessCluster indicates an expected call of GetServerlessCluster.
func (mr *MockServerlessClusterServiceClientMockRecorder) GetServerlessCluster(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServerlessCluster", reflect.TypeOf((*MockServerlessClusterServiceClient)(nil).GetServerlessCluster), varargs...)
}

// ListServerlessClusters mocks base method.
func (m *MockServerlessClusterServiceClient) ListServerlessClusters(ctx context.Context, in *v1.ListServerlessClustersRequest, opts ...grpc.CallOption) (*v1.ListServerlessClustersResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListServerlessClusters", varargs...)
	ret0, _ := ret[0].(*v1.ListServerlessClustersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListServerlessClusters indicates an expected call of ListServerlessClusters.
func (mr *MockServerlessClusterServiceClientMockRecorder) ListServerlessClusters(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListServerlessClusters", reflect.TypeOf((*MockServerlessClusterServiceClient)(nil).ListServerlessClusters), varargs...)
}

// UpdateServerlessCluster mocks base method.
func (m *MockServerlessClusterServiceClient) UpdateServerlessCluster(ctx context.Context, in *v1.UpdateServerlessClusterRequest, opts ...grpc.CallOption) (*v1.UpdateServerlessClusterOperation, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateServerlessCluster", varargs...)
	ret0, _ := ret[0].(*v1.UpdateServerlessClusterOperation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateServerlessCluster indicates an expected call of UpdateServerlessCluster.
func (mr *MockServerlessClusterServiceClientMockRecorder) UpdateServerlessCluster(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateServerlessCluster", reflect.TypeOf((*MockServerlessClusterServiceClient)(nil).UpdateServerlessCluster), varargs...)
}
