// Code generated by MockGen. DO NOT EDIT.
// Source: buf.build/gen/go/redpandadata/cloud/grpc/go/redpanda/api/controlplane/v1/controlplanev1grpc (interfaces: ShadowLinkServiceClient)
//
// Generated by this command:
//
//	mockgen -destination=./mock_shadow_link_service_client.go -package=mocks buf.build/gen/go/redpandadata/cloud/grpc/go/redpanda/api/controlplane/v1/controlplanev1grpc ShadowLinkServiceClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	controlplanev1 "buf.build/gen/go/redpandadata/cloud/protocolbuffers/go/redpanda/api/controlplane/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockShadowLinkServiceClient is a mock of ShadowLinkServiceClient interface.
type MockShadowLinkServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockShadowLinkServiceClientMockRecorder
	isgomock struct{}
}

// MockShadowLinkServiceClientMockRecorder is the mock recorder for MockShadowLinkServiceClient.
type MockShadowLinkServiceClientMockRecorder struct {
	mock *MockShadowLinkServiceClient
}

// NewMockShadowLinkServiceClient creates a new mock instance.
func NewMockShadowLinkServiceClient(ctrl *gomock.Controller) *MockShadowLinkServiceClient {
	mock := &MockShadowLinkServiceClient{ctrl: ctrl}
	mock.recorder = &MockShadowLinkServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShadowLinkServiceClient) EXPECT() *MockShadowLinkServiceClientMockRecorder {
	return m.recorder
}

// CreateShadowLink mocks base method.
func (m *MockShadowLinkServiceClient) CreateShadowLink(ctx context.Context, in *controlplanev1.CreateShadowLinkRequest, opts ...grpc.CallOption) (*controlplanev1.CreateShadowLinkOperation, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateShadowLink", varargs...)
	ret0, _ := ret[0].(*controlplanev1.CreateShadowLinkOperation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateShadowLink indicates an expected call of CreateShadowLink.
func (mr *MockShadowLinkServiceClientMockRecorder) CreateShadowLink(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateShadowLink", reflect.TypeOf((*MockShadowLinkServiceClient)(nil).CreateShadowLink), varargs...)
}

// DeleteShadowLink mocks base method.
func (m *MockShadowLinkServiceClient) DeleteShadowLink(ctx context.Context, in *controlplanev1.DeleteShadowLinkRequest, opts ...grpc.CallOption) (*controlplanev1.DeleteShadowLinkOperation, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteShadowLink", varargs...)
	ret0, _ := ret[0].(*controlplanev1.DeleteShadowLinkOperation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteShadowLink indicates an expected call of DeleteShadowLink.
func (mr *MockShadowLinkServiceClientMockRecorder) DeleteShadowLink(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteShadowLink", reflect.TypeOf((*MockShadowLinkServiceClient)(nil).DeleteShadowLink), varargs...)
}

// GetShadowLink mocks base method.
func (m *MockShadowLinkServiceClient) GetShadowLink(ctx context.Context, in *controlplanev1.GetShadowLinkRequest, opts ...grpc.CallOption) (*controlplanev1.GetShadowLinkResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetShadowLink", varargs...)
	ret0, _ := ret[0].(*controlplanev1.GetShadowLinkResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShadowLink indicates an expected call of GetShadowLink.
func (mr *MockShadowLinkServiceClientMockRecorder) GetShadowLink(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShadowLink", reflect.TypeOf((*MockShadowLinkServiceClient)(nil).GetShadowLink), varargs...)
}

// ListShadowLinks mocks base method.
func (m *MockShadowLinkServiceClient) ListShadowLinks(ctx context.Context, in *controlplanev1.ListShadowLinksRequest, opts ...grpc.CallOption) (*controlplanev1.ListShadowLinksResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListShadowLinks", varargs...)
	ret0, _ := ret[0].(*controlplanev1.ListShadowLinksResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListShadowLinks indicates an expected call of ListShadowLinks.
func (mr *MockShadowLinkServiceClientMockRecorder) ListShadowLinks(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListShadowLinks", reflect.TypeOf((*MockShadowLinkServiceClient)(nil).ListShadowLinks), varargs...)
}

// UpdateShadowLink mocks base method.
func (m *MockShadowLinkServiceClient) UpdateShadowLink(ctx context.Context, in *controlplanev1.UpdateShadowLinkRequest, opts ...grpc.CallOption) (*controlplanev1.UpdateShadowLinkOperation, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateShadowLink", varargs...)
	ret0, _ := ret[0].(*controlplanev1.UpdateShadowLinkOperation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateShadowLink indicates an expected call of UpdateShadowLink.
func (mr *MockShadowLinkServiceClientMockRecorder) UpdateShadowLink(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateShadowLink", reflect.TypeOf((*MockShadowLinkServiceClient)(nil).UpdateShadowLink), varargs...)
}
