// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/redpanda-data/terraform-provider-redpanda/redpanda/resources/schema (interfaces: SRClienter)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	sr "github.com/twmb/franz-go/pkg/sr"
)

// MockSRClienter is a mock of SRClienter interface.
type MockSRClienter struct {
	ctrl     *gomock.Controller
	recorder *MockSRClienterMockRecorder
}

// MockSRClienterMockRecorder is the mock recorder for MockSRClienter.
type MockSRClienterMockRecorder struct {
	mock *MockSRClienter
}

// NewMockSRClienter creates a new mock instance.
func NewMockSRClienter(ctrl *gomock.Controller) *MockSRClienter {
	mock := &MockSRClienter{ctrl: ctrl}
	mock.recorder = &MockSRClienterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSRClienter) EXPECT() *MockSRClienterMockRecorder {
	return m.recorder
}

// Compatibility mocks base method.
func (m *MockSRClienter) Compatibility(arg0 context.Context, arg1 ...string) []sr.CompatibilityResult {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Compatibility", varargs...)
	ret0, _ := ret[0].([]sr.CompatibilityResult)
	return ret0
}

// Compatibility indicates an expected call of Compatibility.
func (mr *MockSRClienterMockRecorder) Compatibility(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compatibility", reflect.TypeOf((*MockSRClienter)(nil).Compatibility), varargs...)
}

// CreateSchema mocks base method.
func (m *MockSRClienter) CreateSchema(arg0 context.Context, arg1 string, arg2 sr.Schema) (sr.SubjectSchema, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSchema", arg0, arg1, arg2)
	ret0, _ := ret[0].(sr.SubjectSchema)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSchema indicates an expected call of CreateSchema.
func (mr *MockSRClienterMockRecorder) CreateSchema(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSchema", reflect.TypeOf((*MockSRClienter)(nil).CreateSchema), arg0, arg1, arg2)
}

// DeleteSubject mocks base method.
func (m *MockSRClienter) DeleteSubject(arg0 context.Context, arg1 string, arg2 sr.DeleteHow) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSubject", arg0, arg1, arg2)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteSubject indicates an expected call of DeleteSubject.
func (mr *MockSRClienterMockRecorder) DeleteSubject(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSubject", reflect.TypeOf((*MockSRClienter)(nil).DeleteSubject), arg0, arg1, arg2)
}

// SchemaByVersion mocks base method.
func (m *MockSRClienter) SchemaByVersion(arg0 context.Context, arg1 string, arg2 int) (sr.SubjectSchema, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SchemaByVersion", arg0, arg1, arg2)
	ret0, _ := ret[0].(sr.SubjectSchema)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SchemaByVersion indicates an expected call of SchemaByVersion.
func (mr *MockSRClienterMockRecorder) SchemaByVersion(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SchemaByVersion", reflect.TypeOf((*MockSRClienter)(nil).SchemaByVersion), arg0, arg1, arg2)
}

// Schemas mocks base method.
func (m *MockSRClienter) Schemas(arg0 context.Context, arg1 string) ([]sr.SubjectSchema, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Schemas", arg0, arg1)
	ret0, _ := ret[0].([]sr.SubjectSchema)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Schemas indicates an expected call of Schemas.
func (mr *MockSRClienterMockRecorder) Schemas(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Schemas", reflect.TypeOf((*MockSRClienter)(nil).Schemas), arg0, arg1)
}

// SetCompatibility mocks base method.
func (m *MockSRClienter) SetCompatibility(arg0 context.Context, arg1 sr.SetCompatibility, arg2 ...string) []sr.CompatibilityResult {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetCompatibility", varargs...)
	ret0, _ := ret[0].([]sr.CompatibilityResult)
	return ret0
}

// SetCompatibility indicates an expected call of SetCompatibility.
func (mr *MockSRClienterMockRecorder) SetCompatibility(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCompatibility", reflect.TypeOf((*MockSRClienter)(nil).SetCompatibility), varargs...)
}
