// Code generated by MockGen. DO NOT EDIT.
// Source: buf.build/gen/go/redpandadata/dataplane/grpc/go/redpanda/api/dataplane/v1/dataplanev1grpc (interfaces: SecretServiceClient)
//
// Generated by this command:
//
//	mockgen -destination=./mock_secret_service_client.go -package=mocks buf.build/gen/go/redpandadata/dataplane/grpc/go/redpanda/api/dataplane/v1/dataplanev1grpc SecretServiceClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dataplanev1 "buf.build/gen/go/redpandadata/dataplane/protocolbuffers/go/redpanda/api/dataplane/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockSecretServiceClient is a mock of SecretServiceClient interface.
type MockSecretServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockSecretServiceClientMockRecorder
	isgomock struct{}
}

// MockSecretServiceClientMockRecorder is the mock recorder for MockSecretServiceClient.
type MockSecretServiceClientMockRecorder struct {
	mock *MockSecretServiceClient
}

// NewMockSecretServiceClient creates a new mock instance.
func NewMockSecretServiceClient(ctrl *gomock.Controller) *MockSecretServiceClient {
	mock := &MockSecretServiceClient{ctrl: ctrl}
	mock.recorder = &MockSecretServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretServiceClient) EXPECT() *MockSecretServiceClientMockRecorder {
	return m.recorder
}

// CreateKafkaConnectSecret mocks base method.
func (m *MockSecretServiceClient) CreateKafkaConnectSecret(ctx context.Context, in *dataplanev1.CreateKafkaConnectSecretRequest, opts ...grpc.CallOption) (*dataplanev1.CreateKafkaConnectSecretResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateKafkaConnectSecret", varargs...)
	ret0, _ := ret[0].(*dataplanev1.CreateKafkaConnectSecretResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateKafkaConnectSecret indicates an expected call of CreateKafkaConnectSecret.
func (mr *MockSecretServiceClientMockRecorder) CreateKafkaConnectSecret(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKafkaConnectSecret", reflect.TypeOf((*MockSecretServiceClient)(nil).CreateKafkaConnectSecret), varargs...)
}

// CreateSecret mocks base method.
func (m *MockSecretServiceClient) CreateSecret(ctx context.Context, in *dataplanev1.CreateSecretRequest, opts ...grpc.CallOption) (*dataplanev1.CreateSecretResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateSecret", varargs...)
	ret0, _ := ret[0].(*dataplanev1.CreateSecretResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSecret indicates an expected call of CreateSecret.
func (mr *MockSecretServiceClientMockRecorder) CreateSecret(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSecret", reflect.TypeOf((*MockSecretServiceClient)(nil).CreateSecret), varargs...)
}

// DeleteKafkaConnectSecret mocks base method.
func (m *MockSecretServiceClient) DeleteKafkaConnectSecret(ctx context.Context, in *dataplanev1.DeleteKafkaConnectSecretRequest, opts ...grpc.CallOption) (*dataplanev1.DeleteKafkaConnectSecretResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteKafkaConnectSecret", varargs...)
	ret0, _ := ret[0].(*dataplanev1.DeleteKafkaConnectSecretResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteKafkaConnectSecret indicates an expected call of DeleteKafkaConnectSecret.
func (mr *MockSecretServiceClientMockRecorder) DeleteKafkaConnectSecret(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteKafkaConnectSecret", reflect.TypeOf((*MockSecretServiceClient)(nil).DeleteKafkaConnectSecret), varargs...)
}

// DeleteSecret mocks base method.
func (m *MockSecretServiceClient) DeleteSecret(ctx context.Context, in *dataplanev1.DeleteSecretRequest, opts ...grpc.CallOption) (*dataplanev1.DeleteSecretResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteSecret", varargs...)
	ret0, _ := ret[0].(*dataplanev1.DeleteSecretResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteSecret indicates an expected call of DeleteSecret.
func (mr *MockSecretServiceClientMockRecorder) DeleteSecret(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSecret", reflect.TypeOf((*MockSecretServiceClient)(nil).DeleteSecret), varargs...)
}

// GetKafkaConnectSecret mocks base method.
func (m *MockSecretServiceClient) GetKafkaConnectSecret(ctx context.Context, in *dataplanev1.GetKafkaConnectSecretRequest, opts ...grpc.CallOption) (*dataplanev1.GetKafkaConnectSecretResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetKafkaConnectSecret", varargs...)
	ret0, _ := ret[0].(*dataplanev1.GetKafkaConnectSecretResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKafkaConnectSecret indicates an expected call of GetKafkaConnectSecret.
func (mr *MockSecretServiceClientMockRecorder) GetKafkaConnectSecret(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKafkaConnectSecret", reflect.TypeOf((*MockSecretServiceClient)(nil).GetKafkaConnectSecret), varargs...)
}

// GetSecret mocks base method.
func (m *MockSecretServiceClient) GetSecret(ctx context.Context, in *dataplanev1.GetSecretRequest, opts ...grpc.CallOption) (*dataplanev1.GetSecretResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetSecret", varargs...)
	ret0, _ := ret[0].(*dataplanev1.GetSecretResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecret indicates an expected call of GetSecret.
func (mr *MockSecretServiceClientMockRecorder) GetSecret(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecret", reflect.TypeOf((*MockSecretServiceClient)(nil).GetSecret), varargs...)
}

// ListKafkaConnectSecrets mocks base method.
func (m *MockSecretServiceClient) ListKafkaConnectSecrets(ctx context.Context, in *dataplanev1.ListKafkaConnectSecretsRequest, opts ...grpc.CallOption) (*dataplanev1.ListKafkaConnectSecretsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListKafkaConnectSecrets", varargs...)
	ret0, _ := ret[0].(*dataplanev1.ListKafkaConnectSecretsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListKafkaConnectSecrets indicates an expected call of ListKafkaConnectSecrets.
func (mr *MockSecretServiceClientMockRecorder) ListKafkaConnectSecrets(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListKafkaConnectSecrets", reflect.TypeOf((*MockSecretServiceClient)(nil).ListKafkaConnectSecrets), varargs...)
}

// ListResources mocks base method.
func (m *MockSecretServiceClient) ListResources(ctx context.Context, in *dataplanev1.ListResourcesRequest, opts ...grpc.CallOption) (*dataplanev1.ListResourcesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListResources", varargs...)
	ret0, _ := ret[0].(*dataplanev1.ListResourcesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListResources indicates an expected call of ListResources.
func (mr *MockSecretServiceClientMockRecorder) ListResources(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListResources", reflect.TypeOf((*MockSecretServiceClient)(nil).ListResources), varargs...)
}

// ListSecretScopes mocks base method.
func (m *MockSecretServiceClient) ListSecretScopes(ctx context.Context, in *dataplanev1.ListSecretScopesRequest, opts ...grpc.CallOption) (*dataplanev1.ListSecretScopesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListSecretScopes", varargs...)
	ret0, _ := ret[0].(*dataplanev1.ListSecretScopesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSecretScopes indicates an expected call of ListSecretScopes.
func (mr *MockSecretServiceClientMockRecorder) ListSecretScopes(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSecretScopes", reflect.TypeOf((*MockSecretServiceClient)(nil).ListSecretScopes), varargs...)
}

// ListSecrets mocks base method.
func (m *MockSecretServiceClient) ListSecrets(ctx context.Context, in *dataplanev1.ListSecretsRequest, opts ...grpc.CallOption) (*dataplanev1.ListSecretsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListSecrets", varargs...)
	ret0, _ := ret[0].(*dataplanev1.ListSecretsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSecrets indicates an expected call of ListSecrets.
func (mr *MockSecretServiceClientMockRecorder) ListSecrets(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSecrets", reflect.TypeOf((*MockSecretServiceClient)(nil).ListSecrets), varargs...)
}

// UpdateKafkaConnectSecret mocks base method.
func (m *MockSecretServiceClient) UpdateKafkaConnectSecret(ctx context.Context, in *dataplanev1.UpdateKafkaConnectSecretRequest, opts ...grpc.CallOption) (*dataplanev1.UpdateKafkaConnectSecretResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateKafkaConnectSecret", varargs...)
	ret0, _ := ret[0].(*dataplanev1.UpdateKafkaConnectSecretResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateKafkaConnectSecret indicates an expected call of UpdateKafkaConnectSecret.
func (mr *MockSecretServiceClientMockRecorder) UpdateKafkaConnectSecret(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateKafkaConnectSecret", reflect.TypeOf((*MockSecretServiceClient)(nil).UpdateKafkaConnectSecret), varargs...)
}

// UpdateSecret mocks base method.
func (m *MockSecretServiceClient) UpdateSecret(ctx context.Context, in *dataplanev1.UpdateSecretRequest, opts ...grpc.CallOption) (*dataplanev1.UpdateSecretResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateSecret", varargs...)
	ret0, _ := ret[0].(*dataplanev1.UpdateSecretResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSecret indicates an expected call of UpdateSecret.
func (mr *MockSecretServiceClientMockRecorder) UpdateSecret(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSecret", reflect.TypeOf((*MockSecretServiceClient)(nil).UpdateSecret), varargs...)
}
