// Code generated by MockGen. DO NOT EDIT.
// Source: buf.build/gen/go/redpandadata/cloud/grpc/go/redpanda/api/controlplane/v1beta2/controlplanev1beta2grpc (interfaces: ThroughputTierServiceClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	controlplanev1beta2 "buf.build/gen/go/redpandadata/cloud/protocolbuffers/go/redpanda/api/controlplane/v1beta2"
	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockThroughputTierServiceClient is a mock of ThroughputTierServiceClient interface.
type MockThroughputTierServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockThroughputTierServiceClientMockRecorder
}

// MockThroughputTierServiceClientMockRecorder is the mock recorder for MockThroughputTierServiceClient.
type MockThroughputTierServiceClientMockRecorder struct {
	mock *MockThroughputTierServiceClient
}

// NewMockThroughputTierServiceClient creates a new mock instance.
func NewMockThroughputTierServiceClient(ctrl *gomock.Controller) *MockThroughputTierServiceClient {
	mock := &MockThroughputTierServiceClient{ctrl: ctrl}
	mock.recorder = &MockThroughputTierServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockThroughputTierServiceClient) EXPECT() *MockThroughputTierServiceClientMockRecorder {
	return m.recorder
}

// GetThroughputTier mocks base method.
func (m *MockThroughputTierServiceClient) GetThroughputTier(arg0 context.Context, arg1 *controlplanev1beta2.GetThroughputTierRequest, arg2 ...grpc.CallOption) (*controlplanev1beta2.GetThroughputTierResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetThroughputTier", varargs...)
	ret0, _ := ret[0].(*controlplanev1beta2.GetThroughputTierResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetThroughputTier indicates an expected call of GetThroughputTier.
func (mr *MockThroughputTierServiceClientMockRecorder) GetThroughputTier(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetThroughputTier", reflect.TypeOf((*MockThroughputTierServiceClient)(nil).GetThroughputTier), varargs...)
}

// ListThroughputTiers mocks base method.
func (m *MockThroughputTierServiceClient) ListThroughputTiers(arg0 context.Context, arg1 *controlplanev1beta2.ListThroughputTiersRequest, arg2 ...grpc.CallOption) (*controlplanev1beta2.ListThroughputTiersResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListThroughputTiers", varargs...)
	ret0, _ := ret[0].(*controlplanev1beta2.ListThroughputTiersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListThroughputTiers indicates an expected call of ListThroughputTiers.
func (mr *MockThroughputTierServiceClientMockRecorder) ListThroughputTiers(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListThroughputTiers", reflect.TypeOf((*MockThroughputTierServiceClient)(nil).ListThroughputTiers), varargs...)
}
