// Code generated by MockGen. DO NOT EDIT.
// Source: buf.build/gen/go/redpandadata/dataplane/grpc/go/redpanda/api/dataplane/v1/dataplanev1grpc (interfaces: TopicServiceClient)
//
// Generated by this command:
//
//	mockgen -destination=./mock_topic_service_client.go -package=mocks buf.build/gen/go/redpandadata/dataplane/grpc/go/redpanda/api/dataplane/v1/dataplanev1grpc TopicServiceClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	v1 "buf.build/gen/go/redpandadata/dataplane/protocolbuffers/go/redpanda/api/dataplane/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockTopicServiceClient is a mock of TopicServiceClient interface.
type MockTopicServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockTopicServiceClientMockRecorder
	isgomock struct{}
}

// MockTopicServiceClientMockRecorder is the mock recorder for MockTopicServiceClient.
type MockTopicServiceClientMockRecorder struct {
	mock *MockTopicServiceClient
}

// NewMockTopicServiceClient creates a new mock instance.
func NewMockTopicServiceClient(ctrl *gomock.Controller) *MockTopicServiceClient {
	mock := &MockTopicServiceClient{ctrl: ctrl}
	mock.recorder = &MockTopicServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTopicServiceClient) EXPECT() *MockTopicServiceClientMockRecorder {
	return m.recorder
}

// AddPartitionsToTopics mocks base method.
func (m *MockTopicServiceClient) AddPartitionsToTopics(ctx context.Context, in *v1.AddPartitionsToTopicsRequest, opts ...grpc.CallOption) (*v1.AddPartitionsToTopicsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddPartitionsToTopics", varargs...)
	ret0, _ := ret[0].(*v1.AddPartitionsToTopicsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddPartitionsToTopics indicates an expected call of AddPartitionsToTopics.
func (mr *MockTopicServiceClientMockRecorder) AddPartitionsToTopics(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPartitionsToTopics", reflect.TypeOf((*MockTopicServiceClient)(nil).AddPartitionsToTopics), varargs...)
}

// AddTopicPartitions mocks base method.
func (m *MockTopicServiceClient) AddTopicPartitions(ctx context.Context, in *v1.AddTopicPartitionsRequest, opts ...grpc.CallOption) (*v1.AddTopicPartitionsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddTopicPartitions", varargs...)
	ret0, _ := ret[0].(*v1.AddTopicPartitionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddTopicPartitions indicates an expected call of AddTopicPartitions.
func (mr *MockTopicServiceClientMockRecorder) AddTopicPartitions(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTopicPartitions", reflect.TypeOf((*MockTopicServiceClient)(nil).AddTopicPartitions), varargs...)
}

// CreateTopic mocks base method.
func (m *MockTopicServiceClient) CreateTopic(ctx context.Context, in *v1.CreateTopicRequest, opts ...grpc.CallOption) (*v1.CreateTopicResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateTopic", varargs...)
	ret0, _ := ret[0].(*v1.CreateTopicResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTopic indicates an expected call of CreateTopic.
func (mr *MockTopicServiceClientMockRecorder) CreateTopic(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTopic", reflect.TypeOf((*MockTopicServiceClient)(nil).CreateTopic), varargs...)
}

// DeleteTopic mocks base method.
func (m *MockTopicServiceClient) DeleteTopic(ctx context.Context, in *v1.DeleteTopicRequest, opts ...grpc.CallOption) (*v1.DeleteTopicResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteTopic", varargs...)
	ret0, _ := ret[0].(*v1.DeleteTopicResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTopic indicates an expected call of DeleteTopic.
func (mr *MockTopicServiceClientMockRecorder) DeleteTopic(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTopic", reflect.TypeOf((*MockTopicServiceClient)(nil).DeleteTopic), varargs...)
}

// GetTopicConfigurations mocks base method.
func (m *MockTopicServiceClient) GetTopicConfigurations(ctx context.Context, in *v1.GetTopicConfigurationsRequest, opts ...grpc.CallOption) (*v1.GetTopicConfigurationsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTopicConfigurations", varargs...)
	ret0, _ := ret[0].(*v1.GetTopicConfigurationsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopicConfigurations indicates an expected call of GetTopicConfigurations.
func (mr *MockTopicServiceClientMockRecorder) GetTopicConfigurations(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopicConfigurations", reflect.TypeOf((*MockTopicServiceClient)(nil).GetTopicConfigurations), varargs...)
}

// ListTopics mocks base method.
func (m *MockTopicServiceClient) ListTopics(ctx context.Context, in *v1.ListTopicsRequest, opts ...grpc.CallOption) (*v1.ListTopicsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListTopics", varargs...)
	ret0, _ := ret[0].(*v1.ListTopicsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTopics indicates an expected call of ListTopics.
func (mr *MockTopicServiceClientMockRecorder) ListTopics(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTopics", reflect.TypeOf((*MockTopicServiceClient)(nil).ListTopics), varargs...)
}

// SetPartitionsToTopics mocks base method.
func (m *MockTopicServiceClient) SetPartitionsToTopics(ctx context.Context, in *v1.SetPartitionsToTopicsRequest, opts ...grpc.CallOption) (*v1.SetPartitionsToTopicsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetPartitionsToTopics", varargs...)
	ret0, _ := ret[0].(*v1.SetPartitionsToTopicsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetPartitionsToTopics indicates an expected call of SetPartitionsToTopics.
func (mr *MockTopicServiceClientMockRecorder) SetPartitionsToTopics(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPartitionsToTopics", reflect.TypeOf((*MockTopicServiceClient)(nil).SetPartitionsToTopics), varargs...)
}

// SetTopicConfigurations mocks base method.
func (m *MockTopicServiceClient) SetTopicConfigurations(ctx context.Context, in *v1.SetTopicConfigurationsRequest, opts ...grpc.CallOption) (*v1.SetTopicConfigurationsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetTopicConfigurations", varargs...)
	ret0, _ := ret[0].(*v1.SetTopicConfigurationsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetTopicConfigurations indicates an expected call of SetTopicConfigurations.
func (mr *MockTopicServiceClientMockRecorder) SetTopicConfigurations(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTopicConfigurations", reflect.TypeOf((*MockTopicServiceClient)(nil).SetTopicConfigurations), varargs...)
}

// SetTopicPartitions mocks base method.
func (m *MockTopicServiceClient) SetTopicPartitions(ctx context.Context, in *v1.SetTopicPartitionsRequest, opts ...grpc.CallOption) (*v1.SetTopicPartitionsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetTopicPartitions", varargs...)
	ret0, _ := ret[0].(*v1.SetTopicPartitionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetTopicPartitions indicates an expected call of SetTopicPartitions.
func (mr *MockTopicServiceClientMockRecorder) SetTopicPartitions(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTopicPartitions", reflect.TypeOf((*MockTopicServiceClient)(nil).SetTopicPartitions), varargs...)
}

// UpdateTopicConfigurations mocks base method.
func (m *MockTopicServiceClient) UpdateTopicConfigurations(ctx context.Context, in *v1.UpdateTopicConfigurationsRequest, opts ...grpc.CallOption) (*v1.UpdateTopicConfigurationsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateTopicConfigurations", varargs...)
	ret0, _ := ret[0].(*v1.UpdateTopicConfigurationsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTopicConfigurations indicates an expected call of UpdateTopicConfigurations.
func (mr *MockTopicServiceClientMockRecorder) UpdateTopicConfigurations(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTopicConfigurations", reflect.TypeOf((*MockTopicServiceClient)(nil).UpdateTopicConfigurations), varargs...)
}
