// Code generated by MockGen. DO NOT EDIT.
// Source: buf.build/gen/go/redpandadata/dataplane/grpc/go/redpanda/api/console/v1alpha1/consolev1alpha1grpc (interfaces: SecurityServiceClient)
//
// Generated by this command:
//
//	mockgen -destination=./mock_security_service_client.go -package=mocks buf.build/gen/go/redpandadata/dataplane/grpc/go/redpanda/api/console/v1alpha1/consolev1alpha1grpc SecurityServiceClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	consolev1alpha1 "buf.build/gen/go/redpandadata/dataplane/protocolbuffers/go/redpanda/api/console/v1alpha1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockSecurityServiceClient is a mock of SecurityServiceClient interface.
type MockSecurityServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockSecurityServiceClientMockRecorder
	isgomock struct{}
}

// MockSecurityServiceClientMockRecorder is the mock recorder for MockSecurityServiceClient.
type MockSecurityServiceClientMockRecorder struct {
	mock *MockSecurityServiceClient
}

// NewMockSecurityServiceClient creates a new mock instance.
func NewMockSecurityServiceClient(ctrl *gomock.Controller) *MockSecurityServiceClient {
	mock := &MockSecurityServiceClient{ctrl: ctrl}
	mock.recorder = &MockSecurityServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecurityServiceClient) EXPECT() *MockSecurityServiceClientMockRecorder {
	return m.recorder
}

// CreateRole mocks base method.
func (m *MockSecurityServiceClient) CreateRole(ctx context.Context, in *consolev1alpha1.CreateRoleRequest, opts ...grpc.CallOption) (*consolev1alpha1.CreateRoleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateRole", varargs...)
	ret0, _ := ret[0].(*consolev1alpha1.CreateRoleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRole indicates an expected call of CreateRole.
func (mr *MockSecurityServiceClientMockRecorder) CreateRole(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRole", reflect.TypeOf((*MockSecurityServiceClient)(nil).CreateRole), varargs...)
}

// DeleteRole mocks base method.
func (m *MockSecurityServiceClient) DeleteRole(ctx context.Context, in *consolev1alpha1.DeleteRoleRequest, opts ...grpc.CallOption) (*consolev1alpha1.DeleteRoleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteRole", varargs...)
	ret0, _ := ret[0].(*consolev1alpha1.DeleteRoleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteRole indicates an expected call of DeleteRole.
func (mr *MockSecurityServiceClientMockRecorder) DeleteRole(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRole", reflect.TypeOf((*MockSecurityServiceClient)(nil).DeleteRole), varargs...)
}

// GetRole mocks base method.
func (m *MockSecurityServiceClient) GetRole(ctx context.Context, in *consolev1alpha1.GetRoleRequest, opts ...grpc.CallOption) (*consolev1alpha1.GetRoleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetRole", varargs...)
	ret0, _ := ret[0].(*consolev1alpha1.GetRoleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRole indicates an expected call of GetRole.
func (mr *MockSecurityServiceClientMockRecorder) GetRole(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRole", reflect.TypeOf((*MockSecurityServiceClient)(nil).GetRole), varargs...)
}

// ListRoleMembers mocks base method.
func (m *MockSecurityServiceClient) ListRoleMembers(ctx context.Context, in *consolev1alpha1.ListRoleMembersRequest, opts ...grpc.CallOption) (*consolev1alpha1.ListRoleMembersResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListRoleMembers", varargs...)
	ret0, _ := ret[0].(*consolev1alpha1.ListRoleMembersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoleMembers indicates an expected call of ListRoleMembers.
func (mr *MockSecurityServiceClientMockRecorder) ListRoleMembers(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoleMembers", reflect.TypeOf((*MockSecurityServiceClient)(nil).ListRoleMembers), varargs...)
}

// ListRoles mocks base method.
func (m *MockSecurityServiceClient) ListRoles(ctx context.Context, in *consolev1alpha1.ListRolesRequest, opts ...grpc.CallOption) (*consolev1alpha1.ListRolesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListRoles", varargs...)
	ret0, _ := ret[0].(*consolev1alpha1.ListRolesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoles indicates an expected call of ListRoles.
func (mr *MockSecurityServiceClientMockRecorder) ListRoles(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoles", reflect.TypeOf((*MockSecurityServiceClient)(nil).ListRoles), varargs...)
}

// UpdateRoleMembership mocks base method.
func (m *MockSecurityServiceClient) UpdateRoleMembership(ctx context.Context, in *consolev1alpha1.UpdateRoleMembershipRequest, opts ...grpc.CallOption) (*consolev1alpha1.UpdateRoleMembershipResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateRoleMembership", varargs...)
	ret0, _ := ret[0].(*consolev1alpha1.UpdateRoleMembershipResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRoleMembership indicates an expected call of UpdateRoleMembership.
func (mr *MockSecurityServiceClientMockRecorder) UpdateRoleMembership(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRoleMembership", reflect.TypeOf((*MockSecurityServiceClient)(nil).UpdateRoleMembership), varargs...)
}
