// Code generated by MockGen. DO NOT EDIT.
// Source: buf.build/gen/go/redpandadata/cloud/grpc/go/redpanda/api/iam/v1/iamv1grpc (interfaces: ServiceAccountServiceClient)
//
// Generated by this command:
//
//	mockgen -destination=./mock_service_account_service_client.go -package=mocks buf.build/gen/go/redpandadata/cloud/grpc/go/redpanda/api/iam/v1/iamv1grpc ServiceAccountServiceClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	iamv1 "buf.build/gen/go/redpandadata/cloud/protocolbuffers/go/redpanda/api/iam/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockServiceAccountServiceClient is a mock of ServiceAccountServiceClient interface.
type MockServiceAccountServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockServiceAccountServiceClientMockRecorder
	isgomock struct{}
}

// MockServiceAccountServiceClientMockRecorder is the mock recorder for MockServiceAccountServiceClient.
type MockServiceAccountServiceClientMockRecorder struct {
	mock *MockServiceAccountServiceClient
}

// NewMockServiceAccountServiceClient creates a new mock instance.
func NewMockServiceAccountServiceClient(ctrl *gomock.Controller) *MockServiceAccountServiceClient {
	mock := &MockServiceAccountServiceClient{ctrl: ctrl}
	mock.recorder = &MockServiceAccountServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceAccountServiceClient) EXPECT() *MockServiceAccountServiceClientMockRecorder {
	return m.recorder
}

// CreateServiceAccount mocks base method.
func (m *MockServiceAccountServiceClient) CreateServiceAccount(ctx context.Context, in *iamv1.CreateServiceAccountRequest, opts ...grpc.CallOption) (*iamv1.CreateServiceAccountResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateServiceAccount", varargs...)
	ret0, _ := ret[0].(*iamv1.CreateServiceAccountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateServiceAccount indicates an expected call of CreateServiceAccount.
func (mr *MockServiceAccountServiceClientMockRecorder) CreateServiceAccount(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateServiceAccount", reflect.TypeOf((*MockServiceAccountServiceClient)(nil).CreateServiceAccount), varargs...)
}

// DeleteServiceAccount mocks base method.
func (m *MockServiceAccountServiceClient) DeleteServiceAccount(ctx context.Context, in *iamv1.DeleteServiceAccountRequest, opts ...grpc.CallOption) (*iamv1.DeleteServiceAccountResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteServiceAccount", varargs...)
	ret0, _ := ret[0].(*iamv1.DeleteServiceAccountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteServiceAccount indicates an expected call of DeleteServiceAccount.
func (mr *MockServiceAccountServiceClientMockRecorder) DeleteServiceAccount(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteServiceAccount", reflect.TypeOf((*MockServiceAccountServiceClient)(nil).DeleteServiceAccount), varargs...)
}

// GetServiceAccount mocks base method.
func (m *MockServiceAccountServiceClient) GetServiceAccount(ctx context.Context, in *iamv1.GetServiceAccountRequest, opts ...grpc.CallOption) (*iamv1.GetServiceAccountResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetServiceAccount", varargs...)
	ret0, _ := ret[0].(*iamv1.GetServiceAccountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceAccount indicates an expected call of GetServiceAccount.
func (mr *MockServiceAccountServiceClientMockRecorder) GetServiceAccount(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceAccount", reflect.TypeOf((*MockServiceAccountServiceClient)(nil).GetServiceAccount), varargs...)
}

// GetServiceAccountCredentials mocks base method.
func (m *MockServiceAccountServiceClient) GetServiceAccountCredentials(ctx context.Context, in *iamv1.GetServiceAccountCredentialsRequest, opts ...grpc.CallOption) (*iamv1.GetServiceAccountCredentialsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetServiceAccountCredentials", varargs...)
	ret0, _ := ret[0].(*iamv1.GetServiceAccountCredentialsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceAccountCredentials indicates an expected call of GetServiceAccountCredentials.
func (mr *MockServiceAccountServiceClientMockRecorder) GetServiceAccountCredentials(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceAccountCredentials", reflect.TypeOf((*MockServiceAccountServiceClient)(nil).GetServiceAccountCredentials), varargs...)
}

// ListServiceAccounts mocks base method.
func (m *MockServiceAccountServiceClient) ListServiceAccounts(ctx context.Context, in *iamv1.ListServiceAccountsRequest, opts ...grpc.CallOption) (*iamv1.ListServiceAccountsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListServiceAccounts", varargs...)
	ret0, _ := ret[0].(*iamv1.ListServiceAccountsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListServiceAccounts indicates an expected call of ListServiceAccounts.
func (mr *MockServiceAccountServiceClientMockRecorder) ListServiceAccounts(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListServiceAccounts", reflect.TypeOf((*MockServiceAccountServiceClient)(nil).ListServiceAccounts), varargs...)
}

// RotateServiceAccountSecret mocks base method.
func (m *MockServiceAccountServiceClient) RotateServiceAccountSecret(ctx context.Context, in *iamv1.RotateServiceAccountSecretRequest, opts ...grpc.CallOption) (*iamv1.RotateServiceAccountSecretResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RotateServiceAccountSecret", varargs...)
	ret0, _ := ret[0].(*iamv1.RotateServiceAccountSecretResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RotateServiceAccountSecret indicates an expected call of RotateServiceAccountSecret.
func (mr *MockServiceAccountServiceClientMockRecorder) RotateServiceAccountSecret(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RotateServiceAccountSecret", reflect.TypeOf((*MockServiceAccountServiceClient)(nil).RotateServiceAccountSecret), varargs...)
}

// UpdateServiceAccount mocks base method.
func (m *MockServiceAccountServiceClient) UpdateServiceAccount(ctx context.Context, in *iamv1.UpdateServiceAccountRequest, opts ...grpc.CallOption) (*iamv1.UpdateServiceAccountResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateServiceAccount", varargs...)
	ret0, _ := ret[0].(*iamv1.UpdateServiceAccountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateServiceAccount indicates an expected call of UpdateServiceAccount.
func (mr *MockServiceAccountServiceClientMockRecorder) UpdateServiceAccount(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateServiceAccount", reflect.TypeOf((*MockServiceAccountServiceClient)(nil).UpdateServiceAccount), varargs...)
}
