// Code generated by schemagen. DO NOT EDIT.

// Copyright 2023 Redpanda Data, Inc.
//
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

package region

import (
	controlplanev1 "buf.build/gen/go/redpandadata/cloud/protocolbuffers/go/redpanda/api/controlplane/v1"
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/redpanda-data/terraform-provider-redpanda/internal/modelconv"
	"github.com/redpanda-data/terraform-provider-redpanda/redpanda/utils/enums"
)

type DataRegionResponse interface {
	GetCloudProvider() controlplanev1.CloudProvider
	GetName() string
	GetZones() []string
}

// FlattenData populates a *DataModel from the API response payload.
// The prev *DataModel arg carries forward TF-only / sensitive / write-only
// fields that the response cannot supply; pass nil when no prior state exists
// (e.g., during ImportState).
func FlattenData(ctx context.Context, proto DataRegionResponse, prev *DataModel) (*DataModel, diag.Diagnostics) {
	var diags diag.Diagnostics
	m := &DataModel{}
	m.CloudProvider = types.StringValue(enums.CloudProviderToString(proto.GetCloudProvider()))
	m.Name = types.StringValue(proto.GetName())
	m.Zones = modelconv.ListFromSliceWithDiags(ctx, proto.GetZones(), types.StringType, &diags)
	return m, diags
}
