// Code generated by schemagen. DO NOT EDIT.

// Copyright 2023 Redpanda Data, Inc.
//
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.

package network

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"regexp"
)

// DatasourceNetworkSchema returns the Terraform schema for the network datasource.
func DatasourceNetworkSchema(_ context.Context) schema.Schema {
	return schema.Schema{
		Description: "Data source for a Redpanda Cloud network",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "Network ID. The ID is an output of the Create Network request and cannot be set by the caller.",
				Required:    true,
			},

			"cidr_block": schema.StringAttribute{
				Description: "Network CIDR from where public and private subnets are derived. At least a 21 bits CIDR is required.",
				Computed:    true,
				Validators: []validator.String{stringvalidator.RegexMatches(
					regexp.MustCompile(`^(\d{1,3}\.){3}\d{1,3}/(\d{1,2})$`),
					"The value must be a valid CIDR block (e.g., 192.168.0.0/16)",
				)},
			},

			"cloud_provider": schema.StringAttribute{
				Description: "Cloud provider where resources are created.",
				Computed:    true,
				Validators:  []validator.String{stringvalidator.OneOf("", "gcp", "aws")},
			},

			"cluster_type": schema.StringAttribute{
				Description: "Cluster type. Type is immutable and can only be set on cluster creation.",
				Computed:    true,
				Validators:  []validator.String{stringvalidator.OneOf("", "dedicated", "cloud")},
			},

			"customer_managed_resources": schema.SingleNestedAttribute{
				Description: "Cloud resources created by user.",
				Computed:    true,
				Attributes: map[string]schema.Attribute{
					"aws": schema.SingleNestedAttribute{
						Description: "The AWS resources managed by user.",
						Computed:    true,
						Attributes: map[string]schema.Attribute{
							"dynamodb_table": schema.SingleNestedAttribute{
								Description: "AWS DynamoDB table specification.",
								Computed:    true,
								Attributes: map[string]schema.Attribute{
									"arn": schema.StringAttribute{
										Description: "AWS DynamoDB table identifier.",
										Required:    true,
									},
								},
							},
							"management_bucket": schema.SingleNestedAttribute{
								Description: "AWS storage bucket properties by ARN.",
								Computed:    true,
								Attributes: map[string]schema.Attribute{
									"arn": schema.StringAttribute{
										Description: "AWS storage bucket identifier.",
										Required:    true,
									},
								},
							},
							"private_subnets": schema.SingleNestedAttribute{
								Description: "AWS Subnets Specification",
								Computed:    true,
								Attributes: map[string]schema.Attribute{
									"arns": schema.ListAttribute{
										Description: "AWS subnet identifiers.",
										Required:    true,
										ElementType: types.StringType,
									},
								},
							},
							"vpc": schema.SingleNestedAttribute{
								Description: "AWS VPC Specification",
								Computed:    true,
								Attributes: map[string]schema.Attribute{
									"arn": schema.StringAttribute{
										Description: "AWS VPC identifier.",
										Required:    true,
									},
								},
							},
						},
					},
					"gcp": schema.SingleNestedAttribute{
						Description: "GCP resources created and managed by user, and required to deploy the Redpanda cluster. See [Create a BYOVPC Cluster on GCP](https://docs.redpanda.com/redpanda-cloud/get-started/cluster-types/byoc/gcp/vpc-byo-gcp/) for details.",
						Computed:    true,
						Attributes: map[string]schema.Attribute{
							"management_bucket": schema.SingleNestedAttribute{
								Description: "GCP storage bucket properties.",
								Computed:    true,
								Attributes: map[string]schema.Attribute{
									"name": schema.StringAttribute{
										Description: "Name of GCP storage bucket. See the official [GCP documentation](https://cloud.google.com/storage/docs/buckets#naming) for naming restrictions.",
										Required:    true,
									},
								},
							},
							"network_name": schema.StringAttribute{
								Description: "Name of user-created network where the Redpanda cluster is deployed to. See the official [GCP API reference](https://cloud.google.com/compute/docs/reference/rest/v1/networks).",
								Computed:    true,
							},
							"network_project_id": schema.StringAttribute{
								Description: "GCP project ID where the network is created.",
								Computed:    true,
							},
						},
					},
				},
			},

			"name": schema.StringAttribute{
				Description: "The unique name of the network.",
				Computed:    true,
			},

			"region": schema.StringAttribute{
				Description: "Region where network is placed.",
				Computed:    true,
			},

			"resource_group_id": schema.StringAttribute{
				Description: "Resource group ID of the network",
				Computed:    true,
			},

			"state": schema.StringAttribute{
				Description: "Current state of the network.",
				Computed:    true,
			},

			"zones": schema.ListAttribute{
				Description: "Network availability zones.",
				Computed:    true,
				ElementType: types.StringType,
			},
		},
	}
}
