message: "Redpanda Cloud RBAC role"
api_schema: Role
tf_name: Role

api:
  delete:
    flat_field_map:
      role_name: name                   # proto role_name → TF tag "name"

exclude_operations: [update]            # roles are immutable

name:
  required: true
  plan_modifiers: [RequiresReplace]

id:
  extra: true
  type: string
  computed_only: true

cluster_api_url:
  extra: true
  type: string
  required: true
  plan_modifiers: [RequiresReplace]

allow_deletion:
  extra: true
  type: bool
  optional: true
  computed: true
  default: false

delete_acls:
  extra: true
  type: bool
  optional: true
  computed: true
  default: false
